#!/usr/bin/env node
// Bounded deterministic macro fuzzer for `kofun bindgen-c` (#901).
//
//   node fuzz-macros.mjs KOFUN CORPUS_DIR WORK_DIR
//
// Mutates the committed adversarial corpus inside fixed budgets and requires
// exactly one of two outcomes from every single case:
//
//   accept   the tool exits 0, twice, with byte-identical module and report,
//            and the generated bytes fit the output bound;
//   refuse   the tool exits nonzero with a diagnostic that names a cause,
//            and leaves NO output directory behind.
//
// Anything else is a defect and fails the run by name: a hang (the driver's
// own watchdog fires before the tool's bound does), a crash (killed by a
// signal, or an exit code the tool never produces), a silent refusal, a
// partial `--out-dir`, output past the byte bound, or two runs of the same
// input disagreeing.
//
// Determinism, because a fuzz failure nobody can reproduce is a rumour:
//
//   * the seed is a constant in this file. There is no clock, no PID, no
//     /dev/urandom, and no environment variable anywhere in the generator;
//   * the corpus is committed, and the file list is sorted before use;
//   * the case count, the mutation count per case, the byte cap, the
//     per-case wall-clock cap, and the total wall-clock cap are constants;
//   * the summary this prints names outcomes and causes, never clang's
//     prose, so it is stable across clang builds and can be compared byte
//     for byte between two runs.
//
// Nothing reaches a shell: the tool is spawned through execFileSync with a
// structured argv and a closed stdin, and mutated headers only ever travel
// as file bytes.

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

// ------------------------------------------------------------ the budgets
const SEED = 0x6b626669;          // "kbfi"; a constant, never derived
const CASES = 32;                 // fixed case count
const MUTATIONS_PER_CASE = 3;     // fixed mutation count
const MAX_CASE_BYTES = 96 * 1024; // a mutated header may not exceed this
const MAX_OUTPUT_BYTES = 8 * 1024 * 1024; // total generated bytes per case
const CASE_TIMEOUT_MS = 45000;    // driver watchdog, above the tool's own bound
const TOTAL_BUDGET_MS = 600000;   // whole-run wall clock

// The tool's own refusals, in the order they are matched. Each maps to a
// stable category so the summary never carries clang's wording.
const CAUSES = [
  ['too many top-level declarations', 'decl-bound'],
  ['output exceeded the', 'output-bound'],
  ['preprocessor output exceeds', 'preprocessor-bound'],
  ['exceeded the', 'timeout'],
  ['clang failed on', 'clang-refused'],
  ['clang AST is not parseable JSON', 'ast-unparseable'],
  ['clang did not produce a TranslationUnitDecl', 'no-translation-unit'],
  ['header not found', 'missing-header'],
  ['the input must be a .h header', 'not-a-header'],
];

function fail(message) {
  process.stderr.write(`FAIL: bindgen-c fuzz: ${message}\n`);
  process.exit(1);
}

// xorshift32. Small, exactly reproducible, and it is not pretending to be a
// cryptographic source — it only has to pick the same cases every time.
function makeRandom(seed) {
  let state = seed >>> 0;
  if (state === 0) state = 0x9e3779b9;
  return (bound) => {
    state ^= state << 13; state >>>= 0;
    state ^= state >>> 17;
    state ^= state << 5; state >>>= 0;
    return bound <= 0 ? 0 : state % bound;
  };
}

const IDENTIFIER_ANYWHERE = /[A-Za-z_][A-Za-z0-9_]*/g;

// Each mutation is a pure function of (lines, random). None of them consults
// anything outside its arguments.
const MUTATIONS = [
  ['duplicate-define', (lines, random) => {
    const defines = lines.filter((line) => line.startsWith('#define'));
    if (defines.length === 0) return lines;
    const chosen = defines[random(defines.length)];
    const at = random(lines.length + 1);
    return [...lines.slice(0, at), chosen, ...lines.slice(at)];
  }],
  ['self-reference', (lines, random) => {
    const indexes = lines
      .map((line, index) => (/^#define\s+[A-Za-z_][A-Za-z0-9_]*\s+\S/.test(line) ? index : -1))
      .filter((index) => index >= 0);
    if (indexes.length === 0) return lines;
    const index = indexes[random(indexes.length)];
    const name = /^#define\s+([A-Za-z_][A-Za-z0-9_]*)/.exec(lines[index])[1];
    const copy = [...lines];
    copy[index] = `${lines[index]} ${name}`;
    return copy;
  }],
  ['paste-inject', (lines, random) => {
    const indexes = lines
      .map((line, index) => (line.includes(' ') && !line.startsWith('/*') ? index : -1))
      .filter((index) => index >= 0);
    if (indexes.length === 0) return lines;
    const index = indexes[random(indexes.length)];
    const copy = [...lines];
    copy[index] = lines[index].replace(' ', ' ## ');
    return copy;
  }],
  ['stringize-inject', (lines, random) => {
    const indexes = lines
      .map((line, index) => (line.startsWith('#define') && line.includes('(') ? index : -1))
      .filter((index) => index >= 0);
    if (indexes.length === 0) return lines;
    const index = indexes[random(indexes.length)];
    const copy = [...lines];
    copy[index] = lines[index].replace(/([A-Za-z_][A-Za-z0-9_]*)\s*$/, '#$1');
    return copy;
  }],
  ['lengthen-identifier', (lines, random) => {
    const indexes = lines
      .map((line, index) => (IDENTIFIER_ANYWHERE.test(line) ? index : -1))
      .filter((index) => index >= 0);
    IDENTIFIER_ANYWHERE.lastIndex = 0;
    if (indexes.length === 0) return lines;
    const index = indexes[random(indexes.length)];
    const copy = [...lines];
    const padding = 'z'.repeat(64 + random(200));
    copy[index] = lines[index].replace(/([A-Za-z_][A-Za-z0-9_]*)/, `$1_${padding}`);
    return copy;
  }],
  ['truncate', (lines, random) => {
    if (lines.length < 4) return lines;
    return lines.slice(0, 2 + random(lines.length - 2));
  }],
  ['drop-line', (lines, random) => {
    if (lines.length === 0) return lines;
    const index = random(lines.length);
    return [...lines.slice(0, index), ...lines.slice(index + 1)];
  }],
  ['repeat-line', (lines, random) => {
    if (lines.length === 0) return lines;
    const index = random(lines.length);
    const times = 2 + random(30);
    const repeated = new Array(times).fill(lines[index]);
    return [...lines.slice(0, index), ...repeated, ...lines.slice(index + 1)];
  }],
  ['swap-lines', (lines, random) => {
    if (lines.length < 2) return lines;
    const a = random(lines.length);
    const b = random(lines.length);
    const copy = [...lines];
    const held = copy[a];
    copy[a] = copy[b];
    copy[b] = held;
    return copy;
  }],
  ['recursive-pair', (lines, random) => {
    const names = [];
    for (const line of lines) {
      const match = /^#define\s+([A-Za-z_][A-Za-z0-9_]*)/.exec(line);
      if (match) names.push(match[1]);
    }
    if (names.length < 2) return lines;
    const left = names[random(names.length)];
    const right = names[random(names.length)];
    return [...lines,
      `#define KBF_FUZZ_PING ${left} KBF_FUZZ_PONG`,
      `#define KBF_FUZZ_PONG ${right} KBF_FUZZ_PING`,
      'long kbfuzz_recursive_pair(long KBF_FUZZ_PING);'];
  }],
];

function directoryBytes(directory) {
  let total = 0;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const full = path.join(directory, entry.name);
    total += entry.isDirectory() ? directoryBytes(full) : statSync(full).size;
  }
  return total;
}

function readDirectoryFiles(directory) {
  const files = new Map();
  for (const entry of readdirSync(directory, { withFileTypes: true }).sort(
    (a, b) => (a.name < b.name ? -1 : 1))) {
    if (!entry.isFile()) continue;
    files.set(entry.name, readFileSync(path.join(directory, entry.name)));
  }
  return files;
}

// One `kofun bindgen-c` invocation. Structured argv, closed stdin, bounded
// captured output, and a watchdog above the tool's own timeout so that a
// watchdog kill is by construction a tool that failed to bound itself.
function runTool(kofun, headerPath, outDir) {
  try {
    execFileSync(kofun, ['bindgen-c', headerPath, '--out-dir', outDir, '--module', 'kbfuzz'], {
      encoding: 'utf8',
      timeout: CASE_TIMEOUT_MS,
      killSignal: 'SIGKILL',
      maxBuffer: 8 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return { status: 0, stderr: '', watchdog: false };
  } catch (error) {
    const watchdog = error.code === 'ETIMEDOUT' || error.killed === true;
    return {
      status: typeof error.status === 'number' ? error.status : -1,
      stderr: error.stderr ? String(error.stderr) : String(error.message),
      watchdog,
      signal: error.signal || null,
    };
  }
}

function categorize(stderr) {
  for (const [needle, category] of CAUSES) {
    if (stderr.includes(needle)) return category;
  }
  return 'other';
}

// One case: run the tool twice on the same input and classify the outcome.
function classify(label, kofun, headerPath, workDir) {
  const outA = path.join(workDir, 'out-a');
  const outB = path.join(workDir, 'out-b');
  rmSync(outA, { recursive: true, force: true });
  rmSync(outB, { recursive: true, force: true });

  const first = runTool(kofun, headerPath, outA);
  if (first.watchdog) {
    fail(`${label}: the tool did not return inside ${CASE_TIMEOUT_MS} ms; ` +
      'its own clang bound should have fired first');
  }
  if (first.status !== 0 && first.status !== 2) {
    fail(`${label}: the tool exited ${first.status}` +
      `${first.signal ? ` (signal ${first.signal})` : ''}, which is neither ` +
      'success nor its refusal code 2; a crash is not a refusal');
  }

  let outAExists = true;
  try {
    statSync(outA);
  } catch {
    outAExists = false;
  }

  if (first.status !== 0) {
    if (first.stderr.trim() === '') {
      fail(`${label}: the tool refused without saying why`);
    }
    if (outAExists) {
      fail(`${label}: the tool refused but left an output directory behind`);
    }
    return `refuse:${categorize(first.stderr)}`;
  }

  if (!outAExists) {
    fail(`${label}: the tool reported success but wrote no output directory`);
  }
  const bytes = directoryBytes(outA);
  if (bytes > MAX_OUTPUT_BYTES) {
    fail(`${label}: generated ${bytes} bytes, past the ${MAX_OUTPUT_BYTES} byte bound`);
  }

  const second = runTool(kofun, headerPath, outB);
  if (second.status !== 0) {
    fail(`${label}: the same input was accepted and then refused: ${second.stderr.trim()}`);
  }
  const filesA = readDirectoryFiles(outA);
  const filesB = readDirectoryFiles(outB);
  if (filesA.size !== filesB.size) {
    fail(`${label}: two runs produced different file sets`);
  }
  for (const [name, contentA] of filesA) {
    const contentB = filesB.get(name);
    if (contentB === undefined) {
      fail(`${label}: ${name} appeared in one run and not the other`);
    }
    if (!contentA.equals(contentB)) {
      fail(`${label}: two runs produced different bytes for ${name}`);
    }
  }
  return 'accept';
}

// -------------------------------------------------------------------- main
if (process.argv.length !== 5) {
  process.stderr.write('usage: node fuzz-macros.mjs KOFUN CORPUS_DIR WORK_DIR\n');
  process.exit(2);
}
const [kofun, corpusDir, workDir] = process.argv.slice(2);

const corpusNames = readdirSync(corpusDir)
  .filter((name) => name.endsWith('.h'))
  .sort();
if (corpusNames.length === 0) {
  fail('the committed corpus is empty; this run would prove nothing');
}

mkdirSync(workDir, { recursive: true });
const startedAt = Date.now();
const summary = [];
const counts = new Map();
const note = (outcome) => counts.set(outcome, (counts.get(outcome) || 0) + 1);

// Pass one: every committed corpus file, unmutated. These are the cases a
// reader can reproduce by hand.
for (const name of corpusNames) {
  const caseDir = path.join(workDir, `corpus-${name.replace(/\.h$/, '')}`);
  mkdirSync(caseDir, { recursive: true });
  const outcome = classify(`corpus ${name}`, kofun,
    path.join(corpusDir, name), caseDir);
  summary.push(`corpus\t${name}\t-\t${outcome}`);
  note(outcome);
}

// Pass two: seeded mutations of those files.
const random = makeRandom(SEED);
for (let index = 0; index < CASES; index += 1) {
  if (Date.now() - startedAt > TOTAL_BUDGET_MS) {
    fail(`the run passed its ${TOTAL_BUDGET_MS} ms total budget at case ${index}`);
  }
  const source = corpusNames[random(corpusNames.length)];
  let lines = readFileSync(path.join(corpusDir, source), 'utf8').split('\n');
  const applied = [];
  for (let step = 0; step < MUTATIONS_PER_CASE; step += 1) {
    const [mutationName, mutate] = MUTATIONS[random(MUTATIONS.length)];
    lines = mutate(lines, random);
    applied.push(mutationName);
  }
  let text = `${lines.join('\n')}\n`;
  if (text.length > MAX_CASE_BYTES) text = `${text.slice(0, MAX_CASE_BYTES)}\n`;

  const label = String(index).padStart(3, '0');
  const caseDir = path.join(workDir, `case-${label}`);
  mkdirSync(caseDir, { recursive: true });
  const headerPath = path.join(caseDir, 'kbfuzz.h');
  writeFileSync(headerPath, text, 'utf8');

  const outcome = classify(`case ${label} (${source}: ${applied.join(',')})`,
    kofun, headerPath, caseDir);
  summary.push(`case\t${label}\t${source}:${applied.join(',')}\t${outcome}`);
  note(outcome);
}

// The corpus has to discriminate. A run where everything was accepted, or
// everything refused, would pass every rule above while checking nothing.
const accepted = counts.get('accept') || 0;
const refused = [...counts.entries()]
  .filter(([outcome]) => outcome.startsWith('refuse:'))
  .reduce((total, [, count]) => total + count, 0);
if (accepted === 0) fail('no case was accepted; the corpus proves nothing about determinism');
if (refused === 0) fail('no case was refused; the corpus proves nothing about the bounds');

for (const line of summary) process.stdout.write(`${line}\n`);
process.stdout.write('--\n');
for (const outcome of [...counts.keys()].sort()) {
  process.stdout.write(`${outcome}\t${counts.get(outcome)}\n`);
}
process.stdout.write(`total\t${summary.length}\n`);
process.stdout.write(`seed\t${SEED}\n`);
