#!/usr/bin/env sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
KOFUN="$ROOT/bin/kofun"
FIXTURE="$ROOT/bootstrap/fixtures/answer.kofun"
WORK="${KOFUN_CLI_TEST_WORK:-$ROOT/build/cli-test}"

rm -rf "$WORK"
mkdir -p "$WORK"

test "$("$KOFUN" --version)" = "Kofun Stage 1 0.3.0-seed"
"$KOFUN" check "$FIXTURE" >/dev/null
test "$("$KOFUN" run "$FIXTURE")" = "42"

"$KOFUN" build "$FIXTURE" -o "$WORK/answer" --emit-c "$WORK/answer.c" >/dev/null
test "$("$WORK/answer")" = "42"
grep -q "Generated by the Kofun-written Stage 1 seed compiler" "$WORK/answer.c"

"$KOFUN" test "$ROOT/bootstrap/fixtures" | grep -q "1 passed; 0 failed"

cp "$FIXTURE" "$WORK/legacy.kf"
if "$KOFUN" check "$WORK/legacy.kf" >/dev/null 2>&1; then
    printf '%s\n' "FAIL: legacy .kf extension was accepted" >&2
    exit 1
fi

printf '%s\n' "PASS: Python-free Kofun CLI build/run/check/test"
