/* Generated by the Kofun-written Stage 1 seed compiler. */
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

static bool failed;

static void runtime_error(const char *message) {
    if (!failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    failed = true;
}

static int64_t checked_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t checked_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t checked_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t checked_neg(int64_t value) {
    if (value == INT64_MIN) {
        runtime_error("error[R010]: integer overflow in unary operator `-`");
        return 0;
    }
    return -value;
}

static int64_t floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `//` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        runtime_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;
    return quotient;
}

static int64_t floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `%` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) return 0;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;
    return remainder;
}

int main(void) {
    (void)checked_add;
    (void)checked_sub;
    (void)checked_mul;
    (void)checked_neg;
    (void)floor_div;
    (void)floor_mod;
    bool kf_equal;
    {
        bool kt_x = 7 == 7;
        kf_equal = kt_x;
    }
    if (failed) return 1;
    (void)kf_equal;
    bool kf_different;
    {
        bool kt_x = 7 != 8;
        kf_different = kt_x;
    }
    if (failed) return 1;
    (void)kf_different;
    bool kf_less;
    {
        int64_t kt_xl = checked_add(1, 2);
        int64_t kt_xr = checked_mul(4, 2);
        bool kt_x = kt_xl < kt_xr;
        kf_less = kt_x;
    }
    if (failed) return 1;
    (void)kf_less;
    bool kf_less_equal;
    {
        bool kt_x = 3 <= 3;
        kf_less_equal = kt_x;
    }
    if (failed) return 1;
    (void)kf_less_equal;
    bool kf_greater;
    {
        bool kt_x = 9 > 4;
        kf_greater = kt_x;
    }
    if (failed) return 1;
    (void)kf_greater;
    bool kf_greater_equal;
    {
        bool kt_x = 9 >= 9;
        kf_greater_equal = kt_x;
    }
    if (failed) return 1;
    (void)kf_greater_equal;
    bool kf_bool_equal;
    {
        bool kt_x = true != false;
        kf_bool_equal = kt_x;
    }
    if (failed) return 1;
    (void)kf_bool_equal;
    bool kf_negated;
    {
        bool kt_x = !false;
        kf_negated = kt_x;
    }
    if (failed) return 1;
    (void)kf_negated;
    bool kf_ordered;
    {
        bool kt_xllll = kf_equal;
        if (!failed && kt_xllll) {
            kt_xllll = kf_different;
        }
        bool kt_xlll = kt_xllll;
        if (!failed && kt_xlll) {
            kt_xlll = kf_less;
        }
        bool kt_xll = kt_xlll;
        if (!failed && kt_xll) {
            kt_xll = kf_less_equal;
        }
        bool kt_xl = kt_xll;
        if (!failed && kt_xl) {
            kt_xl = kf_greater;
        }
        bool kt_x = kt_xl;
        if (!failed && kt_x) {
            kt_x = kf_greater_equal;
        }
        kf_ordered = kt_x;
    }
    if (failed) return 1;
    (void)kf_ordered;
    bool kf_precedence;
    {
        bool kt_x = false;
        if (!failed && !kt_x) {
        bool kt_xr = true;
        if (!failed && kt_xr) {
            kt_xr = kf_negated;
        }
            kt_x = kt_xr;
        }
        kf_precedence = kt_x;
    }
    if (failed) return 1;
    (void)kf_precedence;
    bool kf_short_and;
    {
        bool kt_x = false;
        if (!failed && kt_x) {
        int64_t kt_xrl = floor_div(1, 0);
        bool kt_xr = kt_xrl == 0;
            kt_x = kt_xr;
        }
        kf_short_and = kt_x;
    }
    if (failed) return 1;
    (void)kf_short_and;
    bool kf_short_or;
    {
        bool kt_x = true;
        if (!failed && !kt_x) {
        int64_t kt_xrl = floor_div(1, 0);
        bool kt_xr = kt_xrl == 0;
            kt_x = kt_xr;
        }
        kf_short_or = kt_x;
    }
    if (failed) return 1;
    (void)kf_short_or;
    bool kf_accepted;
    {
        bool kt_xlll = kf_ordered;
        if (!failed && kt_xlll) {
            kt_xlll = kf_bool_equal;
        }
        bool kt_xll = kt_xlll;
        if (!failed && kt_xll) {
            kt_xll = kf_precedence;
        }
        bool kt_xl = kt_xll;
        if (!failed && kt_xl) {
        bool kt_xlr = !kf_short_and;
            kt_xl = kt_xlr;
        }
        bool kt_x = kt_xl;
        if (!failed && kt_x) {
            kt_x = kf_short_or;
        }
        kf_accepted = kt_x;
    }
    if (failed) return 1;
    (void)kf_accepted;
    {
        int64_t value = 42;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    return 0;
}
