/* Generated by the Kofun-written Stage 1 seed compiler. */
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

static bool failed;

static void runtime_error(const char *message) {
    if (!failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    failed = true;
}

static int64_t checked_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t checked_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t checked_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t checked_neg(int64_t value) {
    if (value == INT64_MIN) {
        runtime_error("error[R010]: integer overflow in unary operator `-`");
        return 0;
    }
    return -value;
}

static int64_t floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `//` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        runtime_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;
    return quotient;
}

static int64_t floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `%` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) return 0;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;
    return remainder;
}

int main(void) {
    (void)checked_add;
    (void)checked_sub;
    (void)checked_mul;
    (void)checked_neg;
    (void)floor_div;
    (void)floor_mod;
    int64_t kf_six;
    {
        int64_t kt_x = checked_mul(2, 3);
        kf_six = kt_x;
    }
    if (failed) return 1;
    (void)kf_six;
    int64_t kf_answer;
    {
        int64_t kt_x = checked_mul(kf_six, 7);
        kf_answer = kt_x;
    }
    if (failed) return 1;
    (void)kf_answer;
    {
        int64_t value = kf_answer;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        int64_t kt_xr = checked_mul(2, 3);
        int64_t kt_x = checked_add(1, kt_xr);
        int64_t value = kt_x;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        int64_t kt_x = floor_div(-7, 2);
        int64_t value = kt_x;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        int64_t kt_x = floor_mod(-7, 2);
        int64_t value = kt_x;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        int64_t kt_xl = checked_sub(kf_answer, 2);
        int64_t kt_x = floor_div(kt_xl, 8);
        int64_t value = kt_x;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    return 0;
}
