/* Generated by the Kofun-written Stage 1 seed compiler. */
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

static bool failed;

static void runtime_error(const char *message) {
    if (!failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    failed = true;
}

static int64_t checked_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t checked_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t checked_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t checked_neg(int64_t value) {
    if (value == INT64_MIN) {
        runtime_error("error[R010]: integer overflow in unary operator `-`");
        return 0;
    }
    return -value;
}

static int64_t floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `//` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        runtime_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;
    return quotient;
}

static int64_t floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `%` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) return 0;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;
    return remainder;
}

int main(void) {
    (void)checked_add;
    (void)checked_sub;
    (void)checked_mul;
    (void)checked_neg;
    (void)floor_div;
    (void)floor_mod;
    int64_t kf_limit;
    {
        kf_limit = 3;
    }
    if (failed) return 1;
    (void)kf_limit;
    {
        int64_t kt_from = 0;
        int64_t kt_to = kf_limit;
        if (failed) return 1;
        for (int64_t kf_index = kt_from; kf_index < kt_to; ++kf_index) {
            (void)kf_index;
            {
                int64_t value = kf_index;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
    }
    int64_t kf_index;
    {
        kf_index = 9;
    }
    if (failed) return 1;
    (void)kf_index;
    {
        int64_t value = kf_index;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        int64_t kt_from = 0;
        int64_t kt_to = 2;
        if (failed) return 1;
        for (int64_t kf_outer = kt_from; kf_outer < kt_to; ++kf_outer) {
            (void)kf_outer;
            {
                int64_t kt_from = 0;
                int64_t kt_to = 2;
                if (failed) return 1;
                for (int64_t kf_inner = kt_from; kf_inner < kt_to; ++kf_inner) {
                    (void)kf_inner;
                    {
                        int64_t kt_xl = checked_mul(kf_outer, 10);
                        int64_t kt_x = checked_add(kt_xl, kf_inner);
                        int64_t value = kt_x;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
            }
        }
    }
    {
        int64_t kt_from = 0;
        int64_t kt_to = 3;
        if (failed) return 1;
        for (int64_t kf_guarded = kt_from; kf_guarded < kt_to; ++kf_guarded) {
            (void)kf_guarded;
            {
                bool kt_taken = false;
                bool kt_cond;
                {
                    bool kt_x = kf_guarded == 1;
                    kt_cond = kt_x;
                }
                if (failed) return 1;
                if (kt_cond) {
                    kt_taken = true;
                    {
                        int64_t value = 100;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
                if (!kt_taken) {
                    {
                        int64_t value = kf_guarded;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
                (void)kt_taken;
            }
        }
    }
    {
        bool kt_taken = false;
        bool kt_cond;
        {
            bool kt_x = kf_limit > 0;
            kt_cond = kt_x;
        }
        if (failed) return 1;
        if (kt_cond) {
            kt_taken = true;
            {
                int64_t kt_from = 0;
                int64_t kt_to = 2;
                if (failed) return 1;
                for (int64_t kf_nested = kt_from; kf_nested < kt_to; ++kf_nested) {
                    (void)kf_nested;
                    {
                        int64_t kt_x = checked_add(200, kf_nested);
                        int64_t value = kt_x;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
            }
        }
        (void)kt_taken;
    }
    {
        bool kt_cond;
        while (true) {
            bool kt_x = kf_limit < 0;
            kt_cond = kt_x;
            if (failed) return 1;
            if (!kt_cond) break;
            {
                int64_t kt_x = floor_div(1, 0);
                int64_t value = kt_x;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
    }
    {
        int64_t kt_from = 0;
        int64_t kt_to = 1;
        if (failed) return 1;
        for (int64_t kf_scoped = kt_from; kf_scoped < kt_to; ++kf_scoped) {
            (void)kf_scoped;
            {
                bool kt_cond;
                while (true) {
                    bool kt_x = kf_scoped > kf_limit;
                    kt_cond = kt_x;
                    if (failed) return 1;
                    if (!kt_cond) break;
                    {
                        int64_t kt_x = floor_div(1, 0);
                        int64_t value = kt_x;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
            }
            {
                int64_t kt_x = checked_add(300, kf_scoped);
                int64_t value = kt_x;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
    }
    {
        int64_t kt_from = 5;
        int64_t kt_to = 5;
        if (failed) return 1;
        for (int64_t kf_empty = kt_from; kf_empty < kt_to; ++kf_empty) {
            (void)kf_empty;
            {
                int64_t kt_x = floor_div(1, 0);
                int64_t value = kt_x;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
    }
    {
        int64_t value = kf_limit;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    return 0;
}
