/* Generated by the Kofun-written Stage 1 seed compiler. */
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static bool failed;

static void runtime_error(const char *message) {
    if (!failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    failed = true;
}

static int64_t checked_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t checked_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t checked_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t checked_neg(int64_t value) {
    if (value == INT64_MIN) {
        runtime_error("error[R010]: integer overflow in unary operator `-`");
        return 0;
    }
    return -value;
}

static int64_t floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `//` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        runtime_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;
    return quotient;
}

static int64_t floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `%` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) return 0;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;
    return remainder;
}

typedef struct KofunTextAllocation {
    struct KofunTextAllocation *next;
    char bytes[];
} KofunTextAllocation;

static KofunTextAllocation *kofun_rt_text_allocations;

static void kofun_rt_text_cleanup(void) {
    while (kofun_rt_text_allocations != NULL) {
        KofunTextAllocation *allocation = kofun_rt_text_allocations;
        kofun_rt_text_allocations = allocation->next;
        free(allocation);
    }
}

static const char *kofun_rt_text_concat(const char *left, const char *right) {
    size_t left_size = strlen(left);
    size_t right_size = strlen(right);
    if (right_size == SIZE_MAX || left_size > SIZE_MAX - right_size - 1) {
        runtime_error("error[R010]: Text concatenation is too large");
        return "";
    }
    size_t payload_size = left_size + right_size + 1;
    if (payload_size > SIZE_MAX - sizeof(KofunTextAllocation)) {
        runtime_error("error[R010]: Text concatenation is too large");
        return "";
    }
    KofunTextAllocation *allocation =
        malloc(sizeof(KofunTextAllocation) + payload_size);
    if (allocation == NULL) {
        runtime_error("error[R010]: Text allocation failed");
        return "";
    }
    memcpy(allocation->bytes, left, left_size);
    memcpy(allocation->bytes + left_size, right, right_size);
    allocation->bytes[left_size + right_size] = '\0';
    allocation->next = kofun_rt_text_allocations;
    kofun_rt_text_allocations = allocation;
    return allocation->bytes;
}

static bool kofun_rt_text_equal(const char *left, const char *right) {
    while (*left != '\0' && *right != '\0') {
        if (*left != *right) return false;
        left += 1;
        right += 1;
    }
    return *left == *right;
}

int main(void) {
    (void)checked_add;
    (void)checked_sub;
    (void)checked_mul;
    (void)checked_neg;
    (void)floor_div;
    (void)floor_mod;
    if (atexit(kofun_rt_text_cleanup) != 0) {
        runtime_error("error[R010]: Text cleanup registration failed");
        return 1;
    }
    (void)kofun_rt_text_concat;
    (void)kofun_rt_text_equal;
    const char * kf_greeting;
    {
        kf_greeting = "kofun";
    }
    if (failed) return 1;
    (void)kf_greeting;
    const char * kf_joined;
    {
        const char * kt_xl = kofun_rt_text_concat(kf_greeting, " ");
        const char * kt_x = kofun_rt_text_concat(kt_xl, "compiler");
        kf_joined = kt_x;
    }
    if (failed) return 1;
    (void)kf_joined;
    const char * kf_punctuation;
    {
        kf_punctuation = "(+ || ==)";
    }
    if (failed) return 1;
    (void)kf_punctuation;
    bool kf_equal;
    {
        bool kt_x = kofun_rt_text_equal(kf_joined, "kofun compiler");
        kf_equal = kt_x;
    }
    if (failed) return 1;
    (void)kf_equal;
    bool kf_different;
    {
        bool kt_x = !kofun_rt_text_equal(kf_punctuation, "(bad)");
        kf_different = kt_x;
    }
    if (failed) return 1;
    (void)kf_different;
    {
        const char * value = kf_joined;
        if (failed) return 1;
        fputs(value, stdout);
        fputc('\n', stdout);
    }
    {
        const char * value = "line\nquote:\" slash:\\";
        if (failed) return 1;
        fputs(value, stdout);
        fputc('\n', stdout);
    }
    {
        const char * value = kf_punctuation;
        if (failed) return 1;
        fputs(value, stdout);
        fputc('\n', stdout);
    }
    {
        bool kt_taken = false;
        bool kt_cond;
        {
            bool kt_x = kf_equal;
            if (!failed && kt_x) {
                kt_x = kf_different;
            }
            kt_cond = kt_x;
        }
        if (failed) return 1;
        if (kt_cond) {
            kt_taken = true;
            {
                const char * value = "equal";
                if (failed) return 1;
                fputs(value, stdout);
                fputc('\n', stdout);
            }
        }
        (void)kt_taken;
    }
    {
        int64_t value = 42;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    return 0;
}
