/* Generated by the Kofun-written Stage 1 seed compiler. */
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

static bool failed;

static void runtime_error(const char *message) {
    if (!failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    failed = true;
}

static int64_t checked_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t checked_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t checked_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t checked_neg(int64_t value) {
    if (value == INT64_MIN) {
        runtime_error("error[R010]: integer overflow in unary operator `-`");
        return 0;
    }
    return -value;
}

static int64_t floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `//` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        runtime_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;
    return quotient;
}

static int64_t floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `%` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) return 0;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;
    return remainder;
}

int main(void) {
    (void)checked_add;
    (void)checked_sub;
    (void)checked_mul;
    (void)checked_neg;
    (void)floor_div;
    (void)floor_mod;
    int64_t kf_limit;
    {
        kf_limit = 3;
    }
    if (failed) return 1;
    (void)kf_limit;
    {
        int64_t kt_start;
        int64_t kt_end;
        {
            kt_start = 0;
        }
        {
            kt_end = kf_limit;
        }
        if (failed) return 1;
        for (int64_t kf_step = kt_start; kf_step < kt_end; ++kf_step) {
            {
                int64_t value = kf_step;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
    }
    {
        int64_t kt_start;
        int64_t kt_end;
        {
            kt_start = 0;
        }
        {
            kt_end = 2;
        }
        if (failed) return 1;
        for (int64_t kf_outer = kt_start; kf_outer < kt_end; ++kf_outer) {
            {
                int64_t kt_start;
                int64_t kt_end;
                {
                    kt_start = 0;
                }
                {
                    kt_end = 2;
                }
                if (failed) return 1;
                for (int64_t kf_inner = kt_start; kf_inner < kt_end; ++kf_inner) {
                    int64_t kf_cell;
                    {
                        int64_t kt_xl = checked_mul(kf_outer, 10);
                        int64_t kt_x = checked_add(kt_xl, kf_inner);
                        kf_cell = kt_x;
                    }
                    if (failed) return 1;
                    (void)kf_cell;
                    {
                        int64_t value = kf_cell;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
            }
        }
    }
    {
        int64_t kt_start;
        int64_t kt_end;
        {
            kt_start = 0;
        }
        {
            kt_end = 3;
        }
        if (failed) return 1;
        for (int64_t kf_step = kt_start; kf_step < kt_end; ++kf_step) {
            {
                bool kt_taken = false;
                bool kt_cond;
                {
                    bool kt_x = kf_step == 0;
                    kt_cond = kt_x;
                }
                if (failed) return 1;
                if (kt_cond) {
                    kt_taken = true;
                    {
                        int64_t value = 100;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
                if (!kt_taken) {
                    bool kt_x = kf_step == 1;
                    kt_cond = kt_x;
                    if (failed) return 1;
                } else {
                    kt_cond = false;
                }
                if (kt_cond) {
                    kt_taken = true;
                    {
                        int64_t value = 200;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
                if (!kt_taken) {
                    int64_t kf_scaled;
                    {
                        int64_t kt_x = checked_mul(kf_step, 300);
                        kf_scaled = kt_x;
                    }
                    if (failed) return 1;
                    (void)kf_scaled;
                    {
                        int64_t value = kf_scaled;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
                (void)kt_taken;
            }
        }
    }
    {
        bool kt_cond;
        for (;;) {
            {
                bool kt_x = kf_limit < 0;
                kt_cond = kt_x;
            }
            if (failed) return 1;
            if (!kt_cond) break;
            {
                int64_t kt_x = floor_div(1, 0);
                int64_t value = kt_x;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
    }
    {
        int64_t kt_start;
        int64_t kt_end;
        {
            kt_start = 0;
        }
        {
            kt_end = 2;
        }
        if (failed) return 1;
        for (int64_t kf_step = kt_start; kf_step < kt_end; ++kf_step) {
            {
                bool kt_cond;
                for (;;) {
                    {
                        bool kt_x = kf_step > kf_limit;
                        kt_cond = kt_x;
                    }
                    if (failed) return 1;
                    if (!kt_cond) break;
                    {
                        int64_t kt_x = floor_div(1, 0);
                        int64_t value = kt_x;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
            }
            {
                int64_t value = kf_step;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
    }
    {
        bool kt_taken = false;
        bool kt_cond;
        {
            bool kt_x = kf_limit > 0;
            kt_cond = kt_x;
        }
        if (failed) return 1;
        if (kt_cond) {
            kt_taken = true;
            {
                int64_t kt_start;
                int64_t kt_end;
                {
                    kt_start = kf_limit;
                }
                {
                    kt_end = kf_limit;
                }
                if (failed) return 1;
                for (int64_t kf_step = kt_start; kf_step < kt_end; ++kf_step) {
                    {
                        int64_t kt_x = floor_div(1, 0);
                        int64_t value = kt_x;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
            }
            {
                int64_t kt_start;
                int64_t kt_end;
                {
                    kt_start = 1;
                }
                {
                    kt_end = kf_limit;
                }
                if (failed) return 1;
                for (int64_t kf_step = kt_start; kf_step < kt_end; ++kf_step) {
                    {
                        int64_t value = kf_step;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
            }
        }
        (void)kt_taken;
    }
    int64_t kf_step;
    {
        kf_step = 42;
    }
    if (failed) return 1;
    (void)kf_step;
    {
        int64_t value = kf_step;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    return 0;
}
