/* Generated by the Kofun-written Stage 1 seed compiler. */
#include <ctype.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static const char *cursor;
static bool failed;
static const char *variable_names[64];
static int64_t variable_values[64];
static size_t variable_count;

static void runtime_error(const char *message) {
    if (!failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    failed = true;
}

static void skip_space(void) {
    while (isspace((unsigned char)*cursor)) ++cursor;
}

static void set_variable(const char *name, int64_t value) {
    if (variable_count >= 64) {
        runtime_error("error[R011]: too many Core bindings");
        return;
    }
    variable_names[variable_count] = name;
    variable_values[variable_count] = value;
    ++variable_count;
}

static int64_t variable(const char *start, size_t length) {
    for (size_t index = variable_count; index > 0; --index) {
        const char *name = variable_names[index - 1];
        if (strlen(name) == length && strncmp(name, start, length) == 0) {
            return variable_values[index - 1];
        }
    }
    runtime_error("error[R011]: unknown Core binding");
    return 0;
}

static uint64_t magnitude(uint64_t limit) {
    uint64_t value = 0;
    bool any = false;
    while (isdigit((unsigned char)*cursor)) {
        uint64_t digit = (uint64_t)(*cursor++ - '0');
        any = true;
        if (value > (limit - digit) / 10) {
            runtime_error("error[R010]: integer overflow in literal");
            return 0;
        }
        value = value * 10 + digit;
    }
    if (!any) runtime_error("error[R011]: expected integer expression");
    return value;
}

static int64_t expression(void);

static int64_t primary(void) {
    skip_space();
    if (*cursor == '(') {
        ++cursor;
        int64_t value = expression();
        skip_space();
        if (*cursor != ')') runtime_error("error[R011]: expected `)`");
        else ++cursor;
        return value;
    }
    if (isalpha((unsigned char)*cursor) || *cursor == '_' || (unsigned char)*cursor >= 0x80) {
        const char *start = cursor++;
        while (isalnum((unsigned char)*cursor) || *cursor == '_' || (unsigned char)*cursor >= 0x80) ++cursor;
        return variable(start, (size_t)(cursor - start));
    }
    return (int64_t)magnitude(INT64_MAX);
}

static int64_t unary(void) {
    skip_space();
    if (*cursor == '+') {
        ++cursor;
        return unary();
    }
    if (*cursor == '-') {
        ++cursor;
        skip_space();
        if (isdigit((unsigned char)*cursor)) {
            uint64_t value = magnitude((uint64_t)INT64_MAX + 1);
            if (value == (uint64_t)INT64_MAX + 1) return INT64_MIN;
            return -(int64_t)value;
        }
        int64_t value = unary();
        if (!failed && value == INT64_MIN) {
            runtime_error("error[R010]: integer overflow in unary operator `-`");
            return 0;
        }
        return -value;
    }
    return primary();
}

static int64_t checked_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t checked_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t checked_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `//` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        runtime_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;
    return quotient;
}

static int64_t floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `%` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) return 0;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;
    return remainder;
}

static int64_t term(void) {
    int64_t value = unary();
    for (;;) {
        skip_space();
        if (*cursor == '*') {
            ++cursor;
            value = checked_mul(value, unary());
        } else if (cursor[0] == '/' && cursor[1] == '/') {
            cursor += 2;
            value = floor_div(value, unary());
        } else if (*cursor == '%') {
            ++cursor;
            value = floor_mod(value, unary());
        } else if (*cursor == '/') {
            ++cursor;
            int64_t right = unary();
            if (right == 0) runtime_error("error[R010]: operator `/` failed: division by zero");
            else if (value == INT64_MIN && right == -1) runtime_error("error[R010]: integer overflow in operator `/`");
            else value /= right;
        } else {
            return value;
        }
    }
}

static int64_t expression(void) {
    int64_t value = term();
    for (;;) {
        skip_space();
        if (*cursor == '+') {
            ++cursor;
            value = checked_add(value, term());
        } else if (*cursor == '-') {
            ++cursor;
            value = checked_sub(value, term());
        } else {
            return value;
        }
    }
}

static int64_t evaluate(const char *source) {
    cursor = source;
    int64_t value = expression();
    skip_space();
    if (*cursor != '\0') runtime_error("error[R011]: trailing input");
    return value;
}

int main(void) {
    (void)set_variable;
    set_variable("six", evaluate("2 * 3"));
    if (failed) return 1;
    set_variable("answer", evaluate("six * 7"));
    if (failed) return 1;
    {
        int64_t value = evaluate("answer");
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        int64_t value = evaluate("1 + 2 * 3");
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        int64_t value = evaluate("-7 // 2");
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        int64_t value = evaluate("-7 % 2");
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        int64_t value = evaluate("(answer - 2) / 8");
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    return 0;
}
