/* Generated by the Kofun-written Stage 1 seed compiler. */
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

static bool failed;

static void runtime_error(const char *message) {
    if (!failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    failed = true;
}

static int64_t checked_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t checked_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t checked_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t checked_neg(int64_t value) {
    if (value == INT64_MIN) {
        runtime_error("error[R010]: integer overflow in unary operator `-`");
        return 0;
    }
    return -value;
}

static int64_t floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `//` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        runtime_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;
    return quotient;
}

static int64_t floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `%` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) return 0;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;
    return remainder;
}

int main(void) {
    (void)checked_add;
    (void)checked_sub;
    (void)checked_mul;
    (void)checked_neg;
    (void)floor_div;
    (void)floor_mod;
    int64_t kf_n;
    {
        kf_n = 7;
    }
    if (failed) return 1;
    (void)kf_n;
    {
        bool kt_taken = false;
        bool kt_cond;
        {
            bool kt_x = kf_n > 5;
            kt_cond = kt_x;
        }
        if (failed) return 1;
        if (kt_cond) {
            kt_taken = true;
            int64_t kf_doubled;
            {
                int64_t kt_x = checked_mul(kf_n, 2);
                kf_doubled = kt_x;
            }
            if (failed) return 1;
            (void)kf_doubled;
            {
                int64_t value = kf_doubled;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        (void)kt_taken;
    }
    {
        bool kt_taken = false;
        bool kt_cond;
        {
            bool kt_x = kf_n > 100;
            kt_cond = kt_x;
        }
        if (failed) return 1;
        if (kt_cond) {
            kt_taken = true;
            {
                int64_t value = 0;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        if (!kt_taken) {
            int64_t kf_doubled;
            {
                int64_t kt_x = checked_add(kf_n, 1);
                kf_doubled = kt_x;
            }
            if (failed) return 1;
            (void)kf_doubled;
            {
                int64_t value = kf_doubled;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        (void)kt_taken;
    }
    {
        bool kt_taken = false;
        bool kt_cond;
        {
            bool kt_x = kf_n == 1;
            kt_cond = kt_x;
        }
        if (failed) return 1;
        if (kt_cond) {
            kt_taken = true;
            {
                int64_t value = 1;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        if (!kt_taken) {
            bool kt_x = kf_n == 7;
            kt_cond = kt_x;
            if (failed) return 1;
        } else {
            kt_cond = false;
        }
        if (kt_cond) {
            kt_taken = true;
            {
                int64_t value = 7;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        if (!kt_taken) {
            int64_t kt_xl = floor_div(1, 0);
            bool kt_x = kt_xl == 0;
            kt_cond = kt_x;
            if (failed) return 1;
        } else {
            kt_cond = false;
        }
        if (kt_cond) {
            kt_taken = true;
            {
                int64_t value = 2;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        if (!kt_taken) {
            {
                int64_t value = 3;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        (void)kt_taken;
    }
    {
        bool kt_taken = false;
        bool kt_cond;
        {
            bool kt_x = kf_n > 0;
            kt_cond = kt_x;
        }
        if (failed) return 1;
        if (kt_cond) {
            kt_taken = true;
            {
                bool kt_taken = false;
                bool kt_cond;
                {
                    bool kt_x = kf_n > 6;
                    kt_cond = kt_x;
                }
                if (failed) return 1;
                if (kt_cond) {
                    kt_taken = true;
                    int64_t kf_inner;
                    {
                        int64_t kt_x = checked_mul(kf_n, 3);
                        kf_inner = kt_x;
                    }
                    if (failed) return 1;
                    (void)kf_inner;
                    {
                        int64_t value = kf_inner;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
                if (!kt_taken) {
                    {
                        int64_t value = 4;
                        if (failed) return 1;
                        printf("%" PRId64 "\n", value);
                    }
                }
                (void)kt_taken;
            }
        }
        if (!kt_taken) {
            {
                int64_t value = 5;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        (void)kt_taken;
    }
    bool kf_outer;
    {
        bool kt_xl = kf_n > 0;
        bool kt_x = kt_xl;
        if (!failed && kt_x) {
        bool kt_xr = kf_n < 10;
            kt_x = kt_xr;
        }
        kf_outer = kt_x;
    }
    if (failed) return 1;
    (void)kf_outer;
    {
        bool kt_taken = false;
        bool kt_cond;
        {
            bool kt_x = !kf_outer;
            kt_cond = kt_x;
        }
        if (failed) return 1;
        if (kt_cond) {
            kt_taken = true;
            {
                int64_t value = 6;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        if (!kt_taken) {
            bool kt_x = kf_outer;
            if (!failed && !kt_x) {
            int64_t kt_xrl = floor_div(1, 0);
            bool kt_xr = kt_xrl == 0;
                kt_x = kt_xr;
            }
            kt_cond = kt_x;
            if (failed) return 1;
        } else {
            kt_cond = false;
        }
        if (kt_cond) {
            kt_taken = true;
            {
                int64_t value = 8;
                if (failed) return 1;
                printf("%" PRId64 "\n", value);
            }
        }
        (void)kt_taken;
    }
    {
        int64_t value = kf_n;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    return 0;
}
