/* Generated by the Kofun-written Stage 1 seed compiler. */
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static bool failed;

static void runtime_error(const char *message) {
    if (!failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    failed = true;
}

static int64_t checked_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t checked_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t checked_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        runtime_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t checked_neg(int64_t value) {
    if (value == INT64_MIN) {
        runtime_error("error[R010]: integer overflow in unary operator `-`");
        return 0;
    }
    return -value;
}

static int64_t floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `//` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        runtime_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;
    return quotient;
}

static int64_t floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        runtime_error("error[R010]: operator `%` failed: division by zero");
        return 0;
    }
    if (left == INT64_MIN && right == -1) return 0;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;
    return remainder;
}

typedef struct KofunTextAllocation {
    struct KofunTextAllocation *next;
    char bytes[];
} KofunTextAllocation;

static KofunTextAllocation *kofun_rt_text_allocations;

static void kofun_rt_text_cleanup(void) {
    while (kofun_rt_text_allocations != NULL) {
        KofunTextAllocation *allocation = kofun_rt_text_allocations;
        kofun_rt_text_allocations = allocation->next;
        free(allocation);
    }
}

static const char *kofun_rt_text_concat(const char *left, const char *right) {
    size_t left_size = strlen(left);
    size_t right_size = strlen(right);
    if (right_size == SIZE_MAX || left_size > SIZE_MAX - right_size - 1) {
        runtime_error("error[R010]: Text concatenation is too large");
        return "";
    }
    size_t payload_size = left_size + right_size + 1;
    if (payload_size > SIZE_MAX - sizeof(KofunTextAllocation)) {
        runtime_error("error[R010]: Text concatenation is too large");
        return "";
    }
    KofunTextAllocation *allocation =
        malloc(sizeof(KofunTextAllocation) + payload_size);
    if (allocation == NULL) {
        runtime_error("error[R010]: Text allocation failed");
        return "";
    }
    memcpy(allocation->bytes, left, left_size);
    memcpy(allocation->bytes + left_size, right, right_size);
    allocation->bytes[left_size + right_size] = '\0';
    allocation->next = kofun_rt_text_allocations;
    kofun_rt_text_allocations = allocation;
    return allocation->bytes;
}

static bool kofun_rt_text_equal(const char *left, const char *right) {
    return strcmp(left, right) == 0;
}

static const char *kofun_rt_text_index(const char *value, int64_t index) {
    size_t length = strlen(value);
    if (index < 0 || (uint64_t)index >= (uint64_t)length) {
        runtime_error("error[R010]: Text index out of bounds");
        return "";
    }
    char character[2] = { value[index], '\0' };
    return kofun_rt_text_concat("", character);
}

typedef struct {
    int64_t len;
    const char **items;
} KofunTextList;

typedef struct KofunTextListAllocation {
    struct KofunTextListAllocation *next;
    const char *items[];
} KofunTextListAllocation;

static KofunTextListAllocation *kofun_rt_text_list_allocations;

static void kofun_rt_text_list_cleanup(void) {
    while (kofun_rt_text_list_allocations != NULL) {
        KofunTextListAllocation *allocation =
            kofun_rt_text_list_allocations;
        kofun_rt_text_list_allocations = allocation->next;
        free(allocation);
    }
}

static KofunTextList kofun_rt_empty_text_list(void) {
    KofunTextList result = { 0, NULL };
    return result;
}

static KofunTextList kofun_rt_chars(const char *value) {
    size_t length = strlen(value);
    if ((uint64_t)length > (uint64_t)INT64_MAX ||
        length > (SIZE_MAX - sizeof(KofunTextListAllocation)) /
            (sizeof(const char *) + 2)) {
        runtime_error("error[R010]: List[Text] allocation is too large");
        return kofun_rt_empty_text_list();
    }
    KofunTextListAllocation *allocation = malloc(
        sizeof(KofunTextListAllocation) +
        length * (sizeof(const char *) + 2));
    if (allocation == NULL) {
        runtime_error("error[R010]: List[Text] allocation failed");
        return kofun_rt_empty_text_list();
    }
    allocation->next = kofun_rt_text_list_allocations;
    kofun_rt_text_list_allocations = allocation;
    char *characters = (char *)(allocation->items + length);
    for (size_t index = 0; index < length; ++index) {
        characters[2 * index] = value[index];
        characters[2 * index + 1] = '\0';
        allocation->items[index] = characters + 2 * index;
    }
    KofunTextList result = {
        (int64_t)length,
        allocation->items,
    };
    return result;
}

static int64_t kofun_rt_text_list_len(KofunTextList values) {
    return values.len;
}

static const char *kofun_rt_text_list_get(
    KofunTextList values,
    int64_t index
) {
    if (index < 0 || index >= values.len) {
        runtime_error("error[R010]: List[Text] index out of bounds");
        return "";
    }
    return values.items[index];
}

int main(void) {
    (void)checked_add;
    (void)checked_sub;
    (void)checked_mul;
    (void)checked_neg;
    (void)floor_div;
    (void)floor_mod;
    if (atexit(kofun_rt_text_cleanup) != 0) {
        runtime_error("error[R010]: Text cleanup registration failed");
        return 1;
    }
    (void)kofun_rt_text_concat;
    (void)kofun_rt_text_equal;
    (void)kofun_rt_text_index;
    if (atexit(kofun_rt_text_list_cleanup) != 0) {
        runtime_error("error[R010]: List[Text] cleanup registration failed");
        return 1;
    }
    (void)kofun_rt_chars;
    (void)kofun_rt_text_list_len;
    (void)kofun_rt_text_list_get;
    const char * kf_word;
    {
        kf_word = "k字n";
    }
    if (failed) return 1;
    (void)kf_word;
    KofunTextList kf_symbols;
    {
        KofunTextList kt_x = kofun_rt_chars(kf_word);
        kf_symbols = kt_x;
    }
    if (failed) return 1;
    (void)kf_symbols;
    const char * kf_first;
    {
        const char * kt_x = kofun_rt_text_list_get(kf_symbols, 0);
        kf_first = kt_x;
    }
    if (failed) return 1;
    (void)kf_first;
    const char * kf_last;
    {
        int64_t kt_xil = kofun_rt_text_list_len(kf_symbols);
        int64_t kt_xi = checked_sub(kt_xil, 1);
        const char * kt_x = kofun_rt_text_list_get(kf_symbols, kt_xi);
        kf_last = kt_x;
    }
    if (failed) return 1;
    (void)kf_last;
    {
        const char * kt_x = kofun_rt_text_concat(kf_first, kf_last);
        const char * value = kt_x;
        if (failed) return 1;
        fputs(value, stdout);
        fputc('\n', stdout);
    }
    {
        int64_t kt_x = kofun_rt_text_list_len(kf_symbols);
        int64_t value = kt_x;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    {
        const char * kt_x = kofun_rt_text_index("abc", 1);
        const char * value = kt_x;
        if (failed) return 1;
        fputs(value, stdout);
        fputc('\n', stdout);
    }
    {
        bool kt_taken = false;
        bool kt_cond;
        {
            KofunTextList kt_xln = kofun_rt_chars("k字n");
            int64_t kt_xl = kofun_rt_text_list_len(kt_xln);
            bool kt_x = kt_xl == 5;
            kt_cond = kt_x;
        }
        if (failed) return 1;
        if (kt_cond) {
            kt_taken = true;
            {
                const char * value = "utf8-bytes";
                if (failed) return 1;
                fputs(value, stdout);
                fputc('\n', stdout);
            }
        }
        (void)kt_taken;
    }
    {
        int64_t value = 42;
        if (failed) return 1;
        printf("%" PRId64 "\n", value);
    }
    return 0;
}
