/* Generated by kofun-stage2 --lower-selfhost-c11. */
/* Source: bootstrap/stage1/compiler.kofun 40e00b91afc5303ed24e1bea74baeca4ed4a346f5022526a67233d984761c5ee */

#include <ctype.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "kofun_unicode.c"

typedef struct {
    int64_t len;
    const char **items;
} kofun_text_list;

int kofun_runtime_argc = 0;
char **kofun_runtime_argv = NULL;

static bool kofun_failed;

static void kofun_error(const char *message) {
    if (!kofun_failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    kofun_failed = true;
}

static int64_t kofun_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t kofun_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t kofun_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t kofun_neg(int64_t value) {
    if (value == INT64_MIN) {
        kofun_error(
            "error[R010]: integer overflow in unary operator `-`"
        );
        return 0;
    }
    return -value;
}

static int64_t kofun_floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        kofun_error(
            "error[R010]: operator `//` failed: division by zero"
        );
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        kofun_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) {
        --quotient;
    }
    return quotient;
}

static int64_t kofun_floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        kofun_error(
            "error[R010]: operator `%` failed: division by zero"
        );
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        return 0;
    }
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) {
        remainder += right;
    }
    return remainder;
}

void kofun_rt_panic(const char *message) {
    fprintf(stderr, "Kofun runtime error: %s\n", message);
    exit(1);
}

void *kofun_rt_alloc(size_t size) {
    void *value = malloc(size == 0 ? 1 : size);
    if (value == NULL) {
        kofun_rt_panic("out of memory");
    }
    return value;
}

char *kofun_rt_copy_n(const char *value, size_t length) {
    char *result = (char *)kofun_rt_alloc(length + 1);
    if (length > 0) {
        memcpy(result, value, length);
    }
    result[length] = '\0';
    return result;
}

char *kofun_rt_text_concat(const char *left, const char *right) {
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    char *result = (char *)kofun_rt_alloc(left_len + right_len + 1);
    memcpy(result, left, left_len);
    memcpy(result + left_len, right, right_len + 1);
    return result;
}

bool kofun_rt_text_equal(const char *left, const char *right) {
    return strcmp(left, right) == 0;
}

int64_t kofun_rt_text_len(const char *value) {
    return (int64_t)strlen(value);
}

int64_t kofun_rt_text_list_len(kofun_text_list values) {
    return values.len;
}

kofun_text_list kofun_rt_args(void) {
    kofun_text_list result;
    result.len = (int64_t)kofun_runtime_argc;
    result.items = (const char **)kofun_runtime_argv;
    return result;
}

kofun_text_list kofun_rt_chars(const char *value) {
    size_t length = strlen(value);
    const char **items = (const char **)kofun_rt_alloc(
        sizeof(char *) * (length == 0 ? 1 : length)
    );
    for (size_t index = 0; index < length; ++index) {
        items[index] = kofun_rt_copy_n(value + index, 1);
    }
    kofun_text_list result;
    result.len = (int64_t)length;
    result.items = items;
    return result;
}

const char *kofun_rt_text_list_get(kofun_text_list values, int64_t index) {
    if (index < 0 || index >= values.len) {
        kofun_rt_panic("List[Text] index out of bounds");
    }
    return values.items[index];
}

bool kofun_rt_text_contains(const char *value, const char *needle) {
    return strstr(value, needle) != NULL;
}

int64_t kofun_rt_find(const char *value, const char *needle) {
    const char *found = strstr(value, needle);
    return found == NULL ? INT64_C(-1) : (int64_t)(found - value);
}

char *kofun_rt_text_slice(const char *value, int64_t start, int64_t end) {
    int64_t length = (int64_t)strlen(value);
    if (start < 0) start = 0;
    if (end < start) end = start;
    if (start > length) start = length;
    if (end > length) end = length;
    return kofun_rt_copy_n(value + start, (size_t)(end - start));
}

char *kofun_rt_trim(const char *value) {
    const unsigned char *start = (const unsigned char *)value;
    while (*start != '\0' && isspace(*start)) {
        ++start;
    }
    const unsigned char *end =
        (const unsigned char *)value + strlen(value);
    while (end > start && isspace(end[-1])) {
        --end;
    }
    return kofun_rt_copy_n((const char *)start, (size_t)(end - start));
}

char *kofun_rt_replace(
    const char *value,
    const char *old,
    const char *replacement
) {
    size_t old_len = strlen(old);
    if (old_len == 0) {
        return kofun_rt_copy_n(value, strlen(value));
    }
    size_t replacement_len = strlen(replacement);
    size_t count = 0;
    const char *cursor = value;
    while ((cursor = strstr(cursor, old)) != NULL) {
        ++count;
        cursor += old_len;
    }
    size_t value_len = strlen(value);
    size_t result_len;
    if (replacement_len >= old_len) {
        result_len = value_len + count * (replacement_len - old_len);
    } else {
        result_len = value_len - count * (old_len - replacement_len);
    }
    char *result = (char *)kofun_rt_alloc(result_len + 1);
    char *out = result;
    cursor = value;
    const char *match;
    while ((match = strstr(cursor, old)) != NULL) {
        size_t prefix = (size_t)(match - cursor);
        memcpy(out, cursor, prefix);
        out += prefix;
        memcpy(out, replacement, replacement_len);
        out += replacement_len;
        cursor = match + old_len;
    }
    strcpy(out, cursor);
    return result;
}

bool kofun_rt_starts_with(const char *value, const char *prefix) {
    size_t prefix_len = strlen(prefix);
    return strncmp(value, prefix, prefix_len) == 0;
}

bool kofun_rt_is_digit(const char *value) {
    return value[0] != '\0' && value[1] == '\0' &&
        isdigit((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_space(const char *value) {
    return value[0] != '\0' && value[1] == '\0' &&
        isspace((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_xid_continue(const char *value) {
    uint32_t codepoint = 0;
    size_t width = 0;
    size_t length = strlen(value);
    if (!kofun_unicode_decode(
            (const uint8_t *)value,
            length,
            0,
            &codepoint,
            &width)) {
        return false;
    }
    return kofun_unicode_is_xid_continue(codepoint);
}

const char *kofun_rt_validate_unicode_source(const char *value) {
    KofunUnicodeError unicode_error;
    if (kofun_unicode_validate_source(
            (const uint8_t *)value,
            strlen(value),
            &unicode_error)) {
        return "";
    }
    char message[1024];
    kofun_unicode_format_error(
        &unicode_error,
        getenv("KOFUN_DIAGNOSTIC_LOCALE"),
        message,
        sizeof(message)
    );
    return kofun_rt_copy_n(message, strlen(message));
}

char *kofun_rt_read_text(const char *path) {
    FILE *file = fopen(path, "rb");
    if (file == NULL) {
        kofun_rt_panic("cannot open input file");
    }
    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        kofun_rt_panic("cannot seek input file");
    }
    long size = ftell(file);
    if (size < 0) {
        fclose(file);
        kofun_rt_panic("cannot measure input file");
    }
    rewind(file);
    char *result = (char *)kofun_rt_alloc((size_t)size + 1);
    size_t read = fread(result, 1, (size_t)size, file);
    if (read != (size_t)size && ferror(file)) {
        fclose(file);
        kofun_rt_panic("cannot read input file");
    }
    result[read] = '\0';
    fclose(file);
    return result;
}

void kofun_rt_write_text(const char *path, const char *value) {
    FILE *file = fopen(path, "wb");
    if (file == NULL) {
        kofun_rt_panic("cannot open output file");
    }
    size_t length = strlen(value);
    if (fwrite(value, 1, length, file) != length) {
        fclose(file);
        kofun_rt_panic("cannot write output file");
    }
    if (fclose(file) != 0) {
        kofun_rt_panic("cannot close output file");
    }
}

static bool kofun_fn_identifier_char(const char *k_b11);
static bool kofun_fn_valid_name(const char *k_b12);
static bool kofun_fn_valid_expression(const char *k_b15);
static const char *kofun_fn_print_expression(const char *k_b20);
static const char *kofun_fn_binding_name(const char *k_b28);
static const char *kofun_fn_binding_expression(const char *k_b32);
static bool kofun_fn_valid_source(const char *k_b34);
static const char *kofun_fn_emit_statements(const char *k_b43);
static const char *kofun_fn_emit_c(const char *k_b52);
static bool kofun_fn_compile_file(const char *k_b53, const char *k_b54);

static bool kofun_fn_identifier_char(const char *k_b11) {
    const char * k_n4 = k_b11;
    bool k_n3 = kofun_rt_is_xid_continue(k_n4);
    bool k_n2 = k_n3;
    if (!k_n2) {
        const char *k_n6 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_";
        const char * k_n7 = k_b11;
        bool k_n5 = kofun_rt_text_contains(k_n6, k_n7);
        k_n2 = k_n5;
    }
    return k_n2;
}

static bool kofun_fn_valid_name(const char *k_b12) {
    const char * k_n11 = k_b12;
    kofun_text_list k_n10 = kofun_rt_chars(k_n11);
    kofun_text_list k_b13 = k_n10;
    kofun_text_list k_n16 = k_b13;
    int64_t k_n15 = kofun_rt_text_list_len(k_n16);
    int64_t k_n17 = INT64_C(0);
    bool k_n14 = k_n15 == k_n17;
    bool k_n13 = k_n14;
    if (!k_n13) {
        kofun_text_list k_n20 = k_b13;
        int64_t k_n21 = INT64_C(0);
        const char *k_n19 = kofun_rt_text_list_get(k_n20, k_n21);
        bool k_n18 = kofun_rt_is_digit(k_n19);
        k_n13 = k_n18;
    }
    if (k_n13) {
        bool k_n23 = false;
        return k_n23;
    }
    int64_t k_n26 = INT64_C(0);
    kofun_text_list k_n28 = k_b13;
    int64_t k_n27 = kofun_rt_text_list_len(k_n28);
    for (int64_t k_b14 = k_n26; k_b14 < k_n27; ++k_b14) {
        kofun_text_list k_n33 = k_b13;
        int64_t k_n34 = k_b14;
        const char *k_n32 = kofun_rt_text_list_get(k_n33, k_n34);
        bool k_n31 = kofun_fn_identifier_char(k_n32);
        if (kofun_failed) return false;
        bool k_n30 = !k_n31;
        if (k_n30) {
            bool k_n36 = false;
            return k_n36;
        }
    }
    bool k_n38 = true;
    return k_n38;
}

static bool kofun_fn_valid_expression(const char *k_b15) {
    const char * k_n42 = k_b15;
    kofun_text_list k_n41 = kofun_rt_chars(k_n42);
    kofun_text_list k_b16 = k_n41;
    kofun_text_list k_n46 = k_b16;
    int64_t k_n45 = kofun_rt_text_list_len(k_n46);
    int64_t k_n47 = INT64_C(0);
    bool k_n44 = k_n45 == k_n47;
    if (k_n44) {
        bool k_n49 = false;
        return k_n49;
    }
    int64_t k_n51 = INT64_C(0);
    int64_t k_b17 = k_n51;
    int64_t k_n54 = INT64_C(0);
    kofun_text_list k_n56 = k_b16;
    int64_t k_n55 = kofun_rt_text_list_len(k_n56);
    for (int64_t k_b18 = k_n54; k_b18 < k_n55; ++k_b18) {
        kofun_text_list k_n59 = k_b16;
        int64_t k_n60 = k_b18;
        const char *k_n58 = kofun_rt_text_list_get(k_n59, k_n60);
        const char * k_b19 = k_n58;
        const char * k_n66 = k_b19;
        bool k_n65 = kofun_fn_identifier_char(k_n66);
        if (kofun_failed) return false;
        bool k_n64 = k_n65;
        if (!k_n64) {
            const char * k_n68 = k_b19;
            bool k_n67 = kofun_rt_is_space(k_n68);
            k_n64 = k_n67;
        }
        bool k_n63 = k_n64;
        if (!k_n63) {
            const char *k_n70 = "+-*/%()";
            const char * k_n71 = k_b19;
            bool k_n69 = kofun_rt_text_contains(k_n70, k_n71);
            k_n63 = k_n69;
        }
        bool k_n62 = !k_n63;
        if (k_n62) {
            bool k_n73 = false;
            return k_n73;
        }
        const char * k_n76 = k_b19;
        const char *k_n77 = "(";
        bool k_n75 = kofun_rt_text_equal(k_n76, k_n77);
        if (k_n75) {
            int64_t k_n80 = k_b17;
            int64_t k_n81 = INT64_C(1);
            int64_t k_n79 = kofun_add(k_n80, k_n81);
            if (kofun_failed) return false;
            k_b17 = k_n79;
        } else {
            const char * k_n84 = k_b19;
            const char *k_n85 = ")";
            bool k_n83 = kofun_rt_text_equal(k_n84, k_n85);
            if (k_n83) {
                int64_t k_n88 = k_b17;
                int64_t k_n89 = INT64_C(1);
                int64_t k_n87 = kofun_sub(k_n88, k_n89);
                if (kofun_failed) return false;
                k_b17 = k_n87;
                int64_t k_n92 = k_b17;
                int64_t k_n93 = INT64_C(0);
                bool k_n91 = k_n92 < k_n93;
                if (k_n91) {
                    bool k_n95 = false;
                    return k_n95;
                }
            }
        }
    }
    int64_t k_n98 = k_b17;
    int64_t k_n99 = INT64_C(0);
    bool k_n97 = k_n98 == k_n99;
    return k_n97;
}

static const char *kofun_fn_print_expression(const char *k_b20) {
    const char *k_n102 = "print(";
    const char * k_b21 = k_n102;
    const char * k_n105 = k_b20;
    const char * k_n106 = k_b21;
    int64_t k_n104 = kofun_rt_find(k_n105, k_n106);
    int64_t k_b22 = k_n104;
    int64_t k_n109 = k_b22;
    int64_t k_n110 = INT64_C(0);
    bool k_n108 = k_n109 < k_n110;
    if (k_n108) {
        const char *k_n112 = "";
        return k_n112;
    }
    int64_t k_n115 = k_b22;
    const char * k_n117 = k_b21;
    int64_t k_n116 = kofun_rt_text_len(k_n117);
    int64_t k_n114 = kofun_add(k_n115, k_n116);
    if (kofun_failed) return "";
    int64_t k_b23 = k_n114;
    const char * k_n120 = k_b20;
    kofun_text_list k_n119 = kofun_rt_chars(k_n120);
    kofun_text_list k_b24 = k_n119;
    int64_t k_n122 = INT64_C(1);
    int64_t k_b25 = k_n122;
    int64_t k_n124 = k_b23;
    int64_t k_b26 = k_n124;
    for (;;) {
        int64_t k_n127 = k_b26;
        kofun_text_list k_n129 = k_b24;
        int64_t k_n128 = kofun_rt_text_list_len(k_n129);
        bool k_n126 = k_n127 < k_n128;
        if (!k_n126) break;
        kofun_text_list k_n132 = k_b24;
        int64_t k_n133 = k_b26;
        const char *k_n131 = kofun_rt_text_list_get(k_n132, k_n133);
        const char * k_b27 = k_n131;
        const char * k_n136 = k_b27;
        const char *k_n137 = "(";
        bool k_n135 = kofun_rt_text_equal(k_n136, k_n137);
        if (k_n135) {
            int64_t k_n140 = k_b25;
            int64_t k_n141 = INT64_C(1);
            int64_t k_n139 = kofun_add(k_n140, k_n141);
            if (kofun_failed) return "";
            k_b25 = k_n139;
        } else {
            const char * k_n144 = k_b27;
            const char *k_n145 = ")";
            bool k_n143 = kofun_rt_text_equal(k_n144, k_n145);
            if (k_n143) {
                int64_t k_n148 = k_b25;
                int64_t k_n149 = INT64_C(1);
                int64_t k_n147 = kofun_sub(k_n148, k_n149);
                if (kofun_failed) return "";
                k_b25 = k_n147;
                int64_t k_n152 = k_b25;
                int64_t k_n153 = INT64_C(0);
                bool k_n151 = k_n152 == k_n153;
                if (k_n151) {
                    const char * k_n157 = k_b20;
                    int64_t k_n158 = k_b23;
                    int64_t k_n159 = k_b26;
                    const char * k_n156 = kofun_rt_text_slice(k_n157, k_n158, k_n159);
                    const char * k_n155 = kofun_rt_trim(k_n156);
                    return k_n155;
                }
            }
        }
        int64_t k_n162 = k_b26;
        int64_t k_n163 = INT64_C(1);
        int64_t k_n161 = kofun_add(k_n162, k_n163);
        if (kofun_failed) return "";
        k_b26 = k_n161;
    }
    const char *k_n165 = "";
    return k_n165;
}

static const char *kofun_fn_binding_name(const char *k_b28) {
    const char * k_n169 = k_b28;
    const char *k_n170 = "=";
    int64_t k_n168 = kofun_rt_find(k_n169, k_n170);
    int64_t k_b29 = k_n168;
    int64_t k_n173 = k_b29;
    int64_t k_n174 = INT64_C(0);
    bool k_n172 = k_n173 < k_n174;
    if (k_n172) {
        const char *k_n176 = "";
        return k_n176;
    }
    const char * k_n180 = k_b28;
    int64_t k_n181 = INT64_C(4);
    int64_t k_n182 = k_b29;
    const char * k_n179 = kofun_rt_text_slice(k_n180, k_n181, k_n182);
    const char * k_n178 = kofun_rt_trim(k_n179);
    const char * k_b30 = k_n178;
    const char * k_n185 = k_b30;
    const char *k_n186 = ":";
    int64_t k_n184 = kofun_rt_find(k_n185, k_n186);
    int64_t k_b31 = k_n184;
    int64_t k_n189 = k_b31;
    int64_t k_n190 = INT64_C(0);
    bool k_n188 = k_n189 >= k_n190;
    if (k_n188) {
        const char * k_n194 = k_b30;
        int64_t k_n195 = INT64_C(0);
        int64_t k_n196 = k_b31;
        const char * k_n193 = kofun_rt_text_slice(k_n194, k_n195, k_n196);
        const char * k_n192 = kofun_rt_trim(k_n193);
        return k_n192;
    }
    const char * k_n198 = k_b30;
    return k_n198;
}

static const char *kofun_fn_binding_expression(const char *k_b32) {
    const char * k_n202 = k_b32;
    const char *k_n203 = "=";
    int64_t k_n201 = kofun_rt_find(k_n202, k_n203);
    int64_t k_b33 = k_n201;
    int64_t k_n206 = k_b33;
    int64_t k_n207 = INT64_C(0);
    bool k_n205 = k_n206 < k_n207;
    if (k_n205) {
        const char *k_n209 = "";
        return k_n209;
    }
    const char * k_n213 = k_b32;
    int64_t k_n215 = k_b33;
    int64_t k_n216 = INT64_C(1);
    int64_t k_n214 = kofun_add(k_n215, k_n216);
    if (kofun_failed) return "";
    const char * k_n218 = k_b32;
    int64_t k_n217 = kofun_rt_text_len(k_n218);
    const char * k_n212 = kofun_rt_text_slice(k_n213, k_n214, k_n217);
    const char * k_n211 = kofun_rt_trim(k_n212);
    return k_n211;
}

static bool kofun_fn_valid_source(const char *k_b34) {
    const char * k_n222 = k_b34;
    kofun_text_list k_n221 = kofun_rt_chars(k_n222);
    kofun_text_list k_b35 = k_n221;
    int64_t k_n224 = INT64_C(0);
    int64_t k_b36 = k_n224;
    int64_t k_n226 = INT64_C(0);
    int64_t k_b37 = k_n226;
    int64_t k_n228 = INT64_C(0);
    int64_t k_b38 = k_n228;
    int64_t k_n230 = INT64_C(0);
    int64_t k_b39 = k_n230;
    int64_t k_n233 = INT64_C(0);
    kofun_text_list k_n235 = k_b35;
    int64_t k_n234 = kofun_rt_text_list_len(k_n235);
    for (int64_t k_b40 = k_n233; k_b40 < k_n234; ++k_b40) {
        kofun_text_list k_n239 = k_b35;
        int64_t k_n240 = k_b40;
        const char *k_n238 = kofun_rt_text_list_get(k_n239, k_n240);
        const char *k_n241 = "\n";
        bool k_n237 = kofun_rt_text_equal(k_n238, k_n241);
        if (k_n237) {
            const char * k_n245 = k_b34;
            int64_t k_n246 = k_b36;
            int64_t k_n247 = k_b40;
            const char * k_n244 = kofun_rt_text_slice(k_n245, k_n246, k_n247);
            const char * k_n243 = kofun_rt_trim(k_n244);
            const char * k_b41 = k_n243;
            const char * k_n252 = k_b41;
            int64_t k_n251 = kofun_rt_text_len(k_n252);
            int64_t k_n253 = INT64_C(0);
            bool k_n250 = k_n251 == k_n253;
            bool k_n249 = k_n250;
            if (!k_n249) {
                const char * k_n255 = k_b41;
                const char *k_n256 = "#";
                bool k_n254 = kofun_rt_starts_with(k_n255, k_n256);
                k_n249 = k_n254;
            }
            if (k_n249) {
            } else {
                const char * k_n259 = k_b41;
                const char *k_n260 = "fn main() {";
                bool k_n258 = kofun_rt_text_equal(k_n259, k_n260);
                if (k_n258) {
                    int64_t k_n264 = k_b38;
                    int64_t k_n265 = INT64_C(0);
                    bool k_n263 = k_n264 != k_n265;
                    bool k_n262 = k_n263;
                    if (!k_n262) {
                        int64_t k_n267 = k_b39;
                        int64_t k_n268 = INT64_C(0);
                        bool k_n266 = k_n267 != k_n268;
                        k_n262 = k_n266;
                    }
                    if (k_n262) {
                        bool k_n270 = false;
                        return k_n270;
                    }
                    int64_t k_n273 = k_b38;
                    int64_t k_n274 = INT64_C(1);
                    int64_t k_n272 = kofun_add(k_n273, k_n274);
                    if (kofun_failed) return false;
                    k_b38 = k_n272;
                    int64_t k_n276 = INT64_C(1);
                    k_b39 = k_n276;
                } else {
                    const char * k_n279 = k_b41;
                    const char *k_n280 = "}";
                    bool k_n278 = kofun_rt_text_equal(k_n279, k_n280);
                    if (k_n278) {
                        int64_t k_n283 = k_b39;
                        int64_t k_n284 = INT64_C(1);
                        bool k_n282 = k_n283 != k_n284;
                        if (k_n282) {
                            bool k_n286 = false;
                            return k_n286;
                        }
                        int64_t k_n288 = INT64_C(0);
                        k_b39 = k_n288;
                    } else {
                        const char * k_n291 = k_b41;
                        const char *k_n292 = "let ";
                        bool k_n290 = kofun_rt_starts_with(k_n291, k_n292);
                        if (k_n290) {
                            int64_t k_n295 = k_b39;
                            int64_t k_n296 = INT64_C(1);
                            bool k_n294 = k_n295 != k_n296;
                            if (k_n294) {
                                bool k_n298 = false;
                                return k_n298;
                            }
                            const char * k_n304 = k_b41;
                            const char * k_n303 = kofun_fn_binding_name(k_n304);
                            if (kofun_failed) return false;
                            bool k_n302 = kofun_fn_valid_name(k_n303);
                            if (kofun_failed) return false;
                            bool k_n301 = !k_n302;
                            bool k_n300 = k_n301;
                            if (!k_n300) {
                                const char * k_n308 = k_b41;
                                const char * k_n307 = kofun_fn_binding_expression(k_n308);
                                if (kofun_failed) return false;
                                bool k_n306 = kofun_fn_valid_expression(k_n307);
                                if (kofun_failed) return false;
                                bool k_n305 = !k_n306;
                                k_n300 = k_n305;
                            }
                            if (k_n300) {
                                bool k_n310 = false;
                                return k_n310;
                            }
                        } else {
                            const char * k_n313 = k_b41;
                            const char *k_n314 = "print(";
                            bool k_n312 = kofun_rt_starts_with(k_n313, k_n314);
                            if (k_n312) {
                                int64_t k_n317 = k_b39;
                                int64_t k_n318 = INT64_C(1);
                                bool k_n316 = k_n317 != k_n318;
                                if (k_n316) {
                                    bool k_n320 = false;
                                    return k_n320;
                                }
                                const char * k_n323 = k_b41;
                                const char * k_n322 = kofun_fn_print_expression(k_n323);
                                if (kofun_failed) return false;
                                const char * k_b42 = k_n322;
                                const char * k_n327 = k_b42;
                                bool k_n326 = kofun_fn_valid_expression(k_n327);
                                if (kofun_failed) return false;
                                bool k_n325 = !k_n326;
                                if (k_n325) {
                                    bool k_n329 = false;
                                    return k_n329;
                                }
                                int64_t k_n332 = k_b37;
                                int64_t k_n333 = INT64_C(1);
                                int64_t k_n331 = kofun_add(k_n332, k_n333);
                                if (kofun_failed) return false;
                                k_b37 = k_n331;
                            } else {
                                bool k_n335 = false;
                                return k_n335;
                            }
                        }
                    }
                }
            }
            int64_t k_n338 = k_b40;
            int64_t k_n339 = INT64_C(1);
            int64_t k_n337 = kofun_add(k_n338, k_n339);
            if (kofun_failed) return false;
            k_b36 = k_n337;
        }
    }
    int64_t k_n344 = k_b38;
    int64_t k_n345 = INT64_C(1);
    bool k_n343 = k_n344 == k_n345;
    bool k_n342 = k_n343;
    if (k_n342) {
        int64_t k_n347 = k_b39;
        int64_t k_n348 = INT64_C(0);
        bool k_n346 = k_n347 == k_n348;
        k_n342 = k_n346;
    }
    bool k_n341 = k_n342;
    if (k_n341) {
        int64_t k_n350 = k_b37;
        int64_t k_n351 = INT64_C(0);
        bool k_n349 = k_n350 > k_n351;
        k_n341 = k_n349;
    }
    return k_n341;
}

static const char *kofun_fn_emit_statements(const char *k_b43) {
    const char * k_n355 = k_b43;
    kofun_text_list k_n354 = kofun_rt_chars(k_n355);
    kofun_text_list k_b44 = k_n354;
    int64_t k_n357 = INT64_C(0);
    int64_t k_b45 = k_n357;
    const char *k_n359 = "";
    const char * k_b46 = k_n359;
    int64_t k_n362 = INT64_C(0);
    kofun_text_list k_n364 = k_b44;
    int64_t k_n363 = kofun_rt_text_list_len(k_n364);
    for (int64_t k_b47 = k_n362; k_b47 < k_n363; ++k_b47) {
        kofun_text_list k_n368 = k_b44;
        int64_t k_n369 = k_b47;
        const char *k_n367 = kofun_rt_text_list_get(k_n368, k_n369);
        const char *k_n370 = "\n";
        bool k_n366 = kofun_rt_text_equal(k_n367, k_n370);
        if (k_n366) {
            const char * k_n374 = k_b43;
            int64_t k_n375 = k_b45;
            int64_t k_n376 = k_b47;
            const char * k_n373 = kofun_rt_text_slice(k_n374, k_n375, k_n376);
            const char * k_n372 = kofun_rt_trim(k_n373);
            const char * k_b48 = k_n372;
            const char * k_n379 = k_b48;
            const char *k_n380 = "let ";
            bool k_n378 = kofun_rt_starts_with(k_n379, k_n380);
            if (k_n378) {
                const char * k_n383 = k_b48;
                const char * k_n382 = kofun_fn_binding_name(k_n383);
                if (kofun_failed) return "";
                const char * k_b49 = k_n382;
                const char * k_n386 = k_b48;
                const char * k_n385 = kofun_fn_binding_expression(k_n386);
                if (kofun_failed) return "";
                const char * k_b50 = k_n385;
                const char * k_n394 = k_b46;
                const char *k_n395 = "    set_variable(\"";
                const char *k_n393 = kofun_rt_text_concat(k_n394, k_n395);
                const char * k_n396 = k_b49;
                const char *k_n392 = kofun_rt_text_concat(k_n393, k_n396);
                const char *k_n397 = "\", evaluate(\"";
                const char *k_n391 = kofun_rt_text_concat(k_n392, k_n397);
                const char * k_n398 = k_b50;
                const char *k_n390 = kofun_rt_text_concat(k_n391, k_n398);
                const char *k_n399 = "\"));\n";
                const char *k_n389 = kofun_rt_text_concat(k_n390, k_n399);
                const char *k_n400 = "    if (failed) return 1;\n";
                const char *k_n388 = kofun_rt_text_concat(k_n389, k_n400);
                k_b46 = k_n388;
            } else {
                const char * k_n403 = k_b48;
                const char *k_n404 = "print(";
                bool k_n402 = kofun_rt_starts_with(k_n403, k_n404);
                if (k_n402) {
                    const char * k_n407 = k_b48;
                    const char * k_n406 = kofun_fn_print_expression(k_n407);
                    if (kofun_failed) return "";
                    const char * k_b51 = k_n406;
                    const char * k_n416 = k_b46;
                    const char *k_n417 = "    {\n";
                    const char *k_n415 = kofun_rt_text_concat(k_n416, k_n417);
                    const char *k_n418 = "        int64_t value = evaluate(\"";
                    const char *k_n414 = kofun_rt_text_concat(k_n415, k_n418);
                    const char * k_n419 = k_b51;
                    const char *k_n413 = kofun_rt_text_concat(k_n414, k_n419);
                    const char *k_n420 = "\");\n";
                    const char *k_n412 = kofun_rt_text_concat(k_n413, k_n420);
                    const char *k_n421 = "        if (failed) return 1;\n";
                    const char *k_n411 = kofun_rt_text_concat(k_n412, k_n421);
                    const char *k_n422 = "        printf(\"%\" PRId64 \"\\n\", value);\n";
                    const char *k_n410 = kofun_rt_text_concat(k_n411, k_n422);
                    const char *k_n423 = "    }\n";
                    const char *k_n409 = kofun_rt_text_concat(k_n410, k_n423);
                    k_b46 = k_n409;
                }
            }
            int64_t k_n426 = k_b47;
            int64_t k_n427 = INT64_C(1);
            int64_t k_n425 = kofun_add(k_n426, k_n427);
            if (kofun_failed) return "";
            k_b45 = k_n425;
        }
    }
    const char * k_n429 = k_b46;
    return k_n429;
}

static const char *kofun_fn_emit_c(const char *k_b52) {
    const char *k_n628 = "/* Generated by the Kofun-written Stage 1 seed compiler. */\n";
    const char *k_n629 = "#include <ctype.h>\n";
    const char *k_n627 = kofun_rt_text_concat(k_n628, k_n629);
    const char *k_n630 = "#include <inttypes.h>\n";
    const char *k_n626 = kofun_rt_text_concat(k_n627, k_n630);
    const char *k_n631 = "#include <stdbool.h>\n";
    const char *k_n625 = kofun_rt_text_concat(k_n626, k_n631);
    const char *k_n632 = "#include <stddef.h>\n";
    const char *k_n624 = kofun_rt_text_concat(k_n625, k_n632);
    const char *k_n633 = "#include <stdint.h>\n";
    const char *k_n623 = kofun_rt_text_concat(k_n624, k_n633);
    const char *k_n634 = "#include <stdio.h>\n";
    const char *k_n622 = kofun_rt_text_concat(k_n623, k_n634);
    const char *k_n635 = "#include <string.h>\n\n";
    const char *k_n621 = kofun_rt_text_concat(k_n622, k_n635);
    const char *k_n636 = "static const char *cursor;\n";
    const char *k_n620 = kofun_rt_text_concat(k_n621, k_n636);
    const char *k_n637 = "static bool failed;\n";
    const char *k_n619 = kofun_rt_text_concat(k_n620, k_n637);
    const char *k_n638 = "static const char *variable_names[64];\n";
    const char *k_n618 = kofun_rt_text_concat(k_n619, k_n638);
    const char *k_n639 = "static int64_t variable_values[64];\n";
    const char *k_n617 = kofun_rt_text_concat(k_n618, k_n639);
    const char *k_n640 = "static size_t variable_count;\n\n";
    const char *k_n616 = kofun_rt_text_concat(k_n617, k_n640);
    const char *k_n641 = "static void runtime_error(const char *message) {\n";
    const char *k_n615 = kofun_rt_text_concat(k_n616, k_n641);
    const char *k_n642 = "    if (!failed) {\n";
    const char *k_n614 = kofun_rt_text_concat(k_n615, k_n642);
    const char *k_n643 = "        fputs(message, stderr);\n";
    const char *k_n613 = kofun_rt_text_concat(k_n614, k_n643);
    const char *k_n644 = "        fputc('\\n', stderr);\n";
    const char *k_n612 = kofun_rt_text_concat(k_n613, k_n644);
    const char *k_n645 = "    }\n";
    const char *k_n611 = kofun_rt_text_concat(k_n612, k_n645);
    const char *k_n646 = "    failed = true;\n";
    const char *k_n610 = kofun_rt_text_concat(k_n611, k_n646);
    const char *k_n647 = "}\n\n";
    const char *k_n609 = kofun_rt_text_concat(k_n610, k_n647);
    const char *k_n648 = "static void skip_space(void) {\n";
    const char *k_n608 = kofun_rt_text_concat(k_n609, k_n648);
    const char *k_n649 = "    while (isspace((unsigned char)*cursor)) ++cursor;\n";
    const char *k_n607 = kofun_rt_text_concat(k_n608, k_n649);
    const char *k_n650 = "}\n\n";
    const char *k_n606 = kofun_rt_text_concat(k_n607, k_n650);
    const char *k_n651 = "static void set_variable(const char *name, int64_t value) {\n";
    const char *k_n605 = kofun_rt_text_concat(k_n606, k_n651);
    const char *k_n652 = "    if (variable_count >= 64) {\n";
    const char *k_n604 = kofun_rt_text_concat(k_n605, k_n652);
    const char *k_n653 = "        runtime_error(\"error[R011]: too many Core bindings\");\n";
    const char *k_n603 = kofun_rt_text_concat(k_n604, k_n653);
    const char *k_n654 = "        return;\n";
    const char *k_n602 = kofun_rt_text_concat(k_n603, k_n654);
    const char *k_n655 = "    }\n";
    const char *k_n601 = kofun_rt_text_concat(k_n602, k_n655);
    const char *k_n656 = "    variable_names[variable_count] = name;\n";
    const char *k_n600 = kofun_rt_text_concat(k_n601, k_n656);
    const char *k_n657 = "    variable_values[variable_count] = value;\n";
    const char *k_n599 = kofun_rt_text_concat(k_n600, k_n657);
    const char *k_n658 = "    ++variable_count;\n";
    const char *k_n598 = kofun_rt_text_concat(k_n599, k_n658);
    const char *k_n659 = "}\n\n";
    const char *k_n597 = kofun_rt_text_concat(k_n598, k_n659);
    const char *k_n660 = "static int64_t variable(const char *start, size_t length) {\n";
    const char *k_n596 = kofun_rt_text_concat(k_n597, k_n660);
    const char *k_n661 = "    for (size_t index = variable_count; index > 0; --index) {\n";
    const char *k_n595 = kofun_rt_text_concat(k_n596, k_n661);
    const char *k_n662 = "        const char *name = variable_names[index - 1];\n";
    const char *k_n594 = kofun_rt_text_concat(k_n595, k_n662);
    const char *k_n663 = "        if (strlen(name) == length && strncmp(name, start, length) == 0) {\n";
    const char *k_n593 = kofun_rt_text_concat(k_n594, k_n663);
    const char *k_n664 = "            return variable_values[index - 1];\n";
    const char *k_n592 = kofun_rt_text_concat(k_n593, k_n664);
    const char *k_n665 = "        }\n";
    const char *k_n591 = kofun_rt_text_concat(k_n592, k_n665);
    const char *k_n666 = "    }\n";
    const char *k_n590 = kofun_rt_text_concat(k_n591, k_n666);
    const char *k_n667 = "    runtime_error(\"error[R011]: unknown Core binding\");\n";
    const char *k_n589 = kofun_rt_text_concat(k_n590, k_n667);
    const char *k_n668 = "    return 0;\n";
    const char *k_n588 = kofun_rt_text_concat(k_n589, k_n668);
    const char *k_n669 = "}\n\n";
    const char *k_n587 = kofun_rt_text_concat(k_n588, k_n669);
    const char *k_n670 = "static uint64_t magnitude(uint64_t limit) {\n";
    const char *k_n586 = kofun_rt_text_concat(k_n587, k_n670);
    const char *k_n671 = "    uint64_t value = 0;\n";
    const char *k_n585 = kofun_rt_text_concat(k_n586, k_n671);
    const char *k_n672 = "    bool any = false;\n";
    const char *k_n584 = kofun_rt_text_concat(k_n585, k_n672);
    const char *k_n673 = "    while (isdigit((unsigned char)*cursor)) {\n";
    const char *k_n583 = kofun_rt_text_concat(k_n584, k_n673);
    const char *k_n674 = "        uint64_t digit = (uint64_t)(*cursor++ - '0');\n";
    const char *k_n582 = kofun_rt_text_concat(k_n583, k_n674);
    const char *k_n675 = "        any = true;\n";
    const char *k_n581 = kofun_rt_text_concat(k_n582, k_n675);
    const char *k_n676 = "        if (value > (limit - digit) / 10) {\n";
    const char *k_n580 = kofun_rt_text_concat(k_n581, k_n676);
    const char *k_n677 = "            runtime_error(\"error[R010]: integer overflow in literal\");\n";
    const char *k_n579 = kofun_rt_text_concat(k_n580, k_n677);
    const char *k_n678 = "            return 0;\n";
    const char *k_n578 = kofun_rt_text_concat(k_n579, k_n678);
    const char *k_n679 = "        }\n";
    const char *k_n577 = kofun_rt_text_concat(k_n578, k_n679);
    const char *k_n680 = "        value = value * 10 + digit;\n";
    const char *k_n576 = kofun_rt_text_concat(k_n577, k_n680);
    const char *k_n681 = "    }\n";
    const char *k_n575 = kofun_rt_text_concat(k_n576, k_n681);
    const char *k_n682 = "    if (!any) runtime_error(\"error[R011]: expected integer expression\");\n";
    const char *k_n574 = kofun_rt_text_concat(k_n575, k_n682);
    const char *k_n683 = "    return value;\n";
    const char *k_n573 = kofun_rt_text_concat(k_n574, k_n683);
    const char *k_n684 = "}\n\n";
    const char *k_n572 = kofun_rt_text_concat(k_n573, k_n684);
    const char *k_n685 = "static int64_t expression(void);\n\n";
    const char *k_n571 = kofun_rt_text_concat(k_n572, k_n685);
    const char *k_n686 = "static int64_t primary(void) {\n";
    const char *k_n570 = kofun_rt_text_concat(k_n571, k_n686);
    const char *k_n687 = "    skip_space();\n";
    const char *k_n569 = kofun_rt_text_concat(k_n570, k_n687);
    const char *k_n688 = "    if (*cursor == '(') {\n";
    const char *k_n568 = kofun_rt_text_concat(k_n569, k_n688);
    const char *k_n689 = "        ++cursor;\n";
    const char *k_n567 = kofun_rt_text_concat(k_n568, k_n689);
    const char *k_n690 = "        int64_t value = expression();\n";
    const char *k_n566 = kofun_rt_text_concat(k_n567, k_n690);
    const char *k_n691 = "        skip_space();\n";
    const char *k_n565 = kofun_rt_text_concat(k_n566, k_n691);
    const char *k_n692 = "        if (*cursor != ')') runtime_error(\"error[R011]: expected `)`\");\n";
    const char *k_n564 = kofun_rt_text_concat(k_n565, k_n692);
    const char *k_n693 = "        else ++cursor;\n";
    const char *k_n563 = kofun_rt_text_concat(k_n564, k_n693);
    const char *k_n694 = "        return value;\n";
    const char *k_n562 = kofun_rt_text_concat(k_n563, k_n694);
    const char *k_n695 = "    }\n";
    const char *k_n561 = kofun_rt_text_concat(k_n562, k_n695);
    const char *k_n696 = "    if (isalpha((unsigned char)*cursor) || *cursor == '_') {\n";
    const char *k_n560 = kofun_rt_text_concat(k_n561, k_n696);
    const char *k_n697 = "        const char *start = cursor++;\n";
    const char *k_n559 = kofun_rt_text_concat(k_n560, k_n697);
    const char *k_n698 = "        while (isalnum((unsigned char)*cursor) || *cursor == '_') ++cursor;\n";
    const char *k_n558 = kofun_rt_text_concat(k_n559, k_n698);
    const char *k_n699 = "        return variable(start, (size_t)(cursor - start));\n";
    const char *k_n557 = kofun_rt_text_concat(k_n558, k_n699);
    const char *k_n700 = "    }\n";
    const char *k_n556 = kofun_rt_text_concat(k_n557, k_n700);
    const char *k_n701 = "    return (int64_t)magnitude(INT64_MAX);\n";
    const char *k_n555 = kofun_rt_text_concat(k_n556, k_n701);
    const char *k_n702 = "}\n\n";
    const char *k_n554 = kofun_rt_text_concat(k_n555, k_n702);
    const char *k_n703 = "static int64_t unary(void) {\n";
    const char *k_n553 = kofun_rt_text_concat(k_n554, k_n703);
    const char *k_n704 = "    skip_space();\n";
    const char *k_n552 = kofun_rt_text_concat(k_n553, k_n704);
    const char *k_n705 = "    if (*cursor == '+') {\n";
    const char *k_n551 = kofun_rt_text_concat(k_n552, k_n705);
    const char *k_n706 = "        ++cursor;\n";
    const char *k_n550 = kofun_rt_text_concat(k_n551, k_n706);
    const char *k_n707 = "        return unary();\n";
    const char *k_n549 = kofun_rt_text_concat(k_n550, k_n707);
    const char *k_n708 = "    }\n";
    const char *k_n548 = kofun_rt_text_concat(k_n549, k_n708);
    const char *k_n709 = "    if (*cursor == '-') {\n";
    const char *k_n547 = kofun_rt_text_concat(k_n548, k_n709);
    const char *k_n710 = "        ++cursor;\n";
    const char *k_n546 = kofun_rt_text_concat(k_n547, k_n710);
    const char *k_n711 = "        skip_space();\n";
    const char *k_n545 = kofun_rt_text_concat(k_n546, k_n711);
    const char *k_n712 = "        if (isdigit((unsigned char)*cursor)) {\n";
    const char *k_n544 = kofun_rt_text_concat(k_n545, k_n712);
    const char *k_n713 = "            uint64_t value = magnitude((uint64_t)INT64_MAX + 1);\n";
    const char *k_n543 = kofun_rt_text_concat(k_n544, k_n713);
    const char *k_n714 = "            if (value == (uint64_t)INT64_MAX + 1) return INT64_MIN;\n";
    const char *k_n542 = kofun_rt_text_concat(k_n543, k_n714);
    const char *k_n715 = "            return -(int64_t)value;\n";
    const char *k_n541 = kofun_rt_text_concat(k_n542, k_n715);
    const char *k_n716 = "        }\n";
    const char *k_n540 = kofun_rt_text_concat(k_n541, k_n716);
    const char *k_n717 = "        int64_t value = unary();\n";
    const char *k_n539 = kofun_rt_text_concat(k_n540, k_n717);
    const char *k_n718 = "        if (!failed && value == INT64_MIN) {\n";
    const char *k_n538 = kofun_rt_text_concat(k_n539, k_n718);
    const char *k_n719 = "            runtime_error(\"error[R010]: integer overflow in unary operator `-`\");\n";
    const char *k_n537 = kofun_rt_text_concat(k_n538, k_n719);
    const char *k_n720 = "            return 0;\n";
    const char *k_n536 = kofun_rt_text_concat(k_n537, k_n720);
    const char *k_n721 = "        }\n";
    const char *k_n535 = kofun_rt_text_concat(k_n536, k_n721);
    const char *k_n722 = "        return -value;\n";
    const char *k_n534 = kofun_rt_text_concat(k_n535, k_n722);
    const char *k_n723 = "    }\n";
    const char *k_n533 = kofun_rt_text_concat(k_n534, k_n723);
    const char *k_n724 = "    return primary();\n";
    const char *k_n532 = kofun_rt_text_concat(k_n533, k_n724);
    const char *k_n725 = "}\n\n";
    const char *k_n531 = kofun_rt_text_concat(k_n532, k_n725);
    const char *k_n726 = "static int64_t checked_add(int64_t left, int64_t right) {\n";
    const char *k_n530 = kofun_rt_text_concat(k_n531, k_n726);
    const char *k_n727 = "    int64_t result;\n";
    const char *k_n529 = kofun_rt_text_concat(k_n530, k_n727);
    const char *k_n728 = "    if (__builtin_add_overflow(left, right, &result)) {\n";
    const char *k_n528 = kofun_rt_text_concat(k_n529, k_n728);
    const char *k_n729 = "        runtime_error(\"error[R010]: integer overflow in operator `+`\");\n";
    const char *k_n527 = kofun_rt_text_concat(k_n528, k_n729);
    const char *k_n730 = "        return 0;\n";
    const char *k_n526 = kofun_rt_text_concat(k_n527, k_n730);
    const char *k_n731 = "    }\n";
    const char *k_n525 = kofun_rt_text_concat(k_n526, k_n731);
    const char *k_n732 = "    return result;\n";
    const char *k_n524 = kofun_rt_text_concat(k_n525, k_n732);
    const char *k_n733 = "}\n\n";
    const char *k_n523 = kofun_rt_text_concat(k_n524, k_n733);
    const char *k_n734 = "static int64_t checked_sub(int64_t left, int64_t right) {\n";
    const char *k_n522 = kofun_rt_text_concat(k_n523, k_n734);
    const char *k_n735 = "    int64_t result;\n";
    const char *k_n521 = kofun_rt_text_concat(k_n522, k_n735);
    const char *k_n736 = "    if (__builtin_sub_overflow(left, right, &result)) {\n";
    const char *k_n520 = kofun_rt_text_concat(k_n521, k_n736);
    const char *k_n737 = "        runtime_error(\"error[R010]: integer overflow in operator `-`\");\n";
    const char *k_n519 = kofun_rt_text_concat(k_n520, k_n737);
    const char *k_n738 = "        return 0;\n";
    const char *k_n518 = kofun_rt_text_concat(k_n519, k_n738);
    const char *k_n739 = "    }\n";
    const char *k_n517 = kofun_rt_text_concat(k_n518, k_n739);
    const char *k_n740 = "    return result;\n";
    const char *k_n516 = kofun_rt_text_concat(k_n517, k_n740);
    const char *k_n741 = "}\n\n";
    const char *k_n515 = kofun_rt_text_concat(k_n516, k_n741);
    const char *k_n742 = "static int64_t checked_mul(int64_t left, int64_t right) {\n";
    const char *k_n514 = kofun_rt_text_concat(k_n515, k_n742);
    const char *k_n743 = "    int64_t result;\n";
    const char *k_n513 = kofun_rt_text_concat(k_n514, k_n743);
    const char *k_n744 = "    if (__builtin_mul_overflow(left, right, &result)) {\n";
    const char *k_n512 = kofun_rt_text_concat(k_n513, k_n744);
    const char *k_n745 = "        runtime_error(\"error[R010]: integer overflow in operator `*`\");\n";
    const char *k_n511 = kofun_rt_text_concat(k_n512, k_n745);
    const char *k_n746 = "        return 0;\n";
    const char *k_n510 = kofun_rt_text_concat(k_n511, k_n746);
    const char *k_n747 = "    }\n";
    const char *k_n509 = kofun_rt_text_concat(k_n510, k_n747);
    const char *k_n748 = "    return result;\n";
    const char *k_n508 = kofun_rt_text_concat(k_n509, k_n748);
    const char *k_n749 = "}\n\n";
    const char *k_n507 = kofun_rt_text_concat(k_n508, k_n749);
    const char *k_n750 = "static int64_t floor_div(int64_t left, int64_t right) {\n";
    const char *k_n506 = kofun_rt_text_concat(k_n507, k_n750);
    const char *k_n751 = "    if (right == 0) {\n";
    const char *k_n505 = kofun_rt_text_concat(k_n506, k_n751);
    const char *k_n752 = "        runtime_error(\"error[R010]: operator `//` failed: division by zero\");\n";
    const char *k_n504 = kofun_rt_text_concat(k_n505, k_n752);
    const char *k_n753 = "        return 0;\n";
    const char *k_n503 = kofun_rt_text_concat(k_n504, k_n753);
    const char *k_n754 = "    }\n";
    const char *k_n502 = kofun_rt_text_concat(k_n503, k_n754);
    const char *k_n755 = "    if (left == INT64_MIN && right == -1) {\n";
    const char *k_n501 = kofun_rt_text_concat(k_n502, k_n755);
    const char *k_n756 = "        runtime_error(\"error[R010]: integer overflow in operator `//`\");\n";
    const char *k_n500 = kofun_rt_text_concat(k_n501, k_n756);
    const char *k_n757 = "        return 0;\n";
    const char *k_n499 = kofun_rt_text_concat(k_n500, k_n757);
    const char *k_n758 = "    }\n";
    const char *k_n498 = kofun_rt_text_concat(k_n499, k_n758);
    const char *k_n759 = "    int64_t quotient = left / right;\n";
    const char *k_n497 = kofun_rt_text_concat(k_n498, k_n759);
    const char *k_n760 = "    int64_t remainder = left % right;\n";
    const char *k_n496 = kofun_rt_text_concat(k_n497, k_n760);
    const char *k_n761 = "    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;\n";
    const char *k_n495 = kofun_rt_text_concat(k_n496, k_n761);
    const char *k_n762 = "    return quotient;\n";
    const char *k_n494 = kofun_rt_text_concat(k_n495, k_n762);
    const char *k_n763 = "}\n\n";
    const char *k_n493 = kofun_rt_text_concat(k_n494, k_n763);
    const char *k_n764 = "static int64_t floor_mod(int64_t left, int64_t right) {\n";
    const char *k_n492 = kofun_rt_text_concat(k_n493, k_n764);
    const char *k_n765 = "    if (right == 0) {\n";
    const char *k_n491 = kofun_rt_text_concat(k_n492, k_n765);
    const char *k_n766 = "        runtime_error(\"error[R010]: operator `%` failed: division by zero\");\n";
    const char *k_n490 = kofun_rt_text_concat(k_n491, k_n766);
    const char *k_n767 = "        return 0;\n";
    const char *k_n489 = kofun_rt_text_concat(k_n490, k_n767);
    const char *k_n768 = "    }\n";
    const char *k_n488 = kofun_rt_text_concat(k_n489, k_n768);
    const char *k_n769 = "    if (left == INT64_MIN && right == -1) return 0;\n";
    const char *k_n487 = kofun_rt_text_concat(k_n488, k_n769);
    const char *k_n770 = "    int64_t remainder = left % right;\n";
    const char *k_n486 = kofun_rt_text_concat(k_n487, k_n770);
    const char *k_n771 = "    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;\n";
    const char *k_n485 = kofun_rt_text_concat(k_n486, k_n771);
    const char *k_n772 = "    return remainder;\n";
    const char *k_n484 = kofun_rt_text_concat(k_n485, k_n772);
    const char *k_n773 = "}\n\n";
    const char *k_n483 = kofun_rt_text_concat(k_n484, k_n773);
    const char *k_n774 = "static int64_t term(void) {\n";
    const char *k_n482 = kofun_rt_text_concat(k_n483, k_n774);
    const char *k_n775 = "    int64_t value = unary();\n";
    const char *k_n481 = kofun_rt_text_concat(k_n482, k_n775);
    const char *k_n776 = "    for (;;) {\n";
    const char *k_n480 = kofun_rt_text_concat(k_n481, k_n776);
    const char *k_n777 = "        skip_space();\n";
    const char *k_n479 = kofun_rt_text_concat(k_n480, k_n777);
    const char *k_n778 = "        if (*cursor == '*') {\n";
    const char *k_n478 = kofun_rt_text_concat(k_n479, k_n778);
    const char *k_n779 = "            ++cursor;\n";
    const char *k_n477 = kofun_rt_text_concat(k_n478, k_n779);
    const char *k_n780 = "            value = checked_mul(value, unary());\n";
    const char *k_n476 = kofun_rt_text_concat(k_n477, k_n780);
    const char *k_n781 = "        } else if (cursor[0] == '/' && cursor[1] == '/') {\n";
    const char *k_n475 = kofun_rt_text_concat(k_n476, k_n781);
    const char *k_n782 = "            cursor += 2;\n";
    const char *k_n474 = kofun_rt_text_concat(k_n475, k_n782);
    const char *k_n783 = "            value = floor_div(value, unary());\n";
    const char *k_n473 = kofun_rt_text_concat(k_n474, k_n783);
    const char *k_n784 = "        } else if (*cursor == '%') {\n";
    const char *k_n472 = kofun_rt_text_concat(k_n473, k_n784);
    const char *k_n785 = "            ++cursor;\n";
    const char *k_n471 = kofun_rt_text_concat(k_n472, k_n785);
    const char *k_n786 = "            value = floor_mod(value, unary());\n";
    const char *k_n470 = kofun_rt_text_concat(k_n471, k_n786);
    const char *k_n787 = "        } else if (*cursor == '/') {\n";
    const char *k_n469 = kofun_rt_text_concat(k_n470, k_n787);
    const char *k_n788 = "            ++cursor;\n";
    const char *k_n468 = kofun_rt_text_concat(k_n469, k_n788);
    const char *k_n789 = "            int64_t right = unary();\n";
    const char *k_n467 = kofun_rt_text_concat(k_n468, k_n789);
    const char *k_n790 = "            if (right == 0) runtime_error(\"error[R010]: operator `/` failed: division by zero\");\n";
    const char *k_n466 = kofun_rt_text_concat(k_n467, k_n790);
    const char *k_n791 = "            else if (value == INT64_MIN && right == -1) runtime_error(\"error[R010]: integer overflow in operator `/`\");\n";
    const char *k_n465 = kofun_rt_text_concat(k_n466, k_n791);
    const char *k_n792 = "            else value /= right;\n";
    const char *k_n464 = kofun_rt_text_concat(k_n465, k_n792);
    const char *k_n793 = "        } else {\n";
    const char *k_n463 = kofun_rt_text_concat(k_n464, k_n793);
    const char *k_n794 = "            return value;\n";
    const char *k_n462 = kofun_rt_text_concat(k_n463, k_n794);
    const char *k_n795 = "        }\n";
    const char *k_n461 = kofun_rt_text_concat(k_n462, k_n795);
    const char *k_n796 = "    }\n";
    const char *k_n460 = kofun_rt_text_concat(k_n461, k_n796);
    const char *k_n797 = "}\n\n";
    const char *k_n459 = kofun_rt_text_concat(k_n460, k_n797);
    const char *k_n798 = "static int64_t expression(void) {\n";
    const char *k_n458 = kofun_rt_text_concat(k_n459, k_n798);
    const char *k_n799 = "    int64_t value = term();\n";
    const char *k_n457 = kofun_rt_text_concat(k_n458, k_n799);
    const char *k_n800 = "    for (;;) {\n";
    const char *k_n456 = kofun_rt_text_concat(k_n457, k_n800);
    const char *k_n801 = "        skip_space();\n";
    const char *k_n455 = kofun_rt_text_concat(k_n456, k_n801);
    const char *k_n802 = "        if (*cursor == '+') {\n";
    const char *k_n454 = kofun_rt_text_concat(k_n455, k_n802);
    const char *k_n803 = "            ++cursor;\n";
    const char *k_n453 = kofun_rt_text_concat(k_n454, k_n803);
    const char *k_n804 = "            value = checked_add(value, term());\n";
    const char *k_n452 = kofun_rt_text_concat(k_n453, k_n804);
    const char *k_n805 = "        } else if (*cursor == '-') {\n";
    const char *k_n451 = kofun_rt_text_concat(k_n452, k_n805);
    const char *k_n806 = "            ++cursor;\n";
    const char *k_n450 = kofun_rt_text_concat(k_n451, k_n806);
    const char *k_n807 = "            value = checked_sub(value, term());\n";
    const char *k_n449 = kofun_rt_text_concat(k_n450, k_n807);
    const char *k_n808 = "        } else {\n";
    const char *k_n448 = kofun_rt_text_concat(k_n449, k_n808);
    const char *k_n809 = "            return value;\n";
    const char *k_n447 = kofun_rt_text_concat(k_n448, k_n809);
    const char *k_n810 = "        }\n";
    const char *k_n446 = kofun_rt_text_concat(k_n447, k_n810);
    const char *k_n811 = "    }\n";
    const char *k_n445 = kofun_rt_text_concat(k_n446, k_n811);
    const char *k_n812 = "}\n\n";
    const char *k_n444 = kofun_rt_text_concat(k_n445, k_n812);
    const char *k_n813 = "static int64_t evaluate(const char *source) {\n";
    const char *k_n443 = kofun_rt_text_concat(k_n444, k_n813);
    const char *k_n814 = "    cursor = source;\n";
    const char *k_n442 = kofun_rt_text_concat(k_n443, k_n814);
    const char *k_n815 = "    int64_t value = expression();\n";
    const char *k_n441 = kofun_rt_text_concat(k_n442, k_n815);
    const char *k_n816 = "    skip_space();\n";
    const char *k_n440 = kofun_rt_text_concat(k_n441, k_n816);
    const char *k_n817 = "    if (*cursor != '\\0') runtime_error(\"error[R011]: trailing input\");\n";
    const char *k_n439 = kofun_rt_text_concat(k_n440, k_n817);
    const char *k_n818 = "    return value;\n";
    const char *k_n438 = kofun_rt_text_concat(k_n439, k_n818);
    const char *k_n819 = "}\n\n";
    const char *k_n437 = kofun_rt_text_concat(k_n438, k_n819);
    const char *k_n820 = "int main(void) {\n";
    const char *k_n436 = kofun_rt_text_concat(k_n437, k_n820);
    const char *k_n821 = "    (void)set_variable;\n";
    const char *k_n435 = kofun_rt_text_concat(k_n436, k_n821);
    const char * k_n823 = k_b52;
    const char * k_n822 = kofun_fn_emit_statements(k_n823);
    if (kofun_failed) return "";
    const char *k_n434 = kofun_rt_text_concat(k_n435, k_n822);
    const char *k_n824 = "    return 0;\n";
    const char *k_n433 = kofun_rt_text_concat(k_n434, k_n824);
    const char *k_n825 = "}\n";
    const char *k_n432 = kofun_rt_text_concat(k_n433, k_n825);
    return k_n432;
}

static bool kofun_fn_compile_file(const char *k_b53, const char *k_b54) {
    const char * k_n829 = k_b53;
    const char * k_n828 = kofun_rt_read_text(k_n829);
    const char * k_b55 = k_n828;
    const char * k_n832 = k_b55;
    const char * k_n831 = kofun_rt_validate_unicode_source(k_n832);
    const char * k_b56 = k_n831;
    const char * k_n836 = k_b56;
    int64_t k_n835 = kofun_rt_text_len(k_n836);
    int64_t k_n837 = INT64_C(0);
    bool k_n834 = k_n835 > k_n837;
    if (k_n834) {
        const char * k_n840 = k_b56;
        printf("%s\n", k_n840);
        bool k_n842 = false;
        return k_n842;
    }
    const char * k_n845 = k_b55;
    const char *k_n846 = "\n";
    const char *k_n844 = kofun_rt_text_concat(k_n845, k_n846);
    const char * k_b57 = k_n844;
    const char * k_n850 = k_b57;
    bool k_n849 = kofun_fn_valid_source(k_n850);
    if (kofun_failed) return false;
    bool k_n848 = !k_n849;
    if (k_n848) {
        const char *k_n853 = "compile error: unsupported Kofun integer Core source";
        printf("%s\n", k_n853);
        bool k_n855 = false;
        return k_n855;
    }
    const char * k_n859 = k_b57;
    const char * k_n858 = kofun_fn_emit_c(k_n859);
    if (kofun_failed) return false;
    const char *k_n860 = "if (isalpha((unsigned char)*cursor) || *cursor == '_')";
    const char *k_n862 = "if (isalpha((unsigned char)*cursor) || *cursor == '_' || ";
    const char *k_n863 = "(unsigned char)*cursor >= 0x80)";
    const char *k_n861 = kofun_rt_text_concat(k_n862, k_n863);
    const char * k_n857 = kofun_rt_replace(k_n858, k_n860, k_n861);
    const char * k_b58 = k_n857;
    const char * k_n866 = k_b58;
    const char *k_n867 = "while (isalnum((unsigned char)*cursor) || *cursor == '_') ++cursor;";
    const char *k_n869 = "while (isalnum((unsigned char)*cursor) || *cursor == '_' || ";
    const char *k_n870 = "(unsigned char)*cursor >= 0x80) ++cursor;";
    const char *k_n868 = kofun_rt_text_concat(k_n869, k_n870);
    const char * k_n865 = kofun_rt_replace(k_n866, k_n867, k_n868);
    k_b58 = k_n865;
    const char * k_n873 = k_b54;
    const char * k_n874 = k_b58;
    kofun_rt_write_text(k_n873, k_n874);
    const char * k_n877 = k_b54;
    printf("%s\n", k_n877);
    bool k_n879 = true;
    return k_n879;
}

int main(int argc, char **argv) {
    kofun_runtime_argc = argc > 0 ? argc - 1 : 0;
    kofun_runtime_argv = argc > 0 ? argv + 1 : argv;
    (void)kofun_failed;
    (void)kofun_error;
    (void)kofun_add;
    (void)kofun_sub;
    (void)kofun_mul;
    (void)kofun_neg;
    (void)kofun_floor_div;
    (void)kofun_floor_mod;
    (void)kofun_fn_identifier_char;
    (void)kofun_fn_valid_name;
    (void)kofun_fn_valid_expression;
    (void)kofun_fn_print_expression;
    (void)kofun_fn_binding_name;
    (void)kofun_fn_binding_expression;
    (void)kofun_fn_valid_source;
    (void)kofun_fn_emit_statements;
    (void)kofun_fn_emit_c;
    (void)kofun_fn_compile_file;
    kofun_text_list k_n882 = kofun_rt_args();
    kofun_text_list k_b59 = k_n882;
    kofun_text_list k_n886 = k_b59;
    int64_t k_n885 = kofun_rt_text_list_len(k_n886);
    int64_t k_n887 = INT64_C(2);
    bool k_n884 = k_n885 != k_n887;
    if (k_n884) {
        const char *k_n890 = "usage: kofun-stage1 INPUT.kofun OUTPUT.c";
        printf("%s\n", k_n890);
        return 0;
    }
    kofun_text_list k_n895 = k_b59;
    int64_t k_n896 = INT64_C(0);
    const char *k_n894 = kofun_rt_text_list_get(k_n895, k_n896);
    kofun_text_list k_n898 = k_b59;
    int64_t k_n899 = INT64_C(1);
    const char *k_n897 = kofun_rt_text_list_get(k_n898, k_n899);
    bool k_n893 = kofun_fn_compile_file(k_n894, k_n897);
    if (kofun_failed) return 1;
    (void)k_n893;
    return 0;
}

