/* Generated by kofun-stage2 --lower-selfhost-c11. */
/* Source: bootstrap/stage1/compiler.kofun 5e7aa3643c99478a3bbf84dc5011321f5863e9cf9d42a24265d762eec3258990 */

#include <ctype.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "kofun_unicode.c"

typedef struct {
    int64_t len;
    const char **items;
} kofun_text_list;

int kofun_runtime_argc = 0;
char **kofun_runtime_argv = NULL;

static bool kofun_failed;

static void kofun_error(const char *message) {
    if (!kofun_failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    kofun_failed = true;
}

static int64_t kofun_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t kofun_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t kofun_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t kofun_neg(int64_t value) {
    if (value == INT64_MIN) {
        kofun_error(
            "error[R010]: integer overflow in unary operator `-`"
        );
        return 0;
    }
    return -value;
}

static int64_t kofun_floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        kofun_error(
            "error[R010]: operator `//` failed: division by zero"
        );
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        kofun_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) {
        --quotient;
    }
    return quotient;
}

static int64_t kofun_floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        kofun_error(
            "error[R010]: operator `%` failed: division by zero"
        );
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        return 0;
    }
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) {
        remainder += right;
    }
    return remainder;
}

void kofun_rt_panic(const char *message) {
    fprintf(stderr, "Kofun runtime error: %s\n", message);
    exit(1);
}

void kofun_rt_fail(void) {
    exit(1);
}

void *kofun_rt_alloc(size_t size) {
    void *value = malloc(size == 0 ? 1 : size);
    if (value == NULL) {
        kofun_rt_panic("out of memory");
    }
    return value;
}

char *kofun_rt_copy_n(const char *value, size_t length) {
    char *result = (char *)kofun_rt_alloc(length + 1);
    if (length > 0) {
        memcpy(result, value, length);
    }
    result[length] = '\0';
    return result;
}

char *kofun_rt_text_concat(const char *left, const char *right) {
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    char *result = (char *)kofun_rt_alloc(left_len + right_len + 1);
    memcpy(result, left, left_len);
    memcpy(result + left_len, right, right_len + 1);
    return result;
}

bool kofun_rt_text_equal(const char *left, const char *right) {
    return strcmp(left, right) == 0;
}

int64_t kofun_rt_text_len(const char *value) {
    return (int64_t)strlen(value);
}

int64_t kofun_rt_text_list_len(kofun_text_list values) {
    return values.len;
}

kofun_text_list kofun_rt_args(void) {
    kofun_text_list result;
    result.len = (int64_t)kofun_runtime_argc;
    result.items = (const char **)kofun_runtime_argv;
    return result;
}

kofun_text_list kofun_rt_chars(const char *value) {
    size_t length = strlen(value);
    const char **items = (const char **)kofun_rt_alloc(
        sizeof(char *) * (length == 0 ? 1 : length)
    );
    for (size_t index = 0; index < length; ++index) {
        items[index] = kofun_rt_copy_n(value + index, 1);
    }
    kofun_text_list result;
    result.len = (int64_t)length;
    result.items = items;
    return result;
}

const char *kofun_rt_text_list_get(kofun_text_list values, int64_t index) {
    if (index < 0 || index >= values.len) {
        kofun_rt_panic("List[Text] index out of bounds");
    }
    return values.items[index];
}

bool kofun_rt_text_contains(const char *value, const char *needle) {
    return strstr(value, needle) != NULL;
}

int64_t kofun_rt_find(const char *value, const char *needle) {
    const char *found = strstr(value, needle);
    return found == NULL ? INT64_C(-1) : (int64_t)(found - value);
}

char *kofun_rt_text_slice(const char *value, int64_t start, int64_t end) {
    int64_t length = (int64_t)strlen(value);
    if (start < 0) start = 0;
    if (end < start) end = start;
    if (start > length) start = length;
    if (end > length) end = length;
    return kofun_rt_copy_n(value + start, (size_t)(end - start));
}

char *kofun_rt_trim(const char *value) {
    const unsigned char *start = (const unsigned char *)value;
    while (*start != '\0' && isspace(*start)) {
        ++start;
    }
    const unsigned char *end =
        (const unsigned char *)value + strlen(value);
    while (end > start && isspace(end[-1])) {
        --end;
    }
    return kofun_rt_copy_n((const char *)start, (size_t)(end - start));
}

char *kofun_rt_replace(
    const char *value,
    const char *old,
    const char *replacement
) {
    size_t old_len = strlen(old);
    if (old_len == 0) {
        return kofun_rt_copy_n(value, strlen(value));
    }
    size_t replacement_len = strlen(replacement);
    size_t count = 0;
    const char *cursor = value;
    while ((cursor = strstr(cursor, old)) != NULL) {
        ++count;
        cursor += old_len;
    }
    size_t value_len = strlen(value);
    size_t result_len;
    if (replacement_len >= old_len) {
        result_len = value_len + count * (replacement_len - old_len);
    } else {
        result_len = value_len - count * (old_len - replacement_len);
    }
    char *result = (char *)kofun_rt_alloc(result_len + 1);
    char *out = result;
    cursor = value;
    const char *match;
    while ((match = strstr(cursor, old)) != NULL) {
        size_t prefix = (size_t)(match - cursor);
        memcpy(out, cursor, prefix);
        out += prefix;
        memcpy(out, replacement, replacement_len);
        out += replacement_len;
        cursor = match + old_len;
    }
    strcpy(out, cursor);
    return result;
}

bool kofun_rt_starts_with(const char *value, const char *prefix) {
    size_t prefix_len = strlen(prefix);
    return strncmp(value, prefix, prefix_len) == 0;
}

bool kofun_rt_is_digit(const char *value) {
    return value[0] != '\0' && value[1] == '\0' &&
        isdigit((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_space(const char *value) {
    return value[0] != '\0' && value[1] == '\0' &&
        isspace((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_xid_continue(const char *value) {
    uint32_t codepoint = 0;
    size_t width = 0;
    size_t length = strlen(value);
    if (!kofun_unicode_decode(
            (const uint8_t *)value,
            length,
            0,
            &codepoint,
            &width)) {
        return false;
    }
    return kofun_unicode_is_xid_continue(codepoint);
}

const char *kofun_rt_validate_unicode_source(const char *value) {
    KofunUnicodeError unicode_error;
    if (kofun_unicode_validate_source(
            (const uint8_t *)value,
            strlen(value),
            &unicode_error)) {
        return "";
    }
    char message[1024];
    kofun_unicode_format_error(
        &unicode_error,
        getenv("KOFUN_DIAGNOSTIC_LOCALE"),
        message,
        sizeof(message)
    );
    return kofun_rt_copy_n(message, strlen(message));
}

char *kofun_rt_read_text(const char *path) {
    FILE *file = fopen(path, "rb");
    if (file == NULL) {
        kofun_rt_panic("cannot open input file");
    }
    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        kofun_rt_panic("cannot seek input file");
    }
    long size = ftell(file);
    if (size < 0) {
        fclose(file);
        kofun_rt_panic("cannot measure input file");
    }
    rewind(file);
    char *result = (char *)kofun_rt_alloc((size_t)size + 1);
    size_t read = fread(result, 1, (size_t)size, file);
    if (read != (size_t)size && ferror(file)) {
        fclose(file);
        kofun_rt_panic("cannot read input file");
    }
    result[read] = '\0';
    fclose(file);
    return result;
}

void kofun_rt_write_text(const char *path, const char *value) {
    FILE *file = fopen(path, "wb");
    if (file == NULL) {
        kofun_rt_panic("cannot open output file");
    }
    size_t length = strlen(value);
    if (fwrite(value, 1, length, file) != length) {
        fclose(file);
        kofun_rt_panic("cannot write output file");
    }
    if (fclose(file) != 0) {
        kofun_rt_panic("cannot close output file");
    }
}

static bool kofun_fn_identifier_char(const char *k_b23);
static bool kofun_fn_valid_name(const char *k_b24);
static int64_t kofun_fn_digit_value(const char *k_b27);
static bool kofun_fn_all_digits(const char *k_b28);
static bool kofun_fn_within_bound(const char *k_b31, const char *k_b32);
static bool kofun_fn_preceded_by_operand(const char *k_b40, int64_t k_b41);
static int64_t kofun_fn_split_binary(const char *k_b45, const char *k_b46);
static bool kofun_fn_wraps_whole(const char *k_b52);
static int64_t kofun_fn_last_newline(const char *k_b57);
static const char *kofun_fn_lowered_statements(const char *k_b61);
static const char *kofun_fn_lowered_operand(const char *k_b63);
static const char *kofun_fn_lower_step(const char *k_b65, const char *k_b66, const char *k_b67, const char *k_b68);
static const char *kofun_fn_lower_atom(const char *k_b70, const char *k_b71);
static const char *kofun_fn_lower_negation(const char *k_b72, const char *k_b73, const char *k_b74);
static const char *kofun_fn_lower_expression(const char *k_b78, const char *k_b79, const char *k_b80);
static const char *kofun_fn_print_expression(const char *k_b91);
static const char *kofun_fn_binding_name(const char *k_b99);
static const char *kofun_fn_binding_expression(const char *k_b103);
static bool kofun_fn_valid_source(const char *k_b105);
static const char *kofun_fn_emit_statements(const char *k_b116);
static const char *kofun_fn_emit_c(const char *k_b126);
static bool kofun_fn_compile_file(const char *k_b127, const char *k_b128);

static bool kofun_fn_identifier_char(const char *k_b23) {
    const char * k_n4 = k_b23;
    bool k_n3 = kofun_rt_is_xid_continue(k_n4);
    bool k_n2 = k_n3;
    if (!k_n2) {
        const char *k_n6 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_";
        const char * k_n7 = k_b23;
        bool k_n5 = kofun_rt_text_contains(k_n6, k_n7);
        k_n2 = k_n5;
    }
    return k_n2;
}

static bool kofun_fn_valid_name(const char *k_b24) {
    const char * k_n11 = k_b24;
    kofun_text_list k_n10 = kofun_rt_chars(k_n11);
    kofun_text_list k_b25 = k_n10;
    kofun_text_list k_n16 = k_b25;
    int64_t k_n15 = kofun_rt_text_list_len(k_n16);
    int64_t k_n17 = INT64_C(0);
    bool k_n14 = k_n15 == k_n17;
    bool k_n13 = k_n14;
    if (!k_n13) {
        kofun_text_list k_n20 = k_b25;
        int64_t k_n21 = INT64_C(0);
        const char *k_n19 = kofun_rt_text_list_get(k_n20, k_n21);
        bool k_n18 = kofun_rt_is_digit(k_n19);
        k_n13 = k_n18;
    }
    if (k_n13) {
        bool k_n23 = false;
        return k_n23;
    }
    int64_t k_n26 = INT64_C(0);
    kofun_text_list k_n28 = k_b25;
    int64_t k_n27 = kofun_rt_text_list_len(k_n28);
    for (int64_t k_b26 = k_n26; k_b26 < k_n27; ++k_b26) {
        kofun_text_list k_n33 = k_b25;
        int64_t k_n34 = k_b26;
        const char *k_n32 = kofun_rt_text_list_get(k_n33, k_n34);
        bool k_n31 = kofun_fn_identifier_char(k_n32);
        if (kofun_failed) return false;
        bool k_n30 = !k_n31;
        if (k_n30) {
            bool k_n36 = false;
            return k_n36;
        }
    }
    bool k_n38 = true;
    return k_n38;
}

static int64_t kofun_fn_digit_value(const char *k_b27) {
    const char *k_n42 = "0123456789";
    const char * k_n43 = k_b27;
    int64_t k_n41 = kofun_rt_find(k_n42, k_n43);
    return k_n41;
}

static bool kofun_fn_all_digits(const char *k_b28) {
    const char * k_n47 = k_b28;
    kofun_text_list k_n46 = kofun_rt_chars(k_n47);
    kofun_text_list k_b29 = k_n46;
    kofun_text_list k_n51 = k_b29;
    int64_t k_n50 = kofun_rt_text_list_len(k_n51);
    int64_t k_n52 = INT64_C(0);
    bool k_n49 = k_n50 == k_n52;
    if (k_n49) {
        bool k_n54 = false;
        return k_n54;
    }
    int64_t k_n57 = INT64_C(0);
    kofun_text_list k_n59 = k_b29;
    int64_t k_n58 = kofun_rt_text_list_len(k_n59);
    for (int64_t k_b30 = k_n57; k_b30 < k_n58; ++k_b30) {
        kofun_text_list k_n64 = k_b29;
        int64_t k_n65 = k_b30;
        const char *k_n63 = kofun_rt_text_list_get(k_n64, k_n65);
        bool k_n62 = kofun_rt_is_digit(k_n63);
        bool k_n61 = !k_n62;
        if (k_n61) {
            bool k_n67 = false;
            return k_n67;
        }
    }
    bool k_n69 = true;
    return k_n69;
}

static bool kofun_fn_within_bound(const char *k_b31, const char *k_b32) {
    const char * k_n73 = k_b31;
    kofun_text_list k_n72 = kofun_rt_chars(k_n73);
    kofun_text_list k_b33 = k_n72;
    const char * k_n76 = k_b32;
    kofun_text_list k_n75 = kofun_rt_chars(k_n76);
    kofun_text_list k_b34 = k_n75;
    int64_t k_n78 = INT64_C(0);
    int64_t k_b35 = k_n78;
    for (;;) {
        int64_t k_n83 = k_b35;
        int64_t k_n84 = INT64_C(1);
        int64_t k_n82 = kofun_add(k_n83, k_n84);
        if (kofun_failed) return false;
        kofun_text_list k_n86 = k_b33;
        int64_t k_n85 = kofun_rt_text_list_len(k_n86);
        bool k_n81 = k_n82 < k_n85;
        bool k_n80 = k_n81;
        if (k_n80) {
            kofun_text_list k_n89 = k_b33;
            int64_t k_n90 = k_b35;
            const char *k_n88 = kofun_rt_text_list_get(k_n89, k_n90);
            const char *k_n91 = "0";
            bool k_n87 = kofun_rt_text_equal(k_n88, k_n91);
            k_n80 = k_n87;
        }
        if (!k_n80) break;
        int64_t k_n94 = k_b35;
        int64_t k_n95 = INT64_C(1);
        int64_t k_n93 = kofun_add(k_n94, k_n95);
        if (kofun_failed) return false;
        k_b35 = k_n93;
    }
    kofun_text_list k_n99 = k_b33;
    int64_t k_n98 = kofun_rt_text_list_len(k_n99);
    int64_t k_n100 = k_b35;
    int64_t k_n97 = kofun_sub(k_n98, k_n100);
    if (kofun_failed) return false;
    int64_t k_b36 = k_n97;
    int64_t k_n103 = k_b36;
    kofun_text_list k_n105 = k_b34;
    int64_t k_n104 = kofun_rt_text_list_len(k_n105);
    bool k_n102 = k_n103 != k_n104;
    if (k_n102) {
        int64_t k_n108 = k_b36;
        kofun_text_list k_n110 = k_b34;
        int64_t k_n109 = kofun_rt_text_list_len(k_n110);
        bool k_n107 = k_n108 < k_n109;
        return k_n107;
    }
    int64_t k_n113 = INT64_C(0);
    kofun_text_list k_n115 = k_b34;
    int64_t k_n114 = kofun_rt_text_list_len(k_n115);
    for (int64_t k_b37 = k_n113; k_b37 < k_n114; ++k_b37) {
        kofun_text_list k_n119 = k_b33;
        int64_t k_n121 = k_b35;
        int64_t k_n122 = k_b37;
        int64_t k_n120 = kofun_add(k_n121, k_n122);
        if (kofun_failed) return false;
        const char *k_n118 = kofun_rt_text_list_get(k_n119, k_n120);
        int64_t k_n117 = kofun_fn_digit_value(k_n118);
        if (kofun_failed) return false;
        int64_t k_b38 = k_n117;
        kofun_text_list k_n126 = k_b34;
        int64_t k_n127 = k_b37;
        const char *k_n125 = kofun_rt_text_list_get(k_n126, k_n127);
        int64_t k_n124 = kofun_fn_digit_value(k_n125);
        if (kofun_failed) return false;
        int64_t k_b39 = k_n124;
        int64_t k_n130 = k_b38;
        int64_t k_n131 = k_b39;
        bool k_n129 = k_n130 != k_n131;
        if (k_n129) {
            int64_t k_n134 = k_b38;
            int64_t k_n135 = k_b39;
            bool k_n133 = k_n134 < k_n135;
            return k_n133;
        }
    }
    bool k_n137 = true;
    return k_n137;
}

static bool kofun_fn_preceded_by_operand(const char *k_b40, int64_t k_b41) {
    const char * k_n141 = k_b40;
    kofun_text_list k_n140 = kofun_rt_chars(k_n141);
    kofun_text_list k_b42 = k_n140;
    int64_t k_n144 = k_b41;
    int64_t k_n145 = INT64_C(1);
    int64_t k_n143 = kofun_sub(k_n144, k_n145);
    if (kofun_failed) return false;
    int64_t k_b43 = k_n143;
    for (;;) {
        int64_t k_n148 = k_b43;
        int64_t k_n149 = INT64_C(0);
        bool k_n147 = k_n148 >= k_n149;
        if (!k_n147) break;
        kofun_text_list k_n152 = k_b42;
        int64_t k_n153 = k_b43;
        const char *k_n151 = kofun_rt_text_list_get(k_n152, k_n153);
        const char * k_b44 = k_n151;
        const char * k_n157 = k_b44;
        bool k_n156 = kofun_rt_is_space(k_n157);
        bool k_n155 = !k_n156;
        if (k_n155) {
            const char * k_n161 = k_b44;
            const char *k_n162 = ")";
            bool k_n160 = kofun_rt_text_equal(k_n161, k_n162);
            bool k_n159 = k_n160;
            if (!k_n159) {
                const char * k_n164 = k_b44;
                bool k_n163 = kofun_fn_identifier_char(k_n164);
                if (kofun_failed) return false;
                k_n159 = k_n163;
            }
            return k_n159;
        }
        int64_t k_n167 = k_b43;
        int64_t k_n168 = INT64_C(1);
        int64_t k_n166 = kofun_sub(k_n167, k_n168);
        if (kofun_failed) return false;
        k_b43 = k_n166;
    }
    bool k_n170 = false;
    return k_n170;
}

static int64_t kofun_fn_split_binary(const char *k_b45, const char *k_b46) {
    const char * k_n174 = k_b45;
    kofun_text_list k_n173 = kofun_rt_chars(k_n174);
    kofun_text_list k_b47 = k_n173;
    int64_t k_n176 = INT64_C(0);
    int64_t k_b48 = k_n176;
    int64_t k_n179 = INT64_C(1);
    int64_t k_n178 = kofun_neg(k_n179);
    if (kofun_failed) return INT64_C(0);
    int64_t k_b49 = k_n178;
    int64_t k_n182 = INT64_C(0);
    kofun_text_list k_n184 = k_b47;
    int64_t k_n183 = kofun_rt_text_list_len(k_n184);
    for (int64_t k_b50 = k_n182; k_b50 < k_n183; ++k_b50) {
        kofun_text_list k_n187 = k_b47;
        int64_t k_n188 = k_b50;
        const char *k_n186 = kofun_rt_text_list_get(k_n187, k_n188);
        const char * k_b51 = k_n186;
        const char * k_n191 = k_b51;
        const char *k_n192 = "(";
        bool k_n190 = kofun_rt_text_equal(k_n191, k_n192);
        if (k_n190) {
            int64_t k_n195 = k_b48;
            int64_t k_n196 = INT64_C(1);
            int64_t k_n194 = kofun_add(k_n195, k_n196);
            if (kofun_failed) return INT64_C(0);
            k_b48 = k_n194;
        } else {
            const char * k_n199 = k_b51;
            const char *k_n200 = ")";
            bool k_n198 = kofun_rt_text_equal(k_n199, k_n200);
            if (k_n198) {
                int64_t k_n203 = k_b48;
                int64_t k_n204 = INT64_C(1);
                int64_t k_n202 = kofun_sub(k_n203, k_n204);
                if (kofun_failed) return INT64_C(0);
                k_b48 = k_n202;
            } else {
                int64_t k_n208 = k_b48;
                int64_t k_n209 = INT64_C(0);
                bool k_n207 = k_n208 == k_n209;
                bool k_n206 = k_n207;
                if (k_n206) {
                    const char * k_n211 = k_b46;
                    const char * k_n212 = k_b51;
                    bool k_n210 = kofun_rt_text_contains(k_n211, k_n212);
                    k_n206 = k_n210;
                }
                if (k_n206) {
                    const char * k_n215 = k_b45;
                    int64_t k_n216 = k_b50;
                    bool k_n214 = kofun_fn_preceded_by_operand(k_n215, k_n216);
                    if (kofun_failed) return INT64_C(0);
                    if (k_n214) {
                        int64_t k_n218 = k_b50;
                        k_b49 = k_n218;
                    }
                }
            }
        }
    }
    int64_t k_n220 = k_b49;
    return k_n220;
}

static bool kofun_fn_wraps_whole(const char *k_b52) {
    const char * k_n224 = k_b52;
    kofun_text_list k_n223 = kofun_rt_chars(k_n224);
    kofun_text_list k_b53 = k_n223;
    kofun_text_list k_n229 = k_b53;
    int64_t k_n228 = kofun_rt_text_list_len(k_n229);
    int64_t k_n230 = INT64_C(2);
    bool k_n227 = k_n228 < k_n230;
    bool k_n226 = k_n227;
    if (!k_n226) {
        kofun_text_list k_n234 = k_b53;
        int64_t k_n235 = INT64_C(0);
        const char *k_n233 = kofun_rt_text_list_get(k_n234, k_n235);
        const char *k_n236 = "(";
        bool k_n232 = kofun_rt_text_equal(k_n233, k_n236);
        bool k_n231 = !k_n232;
        k_n226 = k_n231;
    }
    if (k_n226) {
        bool k_n238 = false;
        return k_n238;
    }
    int64_t k_n240 = INT64_C(0);
    int64_t k_b54 = k_n240;
    int64_t k_n243 = INT64_C(0);
    kofun_text_list k_n245 = k_b53;
    int64_t k_n244 = kofun_rt_text_list_len(k_n245);
    for (int64_t k_b55 = k_n243; k_b55 < k_n244; ++k_b55) {
        kofun_text_list k_n248 = k_b53;
        int64_t k_n249 = k_b55;
        const char *k_n247 = kofun_rt_text_list_get(k_n248, k_n249);
        const char * k_b56 = k_n247;
        const char * k_n252 = k_b56;
        const char *k_n253 = "(";
        bool k_n251 = kofun_rt_text_equal(k_n252, k_n253);
        if (k_n251) {
            int64_t k_n256 = k_b54;
            int64_t k_n257 = INT64_C(1);
            int64_t k_n255 = kofun_add(k_n256, k_n257);
            if (kofun_failed) return false;
            k_b54 = k_n255;
        } else {
            const char * k_n260 = k_b56;
            const char *k_n261 = ")";
            bool k_n259 = kofun_rt_text_equal(k_n260, k_n261);
            if (k_n259) {
                int64_t k_n264 = k_b54;
                int64_t k_n265 = INT64_C(1);
                int64_t k_n263 = kofun_sub(k_n264, k_n265);
                if (kofun_failed) return false;
                k_b54 = k_n263;
                int64_t k_n268 = k_b54;
                int64_t k_n269 = INT64_C(0);
                bool k_n267 = k_n268 == k_n269;
                if (k_n267) {
                    int64_t k_n272 = k_b55;
                    kofun_text_list k_n275 = k_b53;
                    int64_t k_n274 = kofun_rt_text_list_len(k_n275);
                    int64_t k_n276 = INT64_C(1);
                    int64_t k_n273 = kofun_sub(k_n274, k_n276);
                    if (kofun_failed) return false;
                    bool k_n271 = k_n272 == k_n273;
                    return k_n271;
                }
            }
        }
    }
    bool k_n278 = false;
    return k_n278;
}

static int64_t kofun_fn_last_newline(const char *k_b57) {
    const char * k_n282 = k_b57;
    kofun_text_list k_n281 = kofun_rt_chars(k_n282);
    kofun_text_list k_b58 = k_n281;
    int64_t k_n285 = INT64_C(1);
    int64_t k_n284 = kofun_neg(k_n285);
    if (kofun_failed) return INT64_C(0);
    int64_t k_b59 = k_n284;
    int64_t k_n288 = INT64_C(0);
    kofun_text_list k_n290 = k_b58;
    int64_t k_n289 = kofun_rt_text_list_len(k_n290);
    for (int64_t k_b60 = k_n288; k_b60 < k_n289; ++k_b60) {
        kofun_text_list k_n294 = k_b58;
        int64_t k_n295 = k_b60;
        const char *k_n293 = kofun_rt_text_list_get(k_n294, k_n295);
        const char *k_n296 = "\n";
        bool k_n292 = kofun_rt_text_equal(k_n293, k_n296);
        if (k_n292) {
            int64_t k_n298 = k_b60;
            k_b59 = k_n298;
        }
    }
    int64_t k_n300 = k_b59;
    return k_n300;
}

static const char *kofun_fn_lowered_statements(const char *k_b61) {
    const char * k_n304 = k_b61;
    int64_t k_n303 = kofun_fn_last_newline(k_n304);
    if (kofun_failed) return "";
    int64_t k_b62 = k_n303;
    int64_t k_n307 = k_b62;
    int64_t k_n308 = INT64_C(0);
    bool k_n306 = k_n307 < k_n308;
    if (k_n306) {
        const char *k_n310 = "";
        return k_n310;
    }
    const char * k_n313 = k_b61;
    int64_t k_n314 = INT64_C(0);
    int64_t k_n316 = k_b62;
    int64_t k_n317 = INT64_C(1);
    int64_t k_n315 = kofun_add(k_n316, k_n317);
    if (kofun_failed) return "";
    const char * k_n312 = kofun_rt_text_slice(k_n313, k_n314, k_n315);
    return k_n312;
}

static const char *kofun_fn_lowered_operand(const char *k_b63) {
    const char * k_n321 = k_b63;
    int64_t k_n320 = kofun_fn_last_newline(k_n321);
    if (kofun_failed) return "";
    int64_t k_b64 = k_n320;
    const char * k_n324 = k_b63;
    int64_t k_n326 = k_b64;
    int64_t k_n327 = INT64_C(1);
    int64_t k_n325 = kofun_add(k_n326, k_n327);
    if (kofun_failed) return "";
    const char * k_n329 = k_b63;
    int64_t k_n328 = kofun_rt_text_len(k_n329);
    const char * k_n323 = kofun_rt_text_slice(k_n324, k_n325, k_n328);
    return k_n323;
}

static const char *kofun_fn_lower_step(const char *k_b65, const char *k_b66, const char *k_b67, const char *k_b68) {
    const char *k_n333 = "kt_";
    const char * k_n334 = k_b65;
    const char *k_n332 = kofun_rt_text_concat(k_n333, k_n334);
    const char * k_b69 = k_n332;
    const char * k_n347 = k_b67;
    const char * k_n346 = kofun_fn_lowered_statements(k_n347);
    if (kofun_failed) return "";
    const char * k_n349 = k_b68;
    const char * k_n348 = kofun_fn_lowered_statements(k_n349);
    if (kofun_failed) return "";
    const char *k_n345 = kofun_rt_text_concat(k_n346, k_n348);
    const char *k_n350 = "        int64_t ";
    const char *k_n344 = kofun_rt_text_concat(k_n345, k_n350);
    const char * k_n351 = k_b69;
    const char *k_n343 = kofun_rt_text_concat(k_n344, k_n351);
    const char *k_n352 = " = ";
    const char *k_n342 = kofun_rt_text_concat(k_n343, k_n352);
    const char * k_n353 = k_b66;
    const char *k_n341 = kofun_rt_text_concat(k_n342, k_n353);
    const char * k_n355 = k_b67;
    const char * k_n354 = kofun_fn_lowered_operand(k_n355);
    if (kofun_failed) return "";
    const char *k_n340 = kofun_rt_text_concat(k_n341, k_n354);
    const char *k_n356 = ", ";
    const char *k_n339 = kofun_rt_text_concat(k_n340, k_n356);
    const char * k_n358 = k_b68;
    const char * k_n357 = kofun_fn_lowered_operand(k_n358);
    if (kofun_failed) return "";
    const char *k_n338 = kofun_rt_text_concat(k_n339, k_n357);
    const char *k_n359 = ");\n";
    const char *k_n337 = kofun_rt_text_concat(k_n338, k_n359);
    const char * k_n360 = k_b69;
    const char *k_n336 = kofun_rt_text_concat(k_n337, k_n360);
    return k_n336;
}

static const char *kofun_fn_lower_atom(const char *k_b70, const char *k_b71) {
    const char * k_n364 = k_b70;
    bool k_n363 = kofun_fn_all_digits(k_n364);
    if (kofun_failed) return "";
    if (k_n363) {
        const char * k_n368 = k_b70;
        const char *k_n369 = "9223372036854775807";
        bool k_n367 = kofun_fn_within_bound(k_n368, k_n369);
        if (kofun_failed) return "";
        bool k_n366 = !k_n367;
        if (k_n366) {
            const char *k_n371 = "";
            return k_n371;
        }
        const char * k_n373 = k_b70;
        return k_n373;
    }
    const char * k_n377 = k_b70;
    bool k_n376 = kofun_fn_valid_name(k_n377);
    if (kofun_failed) return "";
    bool k_n375 = !k_n376;
    if (k_n375) {
        const char *k_n379 = "";
        return k_n379;
    }
    const char * k_n383 = k_b71;
    const char *k_n386 = "|";
    const char * k_n387 = k_b70;
    const char *k_n385 = kofun_rt_text_concat(k_n386, k_n387);
    const char *k_n388 = "|";
    const char *k_n384 = kofun_rt_text_concat(k_n385, k_n388);
    int64_t k_n382 = kofun_rt_find(k_n383, k_n384);
    int64_t k_n389 = INT64_C(0);
    bool k_n381 = k_n382 < k_n389;
    if (k_n381) {
        const char *k_n391 = "";
        return k_n391;
    }
    const char *k_n394 = "kf_";
    const char * k_n395 = k_b70;
    const char *k_n393 = kofun_rt_text_concat(k_n394, k_n395);
    return k_n393;
}

static const char *kofun_fn_lower_negation(const char *k_b72, const char *k_b73, const char *k_b74) {
    const char * k_n399 = k_b72;
    const char * k_n398 = kofun_rt_trim(k_n399);
    const char * k_b75 = k_n398;
    const char * k_n402 = k_b75;
    bool k_n401 = kofun_fn_all_digits(k_n402);
    if (kofun_failed) return "";
    if (k_n401) {
        const char * k_n405 = k_b75;
        const char *k_n406 = "9223372036854775807";
        bool k_n404 = kofun_fn_within_bound(k_n405, k_n406);
        if (kofun_failed) return "";
        if (k_n404) {
            const char *k_n409 = "-";
            const char * k_n410 = k_b75;
            const char *k_n408 = kofun_rt_text_concat(k_n409, k_n410);
            return k_n408;
        }
        const char * k_n413 = k_b75;
        const char *k_n414 = "9223372036854775808";
        bool k_n412 = kofun_fn_within_bound(k_n413, k_n414);
        if (kofun_failed) return "";
        if (k_n412) {
            const char *k_n416 = "INT64_MIN";
            return k_n416;
        }
        const char *k_n418 = "";
        return k_n418;
    }
    const char * k_n421 = k_b75;
    const char * k_n422 = k_b73;
    const char * k_n424 = k_b74;
    const char *k_n425 = "u";
    const char *k_n423 = kofun_rt_text_concat(k_n424, k_n425);
    const char * k_n420 = kofun_fn_lower_expression(k_n421, k_n422, k_n423);
    if (kofun_failed) return "";
    const char * k_b76 = k_n420;
    const char * k_n429 = k_b76;
    int64_t k_n428 = kofun_rt_text_len(k_n429);
    int64_t k_n430 = INT64_C(0);
    bool k_n427 = k_n428 == k_n430;
    if (k_n427) {
        const char *k_n432 = "";
        return k_n432;
    }
    const char *k_n435 = "kt_";
    const char * k_n436 = k_b74;
    const char *k_n434 = kofun_rt_text_concat(k_n435, k_n436);
    const char * k_b77 = k_n434;
    const char * k_n445 = k_b76;
    const char * k_n444 = kofun_fn_lowered_statements(k_n445);
    if (kofun_failed) return "";
    const char *k_n446 = "        int64_t ";
    const char *k_n443 = kofun_rt_text_concat(k_n444, k_n446);
    const char * k_n447 = k_b77;
    const char *k_n442 = kofun_rt_text_concat(k_n443, k_n447);
    const char *k_n448 = " = checked_neg(";
    const char *k_n441 = kofun_rt_text_concat(k_n442, k_n448);
    const char * k_n450 = k_b76;
    const char * k_n449 = kofun_fn_lowered_operand(k_n450);
    if (kofun_failed) return "";
    const char *k_n440 = kofun_rt_text_concat(k_n441, k_n449);
    const char *k_n451 = ");\n";
    const char *k_n439 = kofun_rt_text_concat(k_n440, k_n451);
    const char * k_n452 = k_b77;
    const char *k_n438 = kofun_rt_text_concat(k_n439, k_n452);
    return k_n438;
}

static const char *kofun_fn_lower_expression(const char *k_b78, const char *k_b79, const char *k_b80) {
    const char * k_n456 = k_b78;
    const char * k_n455 = kofun_rt_trim(k_n456);
    const char * k_b81 = k_n455;
    const char * k_n460 = k_b81;
    int64_t k_n459 = kofun_rt_text_len(k_n460);
    int64_t k_n461 = INT64_C(0);
    bool k_n458 = k_n459 == k_n461;
    if (k_n458) {
        const char *k_n463 = "";
        return k_n463;
    }
    const char * k_n466 = k_b81;
    const char *k_n467 = "+-";
    int64_t k_n465 = kofun_fn_split_binary(k_n466, k_n467);
    if (kofun_failed) return "";
    int64_t k_b82 = k_n465;
    int64_t k_n470 = k_b82;
    int64_t k_n471 = INT64_C(0);
    bool k_n469 = k_n470 >= k_n471;
    if (k_n469) {
        const char * k_n475 = k_b81;
        int64_t k_n476 = INT64_C(0);
        int64_t k_n477 = k_b82;
        const char * k_n474 = kofun_rt_text_slice(k_n475, k_n476, k_n477);
        const char * k_n478 = k_b79;
        const char * k_n480 = k_b80;
        const char *k_n481 = "l";
        const char *k_n479 = kofun_rt_text_concat(k_n480, k_n481);
        const char * k_n473 = kofun_fn_lower_expression(k_n474, k_n478, k_n479);
        if (kofun_failed) return "";
        const char * k_b83 = k_n473;
        const char * k_n485 = k_b81;
        int64_t k_n487 = k_b82;
        int64_t k_n488 = INT64_C(1);
        int64_t k_n486 = kofun_add(k_n487, k_n488);
        if (kofun_failed) return "";
        const char * k_n490 = k_b81;
        int64_t k_n489 = kofun_rt_text_len(k_n490);
        const char * k_n484 = kofun_rt_text_slice(k_n485, k_n486, k_n489);
        const char * k_n491 = k_b79;
        const char * k_n493 = k_b80;
        const char *k_n494 = "r";
        const char *k_n492 = kofun_rt_text_concat(k_n493, k_n494);
        const char * k_n483 = kofun_fn_lower_expression(k_n484, k_n491, k_n492);
        if (kofun_failed) return "";
        const char * k_b84 = k_n483;
        const char * k_n499 = k_b83;
        int64_t k_n498 = kofun_rt_text_len(k_n499);
        int64_t k_n500 = INT64_C(0);
        bool k_n497 = k_n498 == k_n500;
        bool k_n496 = k_n497;
        if (!k_n496) {
            const char * k_n503 = k_b84;
            int64_t k_n502 = kofun_rt_text_len(k_n503);
            int64_t k_n504 = INT64_C(0);
            bool k_n501 = k_n502 == k_n504;
            k_n496 = k_n501;
        }
        if (k_n496) {
            const char *k_n506 = "";
            return k_n506;
        }
        const char * k_n510 = k_b81;
        int64_t k_n511 = k_b82;
        int64_t k_n513 = k_b82;
        int64_t k_n514 = INT64_C(1);
        int64_t k_n512 = kofun_add(k_n513, k_n514);
        if (kofun_failed) return "";
        const char * k_n509 = kofun_rt_text_slice(k_n510, k_n511, k_n512);
        const char *k_n515 = "+";
        bool k_n508 = kofun_rt_text_equal(k_n509, k_n515);
        if (k_n508) {
            const char * k_n518 = k_b80;
            const char *k_n519 = "checked_add(";
            const char * k_n520 = k_b83;
            const char * k_n521 = k_b84;
            const char * k_n517 = kofun_fn_lower_step(k_n518, k_n519, k_n520, k_n521);
            if (kofun_failed) return "";
            return k_n517;
        }
        const char * k_n524 = k_b80;
        const char *k_n525 = "checked_sub(";
        const char * k_n526 = k_b83;
        const char * k_n527 = k_b84;
        const char * k_n523 = kofun_fn_lower_step(k_n524, k_n525, k_n526, k_n527);
        if (kofun_failed) return "";
        return k_n523;
    }
    const char * k_n530 = k_b81;
    const char *k_n531 = "*%/";
    int64_t k_n529 = kofun_fn_split_binary(k_n530, k_n531);
    if (kofun_failed) return "";
    int64_t k_b85 = k_n529;
    int64_t k_n534 = k_b85;
    int64_t k_n535 = INT64_C(0);
    bool k_n533 = k_n534 >= k_n535;
    if (k_n533) {
        const char * k_n538 = k_b81;
        int64_t k_n539 = k_b85;
        int64_t k_n541 = k_b85;
        int64_t k_n542 = INT64_C(1);
        int64_t k_n540 = kofun_add(k_n541, k_n542);
        if (kofun_failed) return "";
        const char * k_n537 = kofun_rt_text_slice(k_n538, k_n539, k_n540);
        const char * k_b86 = k_n537;
        const char *k_n544 = "checked_mul(";
        const char * k_b87 = k_n544;
        int64_t k_n546 = INT64_C(1);
        int64_t k_b88 = k_n546;
        const char * k_n549 = k_b86;
        const char *k_n550 = "%";
        bool k_n548 = kofun_rt_text_equal(k_n549, k_n550);
        if (k_n548) {
            const char *k_n552 = "floor_mod(";
            k_b87 = k_n552;
        } else {
            const char * k_n555 = k_b86;
            const char *k_n556 = "/";
            bool k_n554 = kofun_rt_text_equal(k_n555, k_n556);
            if (k_n554) {
                int64_t k_n560 = k_b85;
                int64_t k_n561 = INT64_C(2);
                int64_t k_n559 = kofun_add(k_n560, k_n561);
                if (kofun_failed) return "";
                const char * k_n563 = k_b81;
                int64_t k_n562 = kofun_rt_text_len(k_n563);
                bool k_n558 = k_n559 > k_n562;
                if (k_n558) {
                    const char *k_n565 = "";
                    return k_n565;
                }
                const char * k_n570 = k_b81;
                int64_t k_n572 = k_b85;
                int64_t k_n573 = INT64_C(1);
                int64_t k_n571 = kofun_add(k_n572, k_n573);
                if (kofun_failed) return "";
                int64_t k_n575 = k_b85;
                int64_t k_n576 = INT64_C(2);
                int64_t k_n574 = kofun_add(k_n575, k_n576);
                if (kofun_failed) return "";
                const char * k_n569 = kofun_rt_text_slice(k_n570, k_n571, k_n574);
                const char *k_n577 = "/";
                bool k_n568 = kofun_rt_text_equal(k_n569, k_n577);
                bool k_n567 = !k_n568;
                if (k_n567) {
                    const char *k_n579 = "";
                    return k_n579;
                }
                const char *k_n581 = "floor_div(";
                k_b87 = k_n581;
                int64_t k_n583 = INT64_C(2);
                k_b88 = k_n583;
            }
        }
        const char * k_n587 = k_b81;
        int64_t k_n588 = INT64_C(0);
        int64_t k_n589 = k_b85;
        const char * k_n586 = kofun_rt_text_slice(k_n587, k_n588, k_n589);
        const char * k_n590 = k_b79;
        const char * k_n592 = k_b80;
        const char *k_n593 = "l";
        const char *k_n591 = kofun_rt_text_concat(k_n592, k_n593);
        const char * k_n585 = kofun_fn_lower_expression(k_n586, k_n590, k_n591);
        if (kofun_failed) return "";
        const char * k_b89 = k_n585;
        const char * k_n597 = k_b81;
        int64_t k_n599 = k_b85;
        int64_t k_n600 = k_b88;
        int64_t k_n598 = kofun_add(k_n599, k_n600);
        if (kofun_failed) return "";
        const char * k_n602 = k_b81;
        int64_t k_n601 = kofun_rt_text_len(k_n602);
        const char * k_n596 = kofun_rt_text_slice(k_n597, k_n598, k_n601);
        const char * k_n603 = k_b79;
        const char * k_n605 = k_b80;
        const char *k_n606 = "r";
        const char *k_n604 = kofun_rt_text_concat(k_n605, k_n606);
        const char * k_n595 = kofun_fn_lower_expression(k_n596, k_n603, k_n604);
        if (kofun_failed) return "";
        const char * k_b90 = k_n595;
        const char * k_n611 = k_b89;
        int64_t k_n610 = kofun_rt_text_len(k_n611);
        int64_t k_n612 = INT64_C(0);
        bool k_n609 = k_n610 == k_n612;
        bool k_n608 = k_n609;
        if (!k_n608) {
            const char * k_n615 = k_b90;
            int64_t k_n614 = kofun_rt_text_len(k_n615);
            int64_t k_n616 = INT64_C(0);
            bool k_n613 = k_n614 == k_n616;
            k_n608 = k_n613;
        }
        if (k_n608) {
            const char *k_n618 = "";
            return k_n618;
        }
        const char * k_n621 = k_b80;
        const char * k_n622 = k_b87;
        const char * k_n623 = k_b89;
        const char * k_n624 = k_b90;
        const char * k_n620 = kofun_fn_lower_step(k_n621, k_n622, k_n623, k_n624);
        if (kofun_failed) return "";
        return k_n620;
    }
    const char * k_n627 = k_b81;
    const char *k_n628 = "+";
    bool k_n626 = kofun_rt_starts_with(k_n627, k_n628);
    if (k_n626) {
        const char * k_n632 = k_b81;
        int64_t k_n633 = INT64_C(1);
        const char * k_n635 = k_b81;
        int64_t k_n634 = kofun_rt_text_len(k_n635);
        const char * k_n631 = kofun_rt_text_slice(k_n632, k_n633, k_n634);
        const char * k_n636 = k_b79;
        const char * k_n637 = k_b80;
        const char * k_n630 = kofun_fn_lower_expression(k_n631, k_n636, k_n637);
        if (kofun_failed) return "";
        return k_n630;
    }
    const char * k_n640 = k_b81;
    const char *k_n641 = "-";
    bool k_n639 = kofun_rt_starts_with(k_n640, k_n641);
    if (k_n639) {
        const char * k_n645 = k_b81;
        int64_t k_n646 = INT64_C(1);
        const char * k_n648 = k_b81;
        int64_t k_n647 = kofun_rt_text_len(k_n648);
        const char * k_n644 = kofun_rt_text_slice(k_n645, k_n646, k_n647);
        const char * k_n649 = k_b79;
        const char * k_n650 = k_b80;
        const char * k_n643 = kofun_fn_lower_negation(k_n644, k_n649, k_n650);
        if (kofun_failed) return "";
        return k_n643;
    }
    const char * k_n653 = k_b81;
    bool k_n652 = kofun_fn_wraps_whole(k_n653);
    if (kofun_failed) return "";
    if (k_n652) {
        const char * k_n657 = k_b81;
        int64_t k_n658 = INT64_C(1);
        const char * k_n661 = k_b81;
        int64_t k_n660 = kofun_rt_text_len(k_n661);
        int64_t k_n662 = INT64_C(1);
        int64_t k_n659 = kofun_sub(k_n660, k_n662);
        if (kofun_failed) return "";
        const char * k_n656 = kofun_rt_text_slice(k_n657, k_n658, k_n659);
        const char * k_n663 = k_b79;
        const char * k_n664 = k_b80;
        const char * k_n655 = kofun_fn_lower_expression(k_n656, k_n663, k_n664);
        if (kofun_failed) return "";
        return k_n655;
    }
    const char * k_n667 = k_b81;
    const char * k_n668 = k_b79;
    const char * k_n666 = kofun_fn_lower_atom(k_n667, k_n668);
    if (kofun_failed) return "";
    return k_n666;
}

static const char *kofun_fn_print_expression(const char *k_b91) {
    const char *k_n671 = "print(";
    const char * k_b92 = k_n671;
    const char * k_n674 = k_b91;
    const char * k_n675 = k_b92;
    int64_t k_n673 = kofun_rt_find(k_n674, k_n675);
    int64_t k_b93 = k_n673;
    int64_t k_n678 = k_b93;
    int64_t k_n679 = INT64_C(0);
    bool k_n677 = k_n678 < k_n679;
    if (k_n677) {
        const char *k_n681 = "";
        return k_n681;
    }
    int64_t k_n684 = k_b93;
    const char * k_n686 = k_b92;
    int64_t k_n685 = kofun_rt_text_len(k_n686);
    int64_t k_n683 = kofun_add(k_n684, k_n685);
    if (kofun_failed) return "";
    int64_t k_b94 = k_n683;
    const char * k_n689 = k_b91;
    kofun_text_list k_n688 = kofun_rt_chars(k_n689);
    kofun_text_list k_b95 = k_n688;
    int64_t k_n691 = INT64_C(1);
    int64_t k_b96 = k_n691;
    int64_t k_n693 = k_b94;
    int64_t k_b97 = k_n693;
    for (;;) {
        int64_t k_n696 = k_b97;
        kofun_text_list k_n698 = k_b95;
        int64_t k_n697 = kofun_rt_text_list_len(k_n698);
        bool k_n695 = k_n696 < k_n697;
        if (!k_n695) break;
        kofun_text_list k_n701 = k_b95;
        int64_t k_n702 = k_b97;
        const char *k_n700 = kofun_rt_text_list_get(k_n701, k_n702);
        const char * k_b98 = k_n700;
        const char * k_n705 = k_b98;
        const char *k_n706 = "(";
        bool k_n704 = kofun_rt_text_equal(k_n705, k_n706);
        if (k_n704) {
            int64_t k_n709 = k_b96;
            int64_t k_n710 = INT64_C(1);
            int64_t k_n708 = kofun_add(k_n709, k_n710);
            if (kofun_failed) return "";
            k_b96 = k_n708;
        } else {
            const char * k_n713 = k_b98;
            const char *k_n714 = ")";
            bool k_n712 = kofun_rt_text_equal(k_n713, k_n714);
            if (k_n712) {
                int64_t k_n717 = k_b96;
                int64_t k_n718 = INT64_C(1);
                int64_t k_n716 = kofun_sub(k_n717, k_n718);
                if (kofun_failed) return "";
                k_b96 = k_n716;
                int64_t k_n721 = k_b96;
                int64_t k_n722 = INT64_C(0);
                bool k_n720 = k_n721 == k_n722;
                if (k_n720) {
                    const char * k_n726 = k_b91;
                    int64_t k_n727 = k_b94;
                    int64_t k_n728 = k_b97;
                    const char * k_n725 = kofun_rt_text_slice(k_n726, k_n727, k_n728);
                    const char * k_n724 = kofun_rt_trim(k_n725);
                    return k_n724;
                }
            }
        }
        int64_t k_n731 = k_b97;
        int64_t k_n732 = INT64_C(1);
        int64_t k_n730 = kofun_add(k_n731, k_n732);
        if (kofun_failed) return "";
        k_b97 = k_n730;
    }
    const char *k_n734 = "";
    return k_n734;
}

static const char *kofun_fn_binding_name(const char *k_b99) {
    const char * k_n738 = k_b99;
    const char *k_n739 = "=";
    int64_t k_n737 = kofun_rt_find(k_n738, k_n739);
    int64_t k_b100 = k_n737;
    int64_t k_n742 = k_b100;
    int64_t k_n743 = INT64_C(0);
    bool k_n741 = k_n742 < k_n743;
    if (k_n741) {
        const char *k_n745 = "";
        return k_n745;
    }
    const char * k_n749 = k_b99;
    int64_t k_n750 = INT64_C(4);
    int64_t k_n751 = k_b100;
    const char * k_n748 = kofun_rt_text_slice(k_n749, k_n750, k_n751);
    const char * k_n747 = kofun_rt_trim(k_n748);
    const char * k_b101 = k_n747;
    const char * k_n754 = k_b101;
    const char *k_n755 = ":";
    int64_t k_n753 = kofun_rt_find(k_n754, k_n755);
    int64_t k_b102 = k_n753;
    int64_t k_n758 = k_b102;
    int64_t k_n759 = INT64_C(0);
    bool k_n757 = k_n758 >= k_n759;
    if (k_n757) {
        const char * k_n763 = k_b101;
        int64_t k_n764 = INT64_C(0);
        int64_t k_n765 = k_b102;
        const char * k_n762 = kofun_rt_text_slice(k_n763, k_n764, k_n765);
        const char * k_n761 = kofun_rt_trim(k_n762);
        return k_n761;
    }
    const char * k_n767 = k_b101;
    return k_n767;
}

static const char *kofun_fn_binding_expression(const char *k_b103) {
    const char * k_n771 = k_b103;
    const char *k_n772 = "=";
    int64_t k_n770 = kofun_rt_find(k_n771, k_n772);
    int64_t k_b104 = k_n770;
    int64_t k_n775 = k_b104;
    int64_t k_n776 = INT64_C(0);
    bool k_n774 = k_n775 < k_n776;
    if (k_n774) {
        const char *k_n778 = "";
        return k_n778;
    }
    const char * k_n782 = k_b103;
    int64_t k_n784 = k_b104;
    int64_t k_n785 = INT64_C(1);
    int64_t k_n783 = kofun_add(k_n784, k_n785);
    if (kofun_failed) return "";
    const char * k_n787 = k_b103;
    int64_t k_n786 = kofun_rt_text_len(k_n787);
    const char * k_n781 = kofun_rt_text_slice(k_n782, k_n783, k_n786);
    const char * k_n780 = kofun_rt_trim(k_n781);
    return k_n780;
}

static bool kofun_fn_valid_source(const char *k_b105) {
    const char * k_n791 = k_b105;
    kofun_text_list k_n790 = kofun_rt_chars(k_n791);
    kofun_text_list k_b106 = k_n790;
    int64_t k_n793 = INT64_C(0);
    int64_t k_b107 = k_n793;
    int64_t k_n795 = INT64_C(0);
    int64_t k_b108 = k_n795;
    int64_t k_n797 = INT64_C(0);
    int64_t k_b109 = k_n797;
    int64_t k_n799 = INT64_C(0);
    int64_t k_b110 = k_n799;
    const char *k_n801 = "|";
    const char * k_b111 = k_n801;
    int64_t k_n804 = INT64_C(0);
    kofun_text_list k_n806 = k_b106;
    int64_t k_n805 = kofun_rt_text_list_len(k_n806);
    for (int64_t k_b112 = k_n804; k_b112 < k_n805; ++k_b112) {
        kofun_text_list k_n810 = k_b106;
        int64_t k_n811 = k_b112;
        const char *k_n809 = kofun_rt_text_list_get(k_n810, k_n811);
        const char *k_n812 = "\n";
        bool k_n808 = kofun_rt_text_equal(k_n809, k_n812);
        if (k_n808) {
            const char * k_n816 = k_b105;
            int64_t k_n817 = k_b107;
            int64_t k_n818 = k_b112;
            const char * k_n815 = kofun_rt_text_slice(k_n816, k_n817, k_n818);
            const char * k_n814 = kofun_rt_trim(k_n815);
            const char * k_b113 = k_n814;
            const char * k_n823 = k_b113;
            int64_t k_n822 = kofun_rt_text_len(k_n823);
            int64_t k_n824 = INT64_C(0);
            bool k_n821 = k_n822 == k_n824;
            bool k_n820 = k_n821;
            if (!k_n820) {
                const char * k_n826 = k_b113;
                const char *k_n827 = "#";
                bool k_n825 = kofun_rt_starts_with(k_n826, k_n827);
                k_n820 = k_n825;
            }
            if (k_n820) {
            } else {
                const char * k_n830 = k_b113;
                const char *k_n831 = "fn main() {";
                bool k_n829 = kofun_rt_text_equal(k_n830, k_n831);
                if (k_n829) {
                    int64_t k_n835 = k_b109;
                    int64_t k_n836 = INT64_C(0);
                    bool k_n834 = k_n835 != k_n836;
                    bool k_n833 = k_n834;
                    if (!k_n833) {
                        int64_t k_n838 = k_b110;
                        int64_t k_n839 = INT64_C(0);
                        bool k_n837 = k_n838 != k_n839;
                        k_n833 = k_n837;
                    }
                    if (k_n833) {
                        bool k_n841 = false;
                        return k_n841;
                    }
                    int64_t k_n844 = k_b109;
                    int64_t k_n845 = INT64_C(1);
                    int64_t k_n843 = kofun_add(k_n844, k_n845);
                    if (kofun_failed) return false;
                    k_b109 = k_n843;
                    int64_t k_n847 = INT64_C(1);
                    k_b110 = k_n847;
                } else {
                    const char * k_n850 = k_b113;
                    const char *k_n851 = "}";
                    bool k_n849 = kofun_rt_text_equal(k_n850, k_n851);
                    if (k_n849) {
                        int64_t k_n854 = k_b110;
                        int64_t k_n855 = INT64_C(1);
                        bool k_n853 = k_n854 != k_n855;
                        if (k_n853) {
                            bool k_n857 = false;
                            return k_n857;
                        }
                        int64_t k_n859 = INT64_C(0);
                        k_b110 = k_n859;
                    } else {
                        const char * k_n862 = k_b113;
                        const char *k_n863 = "let ";
                        bool k_n861 = kofun_rt_starts_with(k_n862, k_n863);
                        if (k_n861) {
                            int64_t k_n866 = k_b110;
                            int64_t k_n867 = INT64_C(1);
                            bool k_n865 = k_n866 != k_n867;
                            if (k_n865) {
                                bool k_n869 = false;
                                return k_n869;
                            }
                            const char * k_n872 = k_b113;
                            const char * k_n871 = kofun_fn_binding_name(k_n872);
                            if (kofun_failed) return false;
                            const char * k_b114 = k_n871;
                            const char * k_n876 = k_b114;
                            bool k_n875 = kofun_fn_valid_name(k_n876);
                            if (kofun_failed) return false;
                            bool k_n874 = !k_n875;
                            if (k_n874) {
                                bool k_n878 = false;
                                return k_n878;
                            }
                            const char * k_n882 = k_b111;
                            const char *k_n885 = "|";
                            const char * k_n886 = k_b114;
                            const char *k_n884 = kofun_rt_text_concat(k_n885, k_n886);
                            const char *k_n887 = "|";
                            const char *k_n883 = kofun_rt_text_concat(k_n884, k_n887);
                            int64_t k_n881 = kofun_rt_find(k_n882, k_n883);
                            int64_t k_n888 = INT64_C(0);
                            bool k_n880 = k_n881 >= k_n888;
                            if (k_n880) {
                                bool k_n890 = false;
                                return k_n890;
                            }
                            const char * k_n896 = k_b113;
                            const char * k_n895 = kofun_fn_binding_expression(k_n896);
                            if (kofun_failed) return false;
                            const char * k_n897 = k_b111;
                            const char *k_n898 = "x";
                            const char * k_n894 = kofun_fn_lower_expression(k_n895, k_n897, k_n898);
                            if (kofun_failed) return false;
                            int64_t k_n893 = kofun_rt_text_len(k_n894);
                            int64_t k_n899 = INT64_C(0);
                            bool k_n892 = k_n893 == k_n899;
                            if (k_n892) {
                                bool k_n901 = false;
                                return k_n901;
                            }
                            const char * k_n905 = k_b111;
                            const char * k_n906 = k_b114;
                            const char *k_n904 = kofun_rt_text_concat(k_n905, k_n906);
                            const char *k_n907 = "|";
                            const char *k_n903 = kofun_rt_text_concat(k_n904, k_n907);
                            k_b111 = k_n903;
                        } else {
                            const char * k_n910 = k_b113;
                            const char *k_n911 = "print(";
                            bool k_n909 = kofun_rt_starts_with(k_n910, k_n911);
                            if (k_n909) {
                                int64_t k_n914 = k_b110;
                                int64_t k_n915 = INT64_C(1);
                                bool k_n913 = k_n914 != k_n915;
                                if (k_n913) {
                                    bool k_n917 = false;
                                    return k_n917;
                                }
                                const char * k_n920 = k_b113;
                                const char * k_n919 = kofun_fn_print_expression(k_n920);
                                if (kofun_failed) return false;
                                const char * k_b115 = k_n919;
                                const char * k_n925 = k_b115;
                                const char * k_n926 = k_b111;
                                const char *k_n927 = "x";
                                const char * k_n924 = kofun_fn_lower_expression(k_n925, k_n926, k_n927);
                                if (kofun_failed) return false;
                                int64_t k_n923 = kofun_rt_text_len(k_n924);
                                int64_t k_n928 = INT64_C(0);
                                bool k_n922 = k_n923 == k_n928;
                                if (k_n922) {
                                    bool k_n930 = false;
                                    return k_n930;
                                }
                                int64_t k_n933 = k_b108;
                                int64_t k_n934 = INT64_C(1);
                                int64_t k_n932 = kofun_add(k_n933, k_n934);
                                if (kofun_failed) return false;
                                k_b108 = k_n932;
                            } else {
                                bool k_n936 = false;
                                return k_n936;
                            }
                        }
                    }
                }
            }
            int64_t k_n939 = k_b112;
            int64_t k_n940 = INT64_C(1);
            int64_t k_n938 = kofun_add(k_n939, k_n940);
            if (kofun_failed) return false;
            k_b107 = k_n938;
        }
    }
    int64_t k_n945 = k_b109;
    int64_t k_n946 = INT64_C(1);
    bool k_n944 = k_n945 == k_n946;
    bool k_n943 = k_n944;
    if (k_n943) {
        int64_t k_n948 = k_b110;
        int64_t k_n949 = INT64_C(0);
        bool k_n947 = k_n948 == k_n949;
        k_n943 = k_n947;
    }
    bool k_n942 = k_n943;
    if (k_n942) {
        int64_t k_n951 = k_b108;
        int64_t k_n952 = INT64_C(0);
        bool k_n950 = k_n951 > k_n952;
        k_n942 = k_n950;
    }
    return k_n942;
}

static const char *kofun_fn_emit_statements(const char *k_b116) {
    const char * k_n956 = k_b116;
    kofun_text_list k_n955 = kofun_rt_chars(k_n956);
    kofun_text_list k_b117 = k_n955;
    int64_t k_n958 = INT64_C(0);
    int64_t k_b118 = k_n958;
    const char *k_n960 = "";
    const char * k_b119 = k_n960;
    const char *k_n962 = "|";
    const char * k_b120 = k_n962;
    int64_t k_n965 = INT64_C(0);
    kofun_text_list k_n967 = k_b117;
    int64_t k_n966 = kofun_rt_text_list_len(k_n967);
    for (int64_t k_b121 = k_n965; k_b121 < k_n966; ++k_b121) {
        kofun_text_list k_n971 = k_b117;
        int64_t k_n972 = k_b121;
        const char *k_n970 = kofun_rt_text_list_get(k_n971, k_n972);
        const char *k_n973 = "\n";
        bool k_n969 = kofun_rt_text_equal(k_n970, k_n973);
        if (k_n969) {
            const char * k_n977 = k_b116;
            int64_t k_n978 = k_b118;
            int64_t k_n979 = k_b121;
            const char * k_n976 = kofun_rt_text_slice(k_n977, k_n978, k_n979);
            const char * k_n975 = kofun_rt_trim(k_n976);
            const char * k_b122 = k_n975;
            const char * k_n982 = k_b122;
            const char *k_n983 = "let ";
            bool k_n981 = kofun_rt_starts_with(k_n982, k_n983);
            if (k_n981) {
                const char * k_n986 = k_b122;
                const char * k_n985 = kofun_fn_binding_name(k_n986);
                if (kofun_failed) return "";
                const char * k_b123 = k_n985;
                const char * k_n990 = k_b122;
                const char * k_n989 = kofun_fn_binding_expression(k_n990);
                if (kofun_failed) return "";
                const char * k_n991 = k_b120;
                const char *k_n992 = "x";
                const char * k_n988 = kofun_fn_lower_expression(k_n989, k_n991, k_n992);
                if (kofun_failed) return "";
                const char * k_b124 = k_n988;
                const char * k_n1009 = k_b119;
                const char *k_n1010 = "    int64_t kf_";
                const char *k_n1008 = kofun_rt_text_concat(k_n1009, k_n1010);
                const char * k_n1011 = k_b123;
                const char *k_n1007 = kofun_rt_text_concat(k_n1008, k_n1011);
                const char *k_n1012 = ";\n";
                const char *k_n1006 = kofun_rt_text_concat(k_n1007, k_n1012);
                const char *k_n1013 = "    {\n";
                const char *k_n1005 = kofun_rt_text_concat(k_n1006, k_n1013);
                const char * k_n1015 = k_b124;
                const char * k_n1014 = kofun_fn_lowered_statements(k_n1015);
                if (kofun_failed) return "";
                const char *k_n1004 = kofun_rt_text_concat(k_n1005, k_n1014);
                const char *k_n1016 = "        kf_";
                const char *k_n1003 = kofun_rt_text_concat(k_n1004, k_n1016);
                const char * k_n1017 = k_b123;
                const char *k_n1002 = kofun_rt_text_concat(k_n1003, k_n1017);
                const char *k_n1018 = " = ";
                const char *k_n1001 = kofun_rt_text_concat(k_n1002, k_n1018);
                const char * k_n1020 = k_b124;
                const char * k_n1019 = kofun_fn_lowered_operand(k_n1020);
                if (kofun_failed) return "";
                const char *k_n1000 = kofun_rt_text_concat(k_n1001, k_n1019);
                const char *k_n1021 = ";\n";
                const char *k_n999 = kofun_rt_text_concat(k_n1000, k_n1021);
                const char *k_n1022 = "    }\n";
                const char *k_n998 = kofun_rt_text_concat(k_n999, k_n1022);
                const char *k_n1023 = "    if (failed) return 1;\n";
                const char *k_n997 = kofun_rt_text_concat(k_n998, k_n1023);
                const char *k_n1024 = "    (void)kf_";
                const char *k_n996 = kofun_rt_text_concat(k_n997, k_n1024);
                const char * k_n1025 = k_b123;
                const char *k_n995 = kofun_rt_text_concat(k_n996, k_n1025);
                const char *k_n1026 = ";\n";
                const char *k_n994 = kofun_rt_text_concat(k_n995, k_n1026);
                k_b119 = k_n994;
                const char * k_n1030 = k_b120;
                const char * k_n1031 = k_b123;
                const char *k_n1029 = kofun_rt_text_concat(k_n1030, k_n1031);
                const char *k_n1032 = "|";
                const char *k_n1028 = kofun_rt_text_concat(k_n1029, k_n1032);
                k_b120 = k_n1028;
            } else {
                const char * k_n1035 = k_b122;
                const char *k_n1036 = "print(";
                bool k_n1034 = kofun_rt_starts_with(k_n1035, k_n1036);
                if (k_n1034) {
                    const char * k_n1040 = k_b122;
                    const char * k_n1039 = kofun_fn_print_expression(k_n1040);
                    if (kofun_failed) return "";
                    const char * k_n1041 = k_b120;
                    const char *k_n1042 = "x";
                    const char * k_n1038 = kofun_fn_lower_expression(k_n1039, k_n1041, k_n1042);
                    if (kofun_failed) return "";
                    const char * k_b125 = k_n1038;
                    const char * k_n1052 = k_b119;
                    const char *k_n1053 = "    {\n";
                    const char *k_n1051 = kofun_rt_text_concat(k_n1052, k_n1053);
                    const char * k_n1055 = k_b125;
                    const char * k_n1054 = kofun_fn_lowered_statements(k_n1055);
                    if (kofun_failed) return "";
                    const char *k_n1050 = kofun_rt_text_concat(k_n1051, k_n1054);
                    const char *k_n1056 = "        int64_t value = ";
                    const char *k_n1049 = kofun_rt_text_concat(k_n1050, k_n1056);
                    const char * k_n1058 = k_b125;
                    const char * k_n1057 = kofun_fn_lowered_operand(k_n1058);
                    if (kofun_failed) return "";
                    const char *k_n1048 = kofun_rt_text_concat(k_n1049, k_n1057);
                    const char *k_n1059 = ";\n";
                    const char *k_n1047 = kofun_rt_text_concat(k_n1048, k_n1059);
                    const char *k_n1060 = "        if (failed) return 1;\n";
                    const char *k_n1046 = kofun_rt_text_concat(k_n1047, k_n1060);
                    const char *k_n1061 = "        printf(\"%\" PRId64 \"\\n\", value);\n";
                    const char *k_n1045 = kofun_rt_text_concat(k_n1046, k_n1061);
                    const char *k_n1062 = "    }\n";
                    const char *k_n1044 = kofun_rt_text_concat(k_n1045, k_n1062);
                    k_b119 = k_n1044;
                }
            }
            int64_t k_n1065 = k_b121;
            int64_t k_n1066 = INT64_C(1);
            int64_t k_n1064 = kofun_add(k_n1065, k_n1066);
            if (kofun_failed) return "";
            k_b118 = k_n1064;
        }
    }
    const char * k_n1068 = k_b119;
    return k_n1068;
}

static const char *kofun_fn_emit_c(const char *k_b126) {
    const char *k_n1148 = "/* Generated by the Kofun-written Stage 1 seed compiler. */\n";
    const char *k_n1149 = "#include <inttypes.h>\n";
    const char *k_n1147 = kofun_rt_text_concat(k_n1148, k_n1149);
    const char *k_n1150 = "#include <stdbool.h>\n";
    const char *k_n1146 = kofun_rt_text_concat(k_n1147, k_n1150);
    const char *k_n1151 = "#include <stdint.h>\n";
    const char *k_n1145 = kofun_rt_text_concat(k_n1146, k_n1151);
    const char *k_n1152 = "#include <stdio.h>\n\n";
    const char *k_n1144 = kofun_rt_text_concat(k_n1145, k_n1152);
    const char *k_n1153 = "static bool failed;\n\n";
    const char *k_n1143 = kofun_rt_text_concat(k_n1144, k_n1153);
    const char *k_n1154 = "static void runtime_error(const char *message) {\n";
    const char *k_n1142 = kofun_rt_text_concat(k_n1143, k_n1154);
    const char *k_n1155 = "    if (!failed) {\n";
    const char *k_n1141 = kofun_rt_text_concat(k_n1142, k_n1155);
    const char *k_n1156 = "        fputs(message, stderr);\n";
    const char *k_n1140 = kofun_rt_text_concat(k_n1141, k_n1156);
    const char *k_n1157 = "        fputc('\\n', stderr);\n";
    const char *k_n1139 = kofun_rt_text_concat(k_n1140, k_n1157);
    const char *k_n1158 = "    }\n";
    const char *k_n1138 = kofun_rt_text_concat(k_n1139, k_n1158);
    const char *k_n1159 = "    failed = true;\n";
    const char *k_n1137 = kofun_rt_text_concat(k_n1138, k_n1159);
    const char *k_n1160 = "}\n\n";
    const char *k_n1136 = kofun_rt_text_concat(k_n1137, k_n1160);
    const char *k_n1161 = "static int64_t checked_add(int64_t left, int64_t right) {\n";
    const char *k_n1135 = kofun_rt_text_concat(k_n1136, k_n1161);
    const char *k_n1162 = "    int64_t result;\n";
    const char *k_n1134 = kofun_rt_text_concat(k_n1135, k_n1162);
    const char *k_n1163 = "    if (__builtin_add_overflow(left, right, &result)) {\n";
    const char *k_n1133 = kofun_rt_text_concat(k_n1134, k_n1163);
    const char *k_n1164 = "        runtime_error(\"error[R010]: integer overflow in operator `+`\");\n";
    const char *k_n1132 = kofun_rt_text_concat(k_n1133, k_n1164);
    const char *k_n1165 = "        return 0;\n";
    const char *k_n1131 = kofun_rt_text_concat(k_n1132, k_n1165);
    const char *k_n1166 = "    }\n";
    const char *k_n1130 = kofun_rt_text_concat(k_n1131, k_n1166);
    const char *k_n1167 = "    return result;\n";
    const char *k_n1129 = kofun_rt_text_concat(k_n1130, k_n1167);
    const char *k_n1168 = "}\n\n";
    const char *k_n1128 = kofun_rt_text_concat(k_n1129, k_n1168);
    const char *k_n1169 = "static int64_t checked_sub(int64_t left, int64_t right) {\n";
    const char *k_n1127 = kofun_rt_text_concat(k_n1128, k_n1169);
    const char *k_n1170 = "    int64_t result;\n";
    const char *k_n1126 = kofun_rt_text_concat(k_n1127, k_n1170);
    const char *k_n1171 = "    if (__builtin_sub_overflow(left, right, &result)) {\n";
    const char *k_n1125 = kofun_rt_text_concat(k_n1126, k_n1171);
    const char *k_n1172 = "        runtime_error(\"error[R010]: integer overflow in operator `-`\");\n";
    const char *k_n1124 = kofun_rt_text_concat(k_n1125, k_n1172);
    const char *k_n1173 = "        return 0;\n";
    const char *k_n1123 = kofun_rt_text_concat(k_n1124, k_n1173);
    const char *k_n1174 = "    }\n";
    const char *k_n1122 = kofun_rt_text_concat(k_n1123, k_n1174);
    const char *k_n1175 = "    return result;\n";
    const char *k_n1121 = kofun_rt_text_concat(k_n1122, k_n1175);
    const char *k_n1176 = "}\n\n";
    const char *k_n1120 = kofun_rt_text_concat(k_n1121, k_n1176);
    const char *k_n1177 = "static int64_t checked_mul(int64_t left, int64_t right) {\n";
    const char *k_n1119 = kofun_rt_text_concat(k_n1120, k_n1177);
    const char *k_n1178 = "    int64_t result;\n";
    const char *k_n1118 = kofun_rt_text_concat(k_n1119, k_n1178);
    const char *k_n1179 = "    if (__builtin_mul_overflow(left, right, &result)) {\n";
    const char *k_n1117 = kofun_rt_text_concat(k_n1118, k_n1179);
    const char *k_n1180 = "        runtime_error(\"error[R010]: integer overflow in operator `*`\");\n";
    const char *k_n1116 = kofun_rt_text_concat(k_n1117, k_n1180);
    const char *k_n1181 = "        return 0;\n";
    const char *k_n1115 = kofun_rt_text_concat(k_n1116, k_n1181);
    const char *k_n1182 = "    }\n";
    const char *k_n1114 = kofun_rt_text_concat(k_n1115, k_n1182);
    const char *k_n1183 = "    return result;\n";
    const char *k_n1113 = kofun_rt_text_concat(k_n1114, k_n1183);
    const char *k_n1184 = "}\n\n";
    const char *k_n1112 = kofun_rt_text_concat(k_n1113, k_n1184);
    const char *k_n1185 = "static int64_t checked_neg(int64_t value) {\n";
    const char *k_n1111 = kofun_rt_text_concat(k_n1112, k_n1185);
    const char *k_n1186 = "    if (value == INT64_MIN) {\n";
    const char *k_n1110 = kofun_rt_text_concat(k_n1111, k_n1186);
    const char *k_n1187 = "        runtime_error(\"error[R010]: integer overflow in unary operator `-`\");\n";
    const char *k_n1109 = kofun_rt_text_concat(k_n1110, k_n1187);
    const char *k_n1188 = "        return 0;\n";
    const char *k_n1108 = kofun_rt_text_concat(k_n1109, k_n1188);
    const char *k_n1189 = "    }\n";
    const char *k_n1107 = kofun_rt_text_concat(k_n1108, k_n1189);
    const char *k_n1190 = "    return -value;\n";
    const char *k_n1106 = kofun_rt_text_concat(k_n1107, k_n1190);
    const char *k_n1191 = "}\n\n";
    const char *k_n1105 = kofun_rt_text_concat(k_n1106, k_n1191);
    const char *k_n1192 = "static int64_t floor_div(int64_t left, int64_t right) {\n";
    const char *k_n1104 = kofun_rt_text_concat(k_n1105, k_n1192);
    const char *k_n1193 = "    if (right == 0) {\n";
    const char *k_n1103 = kofun_rt_text_concat(k_n1104, k_n1193);
    const char *k_n1194 = "        runtime_error(\"error[R010]: operator `//` failed: division by zero\");\n";
    const char *k_n1102 = kofun_rt_text_concat(k_n1103, k_n1194);
    const char *k_n1195 = "        return 0;\n";
    const char *k_n1101 = kofun_rt_text_concat(k_n1102, k_n1195);
    const char *k_n1196 = "    }\n";
    const char *k_n1100 = kofun_rt_text_concat(k_n1101, k_n1196);
    const char *k_n1197 = "    if (left == INT64_MIN && right == -1) {\n";
    const char *k_n1099 = kofun_rt_text_concat(k_n1100, k_n1197);
    const char *k_n1198 = "        runtime_error(\"error[R010]: integer overflow in operator `//`\");\n";
    const char *k_n1098 = kofun_rt_text_concat(k_n1099, k_n1198);
    const char *k_n1199 = "        return 0;\n";
    const char *k_n1097 = kofun_rt_text_concat(k_n1098, k_n1199);
    const char *k_n1200 = "    }\n";
    const char *k_n1096 = kofun_rt_text_concat(k_n1097, k_n1200);
    const char *k_n1201 = "    int64_t quotient = left / right;\n";
    const char *k_n1095 = kofun_rt_text_concat(k_n1096, k_n1201);
    const char *k_n1202 = "    int64_t remainder = left % right;\n";
    const char *k_n1094 = kofun_rt_text_concat(k_n1095, k_n1202);
    const char *k_n1203 = "    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;\n";
    const char *k_n1093 = kofun_rt_text_concat(k_n1094, k_n1203);
    const char *k_n1204 = "    return quotient;\n";
    const char *k_n1092 = kofun_rt_text_concat(k_n1093, k_n1204);
    const char *k_n1205 = "}\n\n";
    const char *k_n1091 = kofun_rt_text_concat(k_n1092, k_n1205);
    const char *k_n1206 = "static int64_t floor_mod(int64_t left, int64_t right) {\n";
    const char *k_n1090 = kofun_rt_text_concat(k_n1091, k_n1206);
    const char *k_n1207 = "    if (right == 0) {\n";
    const char *k_n1089 = kofun_rt_text_concat(k_n1090, k_n1207);
    const char *k_n1208 = "        runtime_error(\"error[R010]: operator `%` failed: division by zero\");\n";
    const char *k_n1088 = kofun_rt_text_concat(k_n1089, k_n1208);
    const char *k_n1209 = "        return 0;\n";
    const char *k_n1087 = kofun_rt_text_concat(k_n1088, k_n1209);
    const char *k_n1210 = "    }\n";
    const char *k_n1086 = kofun_rt_text_concat(k_n1087, k_n1210);
    const char *k_n1211 = "    if (left == INT64_MIN && right == -1) return 0;\n";
    const char *k_n1085 = kofun_rt_text_concat(k_n1086, k_n1211);
    const char *k_n1212 = "    int64_t remainder = left % right;\n";
    const char *k_n1084 = kofun_rt_text_concat(k_n1085, k_n1212);
    const char *k_n1213 = "    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;\n";
    const char *k_n1083 = kofun_rt_text_concat(k_n1084, k_n1213);
    const char *k_n1214 = "    return remainder;\n";
    const char *k_n1082 = kofun_rt_text_concat(k_n1083, k_n1214);
    const char *k_n1215 = "}\n\n";
    const char *k_n1081 = kofun_rt_text_concat(k_n1082, k_n1215);
    const char *k_n1216 = "int main(void) {\n";
    const char *k_n1080 = kofun_rt_text_concat(k_n1081, k_n1216);
    const char *k_n1217 = "    (void)checked_add;\n";
    const char *k_n1079 = kofun_rt_text_concat(k_n1080, k_n1217);
    const char *k_n1218 = "    (void)checked_sub;\n";
    const char *k_n1078 = kofun_rt_text_concat(k_n1079, k_n1218);
    const char *k_n1219 = "    (void)checked_mul;\n";
    const char *k_n1077 = kofun_rt_text_concat(k_n1078, k_n1219);
    const char *k_n1220 = "    (void)checked_neg;\n";
    const char *k_n1076 = kofun_rt_text_concat(k_n1077, k_n1220);
    const char *k_n1221 = "    (void)floor_div;\n";
    const char *k_n1075 = kofun_rt_text_concat(k_n1076, k_n1221);
    const char *k_n1222 = "    (void)floor_mod;\n";
    const char *k_n1074 = kofun_rt_text_concat(k_n1075, k_n1222);
    const char * k_n1224 = k_b126;
    const char * k_n1223 = kofun_fn_emit_statements(k_n1224);
    if (kofun_failed) return "";
    const char *k_n1073 = kofun_rt_text_concat(k_n1074, k_n1223);
    const char *k_n1225 = "    return 0;\n";
    const char *k_n1072 = kofun_rt_text_concat(k_n1073, k_n1225);
    const char *k_n1226 = "}\n";
    const char *k_n1071 = kofun_rt_text_concat(k_n1072, k_n1226);
    return k_n1071;
}

static bool kofun_fn_compile_file(const char *k_b127, const char *k_b128) {
    const char * k_n1230 = k_b127;
    const char * k_n1229 = kofun_rt_read_text(k_n1230);
    const char * k_b129 = k_n1229;
    const char * k_n1233 = k_b129;
    const char * k_n1232 = kofun_rt_validate_unicode_source(k_n1233);
    const char * k_b130 = k_n1232;
    const char * k_n1237 = k_b130;
    int64_t k_n1236 = kofun_rt_text_len(k_n1237);
    int64_t k_n1238 = INT64_C(0);
    bool k_n1235 = k_n1236 > k_n1238;
    if (k_n1235) {
        const char * k_n1241 = k_b130;
        printf("%s\n", k_n1241);
        bool k_n1243 = false;
        return k_n1243;
    }
    const char * k_n1246 = k_b129;
    const char *k_n1247 = "\n";
    const char *k_n1245 = kofun_rt_text_concat(k_n1246, k_n1247);
    const char * k_b131 = k_n1245;
    const char * k_n1251 = k_b131;
    bool k_n1250 = kofun_fn_valid_source(k_n1251);
    if (kofun_failed) return false;
    bool k_n1249 = !k_n1250;
    if (k_n1249) {
        const char *k_n1254 = "compile error: unsupported Kofun integer Core source";
        printf("%s\n", k_n1254);
        bool k_n1256 = false;
        return k_n1256;
    }
    const char * k_n1259 = k_b128;
    const char * k_n1261 = k_b131;
    const char * k_n1260 = kofun_fn_emit_c(k_n1261);
    if (kofun_failed) return false;
    kofun_rt_write_text(k_n1259, k_n1260);
    const char * k_n1264 = k_b128;
    printf("%s\n", k_n1264);
    bool k_n1266 = true;
    return k_n1266;
}

int main(int argc, char **argv) {
    kofun_runtime_argc = argc > 0 ? argc - 1 : 0;
    kofun_runtime_argv = argc > 0 ? argv + 1 : argv;
    (void)kofun_failed;
    (void)kofun_error;
    (void)kofun_add;
    (void)kofun_sub;
    (void)kofun_mul;
    (void)kofun_neg;
    (void)kofun_floor_div;
    (void)kofun_floor_mod;
    (void)kofun_fn_identifier_char;
    (void)kofun_fn_valid_name;
    (void)kofun_fn_digit_value;
    (void)kofun_fn_all_digits;
    (void)kofun_fn_within_bound;
    (void)kofun_fn_preceded_by_operand;
    (void)kofun_fn_split_binary;
    (void)kofun_fn_wraps_whole;
    (void)kofun_fn_last_newline;
    (void)kofun_fn_lowered_statements;
    (void)kofun_fn_lowered_operand;
    (void)kofun_fn_lower_step;
    (void)kofun_fn_lower_atom;
    (void)kofun_fn_lower_negation;
    (void)kofun_fn_lower_expression;
    (void)kofun_fn_print_expression;
    (void)kofun_fn_binding_name;
    (void)kofun_fn_binding_expression;
    (void)kofun_fn_valid_source;
    (void)kofun_fn_emit_statements;
    (void)kofun_fn_emit_c;
    (void)kofun_fn_compile_file;
    kofun_text_list k_n1269 = kofun_rt_args();
    kofun_text_list k_b132 = k_n1269;
    kofun_text_list k_n1273 = k_b132;
    int64_t k_n1272 = kofun_rt_text_list_len(k_n1273);
    int64_t k_n1274 = INT64_C(2);
    bool k_n1271 = k_n1272 != k_n1274;
    if (k_n1271) {
        const char *k_n1277 = "usage: kofun-stage1 INPUT.kofun OUTPUT.c";
        printf("%s\n", k_n1277);
        return 0;
    }
    kofun_text_list k_n1283 = k_b132;
    int64_t k_n1284 = INT64_C(0);
    const char *k_n1282 = kofun_rt_text_list_get(k_n1283, k_n1284);
    kofun_text_list k_n1286 = k_b132;
    int64_t k_n1287 = INT64_C(1);
    const char *k_n1285 = kofun_rt_text_list_get(k_n1286, k_n1287);
    bool k_n1281 = kofun_fn_compile_file(k_n1282, k_n1285);
    if (kofun_failed) return 1;
    bool k_n1280 = !k_n1281;
    if (k_n1280) {
        kofun_rt_fail();
    }
    return 0;
}

