from __future__ import annotations

import json
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from . import ast
from .c_runtime import runtime_lines
from .typesys import ANY, BOOL, FLOAT, INT, LIST, NULL, TEXT, UNKNOWN, VOID, Type


@dataclass(slots=True)
class BackendFailure(Exception):
    message: str
    span: ast.Span | None = None

    def __str__(self) -> str:
        return self.message


class CBackend:
    """Small, deliberately strict C11 bootstrap backend.

    The reference interpreter supports more language features. This backend
    lowers primitive numerics, booleans, text, a narrow `List[Text]` runtime,
    control flow, recursion, direct calls, and the file/text operations needed
    by the Frost-written Stage 1 compiler seed. Unsupported features fail at
    compile time rather than silently changing semantics.
    """

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.indent = 0
        self.function_returns: dict[str, Type] = {}
        self.function_params: dict[str, list[Type]] = {}

    def emit_program(self, program: ast.Program, source_name: str = "<input>") -> str:
        functions = [node for node in program.declarations if isinstance(node, ast.FunctionDecl)]
        non_functions = [
            node
            for node in program.declarations
            if not isinstance(node, (ast.FunctionDecl, ast.LawDecl))
        ]
        if non_functions:
            raise BackendFailure("the C backend currently requires all executable code inside functions", non_functions[0].span)
        if not any(fn.name == "main" for fn in functions):
            raise BackendFailure("the C backend requires `fn main()`", program.span)

        for fn in functions:
            params: list[Type] = []
            for param in fn.params:
                if param.annotation is None:
                    raise BackendFailure(f"C backend parameter `{param.name}` needs a type annotation", param.span)
                if param.mode != "value":
                    raise BackendFailure("C backend MVP does not yet lower read/edit/take parameters", param.span)
                params.append(self._type_from_ref(param.annotation))
            if fn.return_type is None:
                result = VOID
            else:
                result = self._type_from_ref(fn.return_type)
            self.function_params[fn.name] = params
            self.function_returns[fn.name] = result

        self.lines = [
            "/* Generated by Frost bootstrap compiler. */",
            f"/* Source: {source_name.replace('*/', '* /')} */",
            "#include <stdbool.h>",
            "#include <ctype.h>",
            "#include <inttypes.h>",
            "#include <math.h>",
            "#include <stddef.h>",
            "#include <stdint.h>",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            "",
            *runtime_lines(),
            "",
        ]
        for fn in functions:
            self._line(self._prototype(fn) + ";")
        self._line("")
        for fn in functions:
            self._emit_function(fn)
            self._line("")
        self._line("int main(int argc, char **argv) {")
        self.indent += 1
        self._line("frost_runtime_argc = argc > 0 ? argc - 1 : 0;")
        self._line("frost_runtime_argv = argc > 0 ? argv + 1 : argv;")
        result = self.function_returns["main"]
        if result == VOID:
            self._line(f"{self._function_name('main')}();")
            self._line("return 0;")
        elif result == INT:
            self._line(f"return (int){self._function_name('main')}();")
        else:
            self._line(f"(void){self._function_name('main')}();")
            self._line("return 0;")
        self.indent -= 1
        self._line("}")
        return "\n".join(self.lines) + "\n"

    def _prototype(self, fn: ast.FunctionDecl) -> str:
        result = self._c_type(self.function_returns[fn.name], fn.span)
        params = self.function_params[fn.name]
        rendered = ", ".join(
            f"{self._c_type(param_type, param.span)} {self._identifier(param.name)}"
            for param, param_type in zip(fn.params, params)
        )
        if not rendered:
            rendered = "void"
        return f"static {result} {self._function_name(fn.name)}({rendered})"

    def _emit_function(self, fn: ast.FunctionDecl) -> None:
        self._line(self._prototype(fn) + " {")
        self.indent += 1
        for statement in fn.body.statements:
            self._emit_stmt(statement)
        if self.function_returns[fn.name] == VOID and not self._ends_with_return(fn.body):
            self._line("return;")
        self.indent -= 1
        self._line("}")

    def _emit_stmt(self, node: ast.Stmt) -> None:
        if isinstance(node, ast.LetStmt):
            if node.owned:
                raise BackendFailure("C backend MVP does not yet lower `let own`", node.span)
            value_type = self._expr_type(node.value)
            declared = self._type_from_ref(node.annotation) if node.annotation else value_type
            self._line(f"{self._c_type(declared, node.span)} {self._identifier(node.name)} = {self._expr(node.value)};")
            return
        if isinstance(node, ast.AssignStmt):
            self._line(f"{self._identifier(node.name)} = {self._expr(node.value)};")
            return
        if isinstance(node, ast.ReturnStmt):
            if node.value is None:
                self._line("return;")
            else:
                self._line(f"return {self._expr(node.value)};")
            return
        if isinstance(node, ast.WhileStmt):
            self._line(f"while ({self._expr(node.condition)}) {{")
            self.indent += 1
            for statement in node.body.statements:
                self._emit_stmt(statement)
            self.indent -= 1
            self._line("}")
            return
        if isinstance(node, ast.ForStmt):
            start, end = self._range_bounds(node.iterable)
            name = self._identifier(node.name)
            self._line(f"for (int64_t {name} = {start}; {name} < {end}; ++{name}) {{")
            self.indent += 1
            for statement in node.body.statements:
                self._emit_stmt(statement)
            self.indent -= 1
            self._line("}")
            return
        if isinstance(node, ast.BreakStmt):
            self._line("break;")
            return
        if isinstance(node, ast.ContinueStmt):
            self._line("continue;")
            return
        if isinstance(node, ast.TakeStmt):
            raise BackendFailure("C backend MVP does not yet lower resource ownership", node.span)
        if isinstance(node, ast.ExprStmt):
            if isinstance(node.expr, ast.IfExpr):
                self._emit_if(node.expr)
                return
            if isinstance(node.expr, ast.CallExpr) and self._is_named_call(node.expr, "print"):
                self._emit_print(node.expr)
                return
            self._line(f"(void)({self._expr(node.expr)});")
            return
        if isinstance(node, ast.FunctionDecl):
            raise BackendFailure("nested functions are not supported by the C backend", node.span)
        raise BackendFailure(f"C backend does not support {type(node).__name__}", node.span)

    def _emit_if(self, node: ast.IfExpr, *, as_else_if: bool = False) -> None:
        prefix = "else if" if as_else_if else "if"
        self._line(f"{prefix} ({self._expr(node.condition)}) {{")
        self.indent += 1
        for statement in node.then_branch.statements:
            self._emit_stmt(statement)
        self.indent -= 1
        if node.else_branch is None:
            self._line("}")
            return
        nested = self._single_if(node.else_branch)
        if nested is not None:
            self._line("}", newline=False)
            # Keep canonical C `else if` on one line.
            self.lines[-1] += f" else if ({self._expr(nested.condition)}) {{"
            self.indent += 1
            for statement in nested.then_branch.statements:
                self._emit_stmt(statement)
            self.indent -= 1
            if nested.else_branch is None:
                self._line("}")
            else:
                self._line("} else {")
                self.indent += 1
                for statement in nested.else_branch.statements:
                    self._emit_stmt(statement)
                self.indent -= 1
                self._line("}")
            return
        self._line("} else {")
        self.indent += 1
        for statement in node.else_branch.statements:
            self._emit_stmt(statement)
        self.indent -= 1
        self._line("}")

    def _emit_print(self, call: ast.CallExpr) -> None:
        if len(call.args) != 1:
            raise BackendFailure("C backend `print` expects one argument", call.span)
        arg = call.args[0]
        value = self._expr(arg)
        value_type = self._expr_type(arg)
        if value_type == INT:
            self._line(f'printf("%" PRId64 "\\n", (int64_t)({value}));')
        elif value_type == FLOAT:
            self._line(f'printf("%.17g\\n", (double)({value}));')
        elif value_type == BOOL:
            self._line(f'printf("%s\\n", ({value}) ? "true" : "false");')
        elif value_type == TEXT:
            self._line(f'printf("%s\\n", {value});')
        else:
            raise BackendFailure(f"C backend cannot print {value_type} yet", arg.span)

    def _expr(self, node: ast.Expr) -> str:
        if isinstance(node, ast.Literal):
            if node.kind == "Int":
                return f"INT64_C({node.value})"
            if node.kind == "Float":
                value = repr(float(node.value))
                return value if any(ch in value for ch in ".eE") else value + ".0"
            if node.kind == "Bool":
                return "true" if node.value else "false"
            if node.kind == "Text":
                return json.dumps(node.value, ensure_ascii=True)
            if node.kind == "Null":
                raise BackendFailure("C backend does not lower `null` yet", node.span)
        if isinstance(node, ast.Variable):
            return self._identifier(node.name)
        if isinstance(node, ast.UnaryExpr):
            op = "!" if node.op == "!" else node.op
            return f"({op}{self._expr(node.operand)})"
        if isinstance(node, ast.BinaryExpr):
            if node.op == "**":
                return f"pow((double)({self._expr(node.left)}), (double)({self._expr(node.right)}))"
            if node.op == "..":
                raise BackendFailure("ranges are only valid directly in C-backend for-loops", node.span)
            left = self._expr(node.left)
            right = self._expr(node.right)
            left_type = self._expr_type(node.left)
            right_type = self._expr_type(node.right)
            if node.op == "+" and left_type == right_type == TEXT:
                return f"frost_rt_text_concat({left}, {right})"
            if node.op in {"==", "!="} and left_type == right_type == TEXT:
                equality = f"frost_rt_text_equal({left}, {right})"
                return equality if node.op == "==" else f"(!{equality})"
            op = {"&&": "&&", "||": "||", "//": "/"}.get(node.op, node.op)
            if node.op == "/" and self._expr_type(node) == FLOAT:
                return f"(((double)({left})) / ((double)({right})))"
            return f"(({left}) {op} ({right}))"
        if isinstance(node, ast.CallExpr):
            if isinstance(node.callee, ast.Variable):
                name = node.callee.name
                if name == "print":
                    raise BackendFailure("`print` cannot be used as a value in the C backend", node.span)
                if name in {"sqrt", "sin", "cos", "exp", "log", "abs"}:
                    c_name = "fabs" if name == "abs" and self._expr_type(node.args[0]) == FLOAT else name
                    return f"{c_name}({', '.join(self._expr(arg) for arg in node.args)})"
                builtin = self._builtin_call(node, name)
                if builtin is not None:
                    return builtin
                if name in self.function_returns:
                    return f"{self._function_name(name)}({', '.join(self._expr(arg) for arg in node.args)})"
                raise BackendFailure(f"C backend does not support call to `{name}`", node.span)
            raise BackendFailure("C backend supports only direct function calls", node.span)
        if isinstance(node, ast.IfExpr):
            then_expr = self._single_value(node.then_branch)
            else_expr = self._single_value(node.else_branch) if node.else_branch else None
            if then_expr is None or else_expr is None:
                raise BackendFailure("complex if-expressions must be used as statements in the C backend", node.span)
            return f"(({self._expr(node.condition)}) ? ({self._expr(then_expr)}) : ({self._expr(else_expr)}))"
        if isinstance(node, ast.IndexExpr):
            target_type = self._expr_type(node.target)
            if target_type == LIST(TEXT):
                return f"frost_rt_text_list_get({self._expr(node.target)}, {self._expr(node.index)})"
            if target_type == TEXT:
                return f"frost_rt_text_index({self._expr(node.target)}, {self._expr(node.index)})"
            raise BackendFailure(f"C backend cannot index {target_type} yet", node.span)
        if isinstance(node, (ast.ListLiteral, ast.TupleLiteral, ast.LambdaExpr, ast.MemberExpr, ast.PipeExpr)):
            raise BackendFailure(f"C backend does not support {type(node).__name__} yet", node.span)
        raise BackendFailure(f"C backend expression gap: {type(node).__name__}", node.span)

    def _builtin_call(self, node: ast.CallExpr, name: str) -> str | None:
        args = [self._expr(arg) for arg in node.args]
        if name == "args" and not args:
            return "frost_rt_args()"
        if name == "read_text" and len(args) == 1:
            return f"frost_rt_read_text({args[0]})"
        if name == "write_text" and len(args) == 2:
            return f"frost_rt_write_text({args[0]}, {args[1]})"
        if name == "chars" and len(args) == 1:
            return f"frost_rt_chars({args[0]})"
        if name == "text_slice" and len(args) == 3:
            return f"frost_rt_text_slice({args[0]}, {args[1]}, {args[2]})"
        if name == "trim" and len(args) == 1:
            return f"frost_rt_trim({args[0]})"
        if name == "replace" and len(args) == 3:
            return f"frost_rt_replace({args[0]}, {args[1]}, {args[2]})"
        if name == "starts_with" and len(args) == 2:
            return f"frost_rt_starts_with({args[0]}, {args[1]})"
        if name == "ends_with" and len(args) == 2:
            return f"frost_rt_ends_with({args[0]}, {args[1]})"
        if name == "find" and len(args) == 2:
            return f"frost_rt_find({args[0]}, {args[1]})"
        if name == "is_digit" and len(args) == 1:
            return f"frost_rt_is_digit({args[0]})"
        if name == "is_space" and len(args) == 1:
            return f"frost_rt_is_space({args[0]})"
        if name == "parse_int" and len(args) == 1:
            return f"frost_rt_parse_int({args[0]})"
        if name == "to_text" and len(args) == 1:
            arg_type = self._expr_type(node.args[0])
            if arg_type == TEXT:
                return args[0]
            if arg_type == INT:
                return f"frost_rt_int_to_text({args[0]})"
            if arg_type == BOOL:
                return f"(({args[0]}) ? \"true\" : \"false\")"
            raise BackendFailure(f"C backend cannot convert {arg_type} to Text yet", node.span)
        if name == "len" and len(args) == 1:
            arg_type = self._expr_type(node.args[0])
            if arg_type == TEXT:
                return f"frost_rt_text_len({args[0]})"
            if arg_type == LIST(TEXT):
                return f"frost_rt_text_list_len({args[0]})"
            raise BackendFailure(f"C backend cannot take len of {arg_type} yet", node.span)
        if name == "contains" and len(args) == 2:
            if self._expr_type(node.args[0]) == TEXT and self._expr_type(node.args[1]) == TEXT:
                return f"frost_rt_text_contains({args[0]}, {args[1]})"
            raise BackendFailure("C backend `contains` currently supports Text, Text", node.span)
        return None

    def _range_bounds(self, node: ast.Expr) -> tuple[str, str]:
        if isinstance(node, ast.BinaryExpr) and node.op == "..":
            return self._expr(node.left), self._expr(node.right)
        if isinstance(node, ast.CallExpr) and self._is_named_call(node, "range") and len(node.args) == 2:
            return self._expr(node.args[0]), self._expr(node.args[1])
        raise BackendFailure("C backend for-loops currently require `start .. end` or `range(start, end)`", node.span)

    def _expr_type(self, node: ast.Expr) -> Type:
        value = getattr(node, "inferred_type", None)
        if isinstance(value, Type):
            return value
        if isinstance(node, ast.Literal):
            return {"Int": INT, "Float": FLOAT, "Bool": BOOL, "Text": TEXT, "Null": NULL}[node.kind]
        if isinstance(node, ast.CallExpr) and isinstance(node.callee, ast.Variable):
            return self.function_returns.get(node.callee.name, ANY)
        return ANY

    def _type_from_ref(self, ref: ast.TypeRef | None) -> Type:
        if ref is None:
            return VOID
        mapping = {"Int": INT, "Float": FLOAT, "Bool": BOOL, "Text": TEXT, "String": TEXT, "Void": VOID}
        if ref.optional:
            raise BackendFailure("C backend MVP does not lower optional types", ref.span)
        if ref.name == "List" and len(ref.args) == 1:
            item = self._type_from_ref(ref.args[0])
            if item == TEXT:
                return LIST(TEXT)
            raise BackendFailure(f"C backend MVP lowers only List[Text], found `{ref}`", ref.span)
        result = mapping.get(ref.name)
        if result is None:
            raise BackendFailure(f"C backend MVP does not lower type `{ref}`", ref.span)
        return result

    def _c_type(self, value: Type, span: ast.Span) -> str:
        mapping = {
            INT: "int64_t",
            FLOAT: "double",
            BOOL: "bool",
            TEXT: "const char *",
            LIST(TEXT): "frost_text_list",
            VOID: "void",
        }
        result = mapping.get(value)
        if result is None:
            raise BackendFailure(f"C backend MVP does not lower type {value}", span)
        return result

    @staticmethod
    def _is_named_call(node: ast.CallExpr, name: str) -> bool:
        return isinstance(node.callee, ast.Variable) and node.callee.name == name

    @staticmethod
    def _single_value(block: ast.Block | None) -> ast.Expr | None:
        if block is None or len(block.statements) != 1:
            return None
        statement = block.statements[0]
        if isinstance(statement, ast.ExprStmt):
            return statement.expr
        if isinstance(statement, ast.ReturnStmt):
            return statement.value
        return None

    @staticmethod
    def _single_if(block: ast.Block) -> ast.IfExpr | None:
        if len(block.statements) == 1 and isinstance(block.statements[0], ast.ExprStmt):
            expr = block.statements[0].expr
            return expr if isinstance(expr, ast.IfExpr) else None
        return None

    @staticmethod
    def _ends_with_return(block: ast.Block) -> bool:
        return bool(block.statements) and isinstance(block.statements[-1], ast.ReturnStmt)

    @staticmethod
    def _identifier(name: str) -> str:
        pieces: list[str] = []
        for char in name:
            if char.isascii() and (char.isalnum() or char == "_"):
                pieces.append(char)
            else:
                pieces.append(f"_u{ord(char):04x}")
        value = "".join(pieces) or "_empty"
        if value[0].isdigit():
            value = "_" + value
        c_keywords = {
            "auto", "break", "case", "char", "const", "continue", "default", "do", "double", "else",
            "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long", "register", "restrict",
            "return", "short", "signed", "sizeof", "static", "struct", "switch", "typedef", "union", "unsigned",
            "void", "volatile", "while", "_Alignas", "_Alignof", "_Atomic", "_Bool", "_Complex", "_Generic",
            "_Imaginary", "_Noreturn", "_Static_assert", "_Thread_local",
        }
        return f"fr_{value}" if value in c_keywords else value

    def _function_name(self, name: str) -> str:
        return "frost_fn_" + self._identifier(name)

    def _line(self, text: str, *, newline: bool = True) -> None:
        self.lines.append("    " * self.indent + text)


def find_c_compiler() -> str | None:
    for candidate in ("cc", "clang", "gcc"):
        path = shutil.which(candidate)
        if path:
            return path
    return None


def compile_c(c_source: str, output: Path, *, emit_c: Path | None = None, compiler: str | None = None) -> Path:
    compiler = compiler or find_c_compiler()
    if compiler is None:
        raise BackendFailure("no C compiler found; install `cc`, `clang`, or `gcc`")
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    c_path = emit_c.resolve() if emit_c else output.with_suffix(output.suffix + ".frost.c")
    c_path.parent.mkdir(parents=True, exist_ok=True)
    c_path.write_text(c_source, encoding="utf-8")
    command = [compiler, "-std=c11", "-O3", "-Wall", "-Wextra", "-Werror", str(c_path), "-lm", "-o", str(output)]
    result = subprocess.run(command, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        raise BackendFailure(f"C compiler failed:\n{result.stderr.strip()}")
    if emit_c is None:
        c_path.unlink(missing_ok=True)
    return output
