/*
 * Convert the reproducible freestanding runtime ELF into the checked-in
 * prefix consumed by compiler.c. No scripting language is involved.
 */

#include <errno.h>
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const unsigned char SENTINEL[16] = {
    0x4b, 0x4f, 0x46, 0x55, 0x4e, 0x2d, 0x43, 0x4c,
    0x49, 0x2d, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47,
};

static uint16_t u16(const unsigned char *bytes) {
    return (uint16_t)bytes[0] | (uint16_t)((uint16_t)bytes[1] << 8);
}

static uint32_t u32(const unsigned char *bytes) {
    return (uint32_t)bytes[0] |
        ((uint32_t)bytes[1] << 8) |
        ((uint32_t)bytes[2] << 16) |
        ((uint32_t)bytes[3] << 24);
}

static uint64_t u64(const unsigned char *bytes) {
    return (uint64_t)u32(bytes) | ((uint64_t)u32(bytes + 4) << 32);
}

static void fail(const char *message) {
    fprintf(stderr, "template_to_inc: %s\n", message);
    exit(2);
}

static unsigned char *read_file(const char *path, size_t *length) {
    FILE *file = fopen(path, "rb");
    if (file == NULL) {
        fprintf(stderr, "template_to_inc: cannot read %s: %s\n",
                path, strerror(errno));
        exit(2);
    }
    if (fseek(file, 0, SEEK_END) != 0) fail("cannot seek input");
    long measured = ftell(file);
    if (measured < 0) fail("cannot measure input");
    if (fseek(file, 0, SEEK_SET) != 0) fail("cannot rewind input");
    unsigned char *bytes = malloc((size_t)measured);
    if (bytes == NULL) fail("out of memory");
    if (fread(bytes, 1, (size_t)measured, file) != (size_t)measured) {
        fail("cannot read complete input");
    }
    if (fclose(file) != 0) fail("cannot close input");
    *length = (size_t)measured;
    return bytes;
}

int main(int argc, char **argv) {
    if (argc != 3) fail("usage: template_to_inc INPUT.elf OUTPUT.inc");
    size_t length = 0;
    unsigned char *bytes = read_file(argv[1], &length);
    if (length < 64 ||
        memcmp(bytes, "\177ELF\2\1\1", 7) != 0 ||
        u16(bytes + 18) != 62 ||
        u16(bytes + 54) != 56) {
        fail("input is not a little-endian x86-64 ELF");
    }
    size_t sentinel_offset = SIZE_MAX;
    size_t sentinel_count = 0;
    for (size_t index = 0; index + sizeof(SENTINEL) <= length; ++index) {
        if (memcmp(bytes + index, SENTINEL, sizeof(SENTINEL)) == 0) {
            sentinel_offset = index;
            ++sentinel_count;
        }
    }
    if (sentinel_count != 1) {
        fail("expected exactly one config sentinel in the ELF image");
    }
    uint64_t phoff = u64(bytes + 32);
    uint16_t phnum = u16(bytes + 56);
    size_t config_phdr = SIZE_MAX;
    uint64_t config_address = 0;
    for (uint16_t index = 0; index < phnum; ++index) {
        size_t offset = (size_t)phoff + (size_t)index * 56;
        if (offset + 56 > length) fail("program header is outside input");
        uint64_t file_offset = u64(bytes + offset + 8);
        uint64_t file_size = u64(bytes + offset + 32);
        if ((uint64_t)sentinel_offset >= file_offset &&
            (uint64_t)sentinel_offset + sizeof(SENTINEL) <=
                file_offset + file_size) {
            if (u32(bytes + offset) != 1 || u32(bytes + offset + 4) != 4) {
                fail("config sentinel is not in a read-only PT_LOAD");
            }
            if ((uint64_t)sentinel_offset != file_offset) {
                fail("config sentinel must begin its PT_LOAD");
            }
            config_phdr = offset;
            config_address =
                u64(bytes + offset + 16) +
                ((uint64_t)sentinel_offset - file_offset);
        }
    }
    if (config_phdr == SIZE_MAX) fail("cannot find config PT_LOAD");
    if (sentinel_offset > UINT32_MAX ||
        config_phdr > UINT32_MAX ||
        config_address > UINT32_MAX) {
        fail("template offsets exceed the bounded compiler format");
    }

    /* The emitted application intentionally has no section table. */
    memset(bytes + 40, 0, 8);
    memset(bytes + 58, 0, 6);

    FILE *output = fopen(argv[2], "wb");
    if (output == NULL) fail("cannot create output");
    fprintf(output,
            "/* Generated by template_to_inc.c; do not edit. */\n"
            "#define CLI_CONFIG_FILE_OFFSET %" PRIu32 "U\n"
            "#define CLI_CONFIG_ADDRESS %" PRIu32 "U\n"
            "#define CLI_CONFIG_PHDR_OFFSET %" PRIu32 "U\n"
            "static const unsigned char CLI_RUNTIME_PREFIX[] = {\n",
            (uint32_t)sentinel_offset,
            (uint32_t)config_address,
            (uint32_t)config_phdr);
    for (size_t index = 0; index < sentinel_offset; ++index) {
        if (index % 12 == 0) fputs("    ", output);
        fprintf(output, "0x%02x,", bytes[index]);
        if (index % 12 == 11 || index + 1 == sentinel_offset) {
            fputc('\n', output);
        } else {
            fputc(' ', output);
        }
    }
    fputs("};\n", output);
    if (fclose(output) != 0) fail("cannot close output");
    free(bytes);
    return 0;
}
