/* Generated by kofun-stage2 --lower-selfhost-c11. */
/* Source: bootstrap/selfhost/c11/accept_lists.kofun 43ac98ee0fd78e115935be4b2d4ef04b53f484ca444cadc15812fef84b92c914 */

#include <ctype.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "kofun_unicode.c"

typedef struct {
    int64_t len;
    const char **items;
} kofun_text_list;

static bool kofun_failed;

static void kofun_error(const char *message) {
    if (!kofun_failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    kofun_failed = true;
}

static int64_t kofun_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t kofun_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t kofun_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t kofun_neg(int64_t value) {
    if (value == INT64_MIN) {
        kofun_error(
            "error[R010]: integer overflow in unary operator `-`"
        );
        return 0;
    }
    return -value;
}

static int64_t kofun_floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        kofun_error(
            "error[R010]: operator `//` failed: division by zero"
        );
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        kofun_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) {
        --quotient;
    }
    return quotient;
}

static int64_t kofun_floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        kofun_error(
            "error[R010]: operator `%` failed: division by zero"
        );
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        return 0;
    }
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) {
        remainder += right;
    }
    return remainder;
}

void kofun_rt_panic(const char *message) {
    fprintf(stderr, "Kofun runtime error: %s\n", message);
    exit(1);
}

void *kofun_rt_alloc(size_t size) {
    void *value = malloc(size == 0 ? 1 : size);
    if (value == NULL) {
        kofun_rt_panic("out of memory");
    }
    return value;
}

char *kofun_rt_copy_n(const char *value, size_t length) {
    char *result = (char *)kofun_rt_alloc(length + 1);
    if (length > 0) {
        memcpy(result, value, length);
    }
    result[length] = '\0';
    return result;
}

char *kofun_rt_text_concat(const char *left, const char *right) {
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    char *result = (char *)kofun_rt_alloc(left_len + right_len + 1);
    memcpy(result, left, left_len);
    memcpy(result + left_len, right, right_len + 1);
    return result;
}

bool kofun_rt_text_equal(const char *left, const char *right) {
    return strcmp(left, right) == 0;
}

int64_t kofun_rt_text_len(const char *value) {
    return (int64_t)strlen(value);
}

int64_t kofun_rt_text_list_len(kofun_text_list values) {
    return values.len;
}

kofun_text_list kofun_rt_chars(const char *value) {
    size_t length = strlen(value);
    const char **items = (const char **)kofun_rt_alloc(
        sizeof(char *) * (length == 0 ? 1 : length)
    );
    for (size_t index = 0; index < length; ++index) {
        items[index] = kofun_rt_copy_n(value + index, 1);
    }
    kofun_text_list result;
    result.len = (int64_t)length;
    result.items = items;
    return result;
}

const char *kofun_rt_text_list_get(kofun_text_list values, int64_t index) {
    if (index < 0 || index >= values.len) {
        kofun_rt_panic("List[Text] index out of bounds");
    }
    return values.items[index];
}

bool kofun_rt_text_contains(const char *value, const char *needle) {
    return strstr(value, needle) != NULL;
}

int64_t kofun_rt_find(const char *value, const char *needle) {
    const char *found = strstr(value, needle);
    return found == NULL ? INT64_C(-1) : (int64_t)(found - value);
}

char *kofun_rt_text_slice(const char *value, int64_t start, int64_t end) {
    int64_t length = (int64_t)strlen(value);
    if (start < 0) start = 0;
    if (end < start) end = start;
    if (start > length) start = length;
    if (end > length) end = length;
    return kofun_rt_copy_n(value + start, (size_t)(end - start));
}

char *kofun_rt_trim(const char *value) {
    const unsigned char *start = (const unsigned char *)value;
    while (*start != '\0' && isspace(*start)) {
        ++start;
    }
    const unsigned char *end =
        (const unsigned char *)value + strlen(value);
    while (end > start && isspace(end[-1])) {
        --end;
    }
    return kofun_rt_copy_n((const char *)start, (size_t)(end - start));
}

char *kofun_rt_replace(
    const char *value,
    const char *old,
    const char *replacement
) {
    size_t old_len = strlen(old);
    if (old_len == 0) {
        return kofun_rt_copy_n(value, strlen(value));
    }
    size_t replacement_len = strlen(replacement);
    size_t count = 0;
    const char *cursor = value;
    while ((cursor = strstr(cursor, old)) != NULL) {
        ++count;
        cursor += old_len;
    }
    size_t value_len = strlen(value);
    size_t result_len;
    if (replacement_len >= old_len) {
        result_len = value_len + count * (replacement_len - old_len);
    } else {
        result_len = value_len - count * (old_len - replacement_len);
    }
    char *result = (char *)kofun_rt_alloc(result_len + 1);
    char *out = result;
    cursor = value;
    const char *match;
    while ((match = strstr(cursor, old)) != NULL) {
        size_t prefix = (size_t)(match - cursor);
        memcpy(out, cursor, prefix);
        out += prefix;
        memcpy(out, replacement, replacement_len);
        out += replacement_len;
        cursor = match + old_len;
    }
    strcpy(out, cursor);
    return result;
}

bool kofun_rt_starts_with(const char *value, const char *prefix) {
    size_t prefix_len = strlen(prefix);
    return strncmp(value, prefix, prefix_len) == 0;
}

bool kofun_rt_is_digit(const char *value) {
    return value[0] != '\0' && value[1] == '\0' &&
        isdigit((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_space(const char *value) {
    return value[0] != '\0' && value[1] == '\0' &&
        isspace((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_xid_continue(const char *value) {
    uint32_t codepoint = 0;
    size_t width = 0;
    size_t length = strlen(value);
    if (!kofun_unicode_decode(
            (const uint8_t *)value,
            length,
            0,
            &codepoint,
            &width)) {
        return false;
    }
    return kofun_unicode_is_xid_continue(codepoint);
}

const char *kofun_rt_validate_unicode_source(const char *value) {
    KofunUnicodeError unicode_error;
    if (kofun_unicode_validate_source(
            (const uint8_t *)value,
            strlen(value),
            &unicode_error)) {
        return "";
    }
    char message[1024];
    kofun_unicode_format_error(
        &unicode_error,
        getenv("KOFUN_DIAGNOSTIC_LOCALE"),
        message,
        sizeof(message)
    );
    return kofun_rt_copy_n(message, strlen(message));
}

int main(void) {
    (void)kofun_failed;
    (void)kofun_error;
    (void)kofun_add;
    (void)kofun_sub;
    (void)kofun_mul;
    (void)kofun_neg;
    (void)kofun_floor_div;
    (void)kofun_floor_mod;
    const char *k_n2 = "k字n";
    const char * k_b1 = k_n2;
    const char * k_n5 = k_b1;
    kofun_text_list k_n4 = kofun_rt_chars(k_n5);
    kofun_text_list k_b2 = k_n4;
    int64_t k_n7 = INT64_C(0);
    int64_t k_b3 = k_n7;
    int64_t k_n10 = INT64_C(0);
    kofun_text_list k_n12 = k_b2;
    int64_t k_n11 = kofun_rt_text_list_len(k_n12);
    for (int64_t k_b4 = k_n10; k_b4 < k_n11; ++k_b4) {
        kofun_text_list k_n18 = k_b2;
        int64_t k_n19 = k_b4;
        const char *k_n17 = kofun_rt_text_list_get(k_n18, k_n19);
        bool k_n16 = kofun_rt_is_digit(k_n17);
        bool k_n15 = !k_n16;
        bool k_n14 = k_n15;
        if (k_n14) {
            kofun_text_list k_n23 = k_b2;
            int64_t k_n24 = k_b4;
            const char *k_n22 = kofun_rt_text_list_get(k_n23, k_n24);
            bool k_n21 = kofun_rt_is_xid_continue(k_n22);
            bool k_n20 = !k_n21;
            k_n14 = k_n20;
        }
        if (k_n14) {
            int64_t k_n27 = k_b3;
            int64_t k_n28 = INT64_C(1);
            int64_t k_n26 = kofun_add(k_n27, k_n28);
            if (kofun_failed) return 1;
            k_b3 = k_n26;
        }
    }
    kofun_text_list k_n31 = k_b2;
    int64_t k_n32 = INT64_C(0);
    const char *k_n30 = kofun_rt_text_list_get(k_n31, k_n32);
    const char * k_b5 = k_n30;
    kofun_text_list k_n35 = k_b2;
    kofun_text_list k_n38 = k_b2;
    int64_t k_n37 = kofun_rt_text_list_len(k_n38);
    int64_t k_n39 = INT64_C(1);
    int64_t k_n36 = kofun_sub(k_n37, k_n39);
    if (kofun_failed) return 1;
    const char *k_n34 = kofun_rt_text_list_get(k_n35, k_n36);
    const char * k_b6 = k_n34;
    const char * k_n44 = k_b5;
    const char *k_n45 = "k";
    bool k_n43 = kofun_rt_text_equal(k_n44, k_n45);
    bool k_n42 = k_n43;
    if (k_n42) {
        const char * k_n47 = k_b6;
        const char *k_n48 = "n";
        bool k_n46 = kofun_rt_text_equal(k_n47, k_n48);
        k_n42 = k_n46;
    }
    bool k_n41 = k_n42;
    if (k_n41) {
        kofun_text_list k_n51 = k_b2;
        int64_t k_n50 = kofun_rt_text_list_len(k_n51);
        int64_t k_n52 = INT64_C(5);
        bool k_n49 = k_n50 == k_n52;
        k_n41 = k_n49;
    }
    if (k_n41) {
        int64_t k_n54 = k_b3;
        return (int)k_n54;
    }
    int64_t k_n56 = INT64_C(90);
    return (int)k_n56;
}

