/* Generated by kofun-stage2 --lower-selfhost-c11. */
/* Source: bootstrap/selfhost/c11/accept_text_pipeline.kofun 72a947eef3ab9f0ce84410b39be390b5b8ce519427df6e0aca974484590f87c1 */

#include <ctype.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "kofun_unicode.c"

typedef struct {
    int64_t len;
    const char **items;
} kofun_text_list;

int kofun_runtime_argc = 0;
char **kofun_runtime_argv = NULL;

static bool kofun_failed;

static void kofun_error(const char *message) {
    if (!kofun_failed) {
        fputs(message, stderr);
        fputc('\n', stderr);
    }
    kofun_failed = true;
}

static int64_t kofun_add(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_add_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `+`");
        return 0;
    }
    return result;
}

static int64_t kofun_sub(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_sub_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `-`");
        return 0;
    }
    return result;
}

static int64_t kofun_mul(int64_t left, int64_t right) {
    int64_t result;
    if (__builtin_mul_overflow(left, right, &result)) {
        kofun_error("error[R010]: integer overflow in operator `*`");
        return 0;
    }
    return result;
}

static int64_t kofun_neg(int64_t value) {
    if (value == INT64_MIN) {
        kofun_error(
            "error[R010]: integer overflow in unary operator `-`"
        );
        return 0;
    }
    return -value;
}

static int64_t kofun_floor_div(int64_t left, int64_t right) {
    if (right == 0) {
        kofun_error(
            "error[R010]: operator `//` failed: division by zero"
        );
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        kofun_error("error[R010]: integer overflow in operator `//`");
        return 0;
    }
    int64_t quotient = left / right;
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) {
        --quotient;
    }
    return quotient;
}

static int64_t kofun_floor_mod(int64_t left, int64_t right) {
    if (right == 0) {
        kofun_error(
            "error[R010]: operator `%` failed: division by zero"
        );
        return 0;
    }
    if (left == INT64_MIN && right == -1) {
        return 0;
    }
    int64_t remainder = left % right;
    if (remainder != 0 && ((remainder < 0) != (right < 0))) {
        remainder += right;
    }
    return remainder;
}

void kofun_rt_panic(const char *message) {
    fprintf(stderr, "Kofun runtime error: %s\n", message);
    exit(1);
}

void *kofun_rt_alloc(size_t size) {
    void *value = malloc(size == 0 ? 1 : size);
    if (value == NULL) {
        kofun_rt_panic("out of memory");
    }
    return value;
}

char *kofun_rt_copy_n(const char *value, size_t length) {
    char *result = (char *)kofun_rt_alloc(length + 1);
    if (length > 0) {
        memcpy(result, value, length);
    }
    result[length] = '\0';
    return result;
}

char *kofun_rt_text_concat(const char *left, const char *right) {
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    char *result = (char *)kofun_rt_alloc(left_len + right_len + 1);
    memcpy(result, left, left_len);
    memcpy(result + left_len, right, right_len + 1);
    return result;
}

bool kofun_rt_text_equal(const char *left, const char *right) {
    return strcmp(left, right) == 0;
}

int64_t kofun_rt_text_len(const char *value) {
    return (int64_t)strlen(value);
}

int64_t kofun_rt_text_list_len(kofun_text_list values) {
    return values.len;
}

kofun_text_list kofun_rt_args(void) {
    kofun_text_list result;
    result.len = (int64_t)kofun_runtime_argc;
    result.items = (const char **)kofun_runtime_argv;
    return result;
}

kofun_text_list kofun_rt_chars(const char *value) {
    size_t length = strlen(value);
    const char **items = (const char **)kofun_rt_alloc(
        sizeof(char *) * (length == 0 ? 1 : length)
    );
    for (size_t index = 0; index < length; ++index) {
        items[index] = kofun_rt_copy_n(value + index, 1);
    }
    kofun_text_list result;
    result.len = (int64_t)length;
    result.items = items;
    return result;
}

const char *kofun_rt_text_list_get(kofun_text_list values, int64_t index) {
    if (index < 0 || index >= values.len) {
        kofun_rt_panic("List[Text] index out of bounds");
    }
    return values.items[index];
}

bool kofun_rt_text_contains(const char *value, const char *needle) {
    return strstr(value, needle) != NULL;
}

int64_t kofun_rt_find(const char *value, const char *needle) {
    const char *found = strstr(value, needle);
    return found == NULL ? INT64_C(-1) : (int64_t)(found - value);
}

char *kofun_rt_text_slice(const char *value, int64_t start, int64_t end) {
    int64_t length = (int64_t)strlen(value);
    if (start < 0) start = 0;
    if (end < start) end = start;
    if (start > length) start = length;
    if (end > length) end = length;
    return kofun_rt_copy_n(value + start, (size_t)(end - start));
}

char *kofun_rt_trim(const char *value) {
    const unsigned char *start = (const unsigned char *)value;
    while (*start != '\0' && isspace(*start)) {
        ++start;
    }
    const unsigned char *end =
        (const unsigned char *)value + strlen(value);
    while (end > start && isspace(end[-1])) {
        --end;
    }
    return kofun_rt_copy_n((const char *)start, (size_t)(end - start));
}

char *kofun_rt_replace(
    const char *value,
    const char *old,
    const char *replacement
) {
    size_t old_len = strlen(old);
    if (old_len == 0) {
        return kofun_rt_copy_n(value, strlen(value));
    }
    size_t replacement_len = strlen(replacement);
    size_t count = 0;
    const char *cursor = value;
    while ((cursor = strstr(cursor, old)) != NULL) {
        ++count;
        cursor += old_len;
    }
    size_t value_len = strlen(value);
    size_t result_len;
    if (replacement_len >= old_len) {
        result_len = value_len + count * (replacement_len - old_len);
    } else {
        result_len = value_len - count * (old_len - replacement_len);
    }
    char *result = (char *)kofun_rt_alloc(result_len + 1);
    char *out = result;
    cursor = value;
    const char *match;
    while ((match = strstr(cursor, old)) != NULL) {
        size_t prefix = (size_t)(match - cursor);
        memcpy(out, cursor, prefix);
        out += prefix;
        memcpy(out, replacement, replacement_len);
        out += replacement_len;
        cursor = match + old_len;
    }
    strcpy(out, cursor);
    return result;
}

bool kofun_rt_starts_with(const char *value, const char *prefix) {
    size_t prefix_len = strlen(prefix);
    return strncmp(value, prefix, prefix_len) == 0;
}

bool kofun_rt_is_digit(const char *value) {
    return value[0] != '\0' && value[1] == '\0' &&
        isdigit((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_space(const char *value) {
    return value[0] != '\0' && value[1] == '\0' &&
        isspace((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_xid_continue(const char *value) {
    uint32_t codepoint = 0;
    size_t width = 0;
    size_t length = strlen(value);
    if (!kofun_unicode_decode(
            (const uint8_t *)value,
            length,
            0,
            &codepoint,
            &width)) {
        return false;
    }
    return kofun_unicode_is_xid_continue(codepoint);
}

const char *kofun_rt_validate_unicode_source(const char *value) {
    KofunUnicodeError unicode_error;
    if (kofun_unicode_validate_source(
            (const uint8_t *)value,
            strlen(value),
            &unicode_error)) {
        return "";
    }
    char message[1024];
    kofun_unicode_format_error(
        &unicode_error,
        getenv("KOFUN_DIAGNOSTIC_LOCALE"),
        message,
        sizeof(message)
    );
    return kofun_rt_copy_n(message, strlen(message));
}

char *kofun_rt_read_text(const char *path) {
    FILE *file = fopen(path, "rb");
    if (file == NULL) {
        kofun_rt_panic("cannot open input file");
    }
    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        kofun_rt_panic("cannot seek input file");
    }
    long size = ftell(file);
    if (size < 0) {
        fclose(file);
        kofun_rt_panic("cannot measure input file");
    }
    rewind(file);
    char *result = (char *)kofun_rt_alloc((size_t)size + 1);
    size_t read = fread(result, 1, (size_t)size, file);
    if (read != (size_t)size && ferror(file)) {
        fclose(file);
        kofun_rt_panic("cannot read input file");
    }
    result[read] = '\0';
    fclose(file);
    return result;
}

void kofun_rt_write_text(const char *path, const char *value) {
    FILE *file = fopen(path, "wb");
    if (file == NULL) {
        kofun_rt_panic("cannot open output file");
    }
    size_t length = strlen(value);
    if (fwrite(value, 1, length, file) != length) {
        fclose(file);
        kofun_rt_panic("cannot write output file");
    }
    if (fclose(file) != 0) {
        kofun_rt_panic("cannot close output file");
    }
}

static const char *kofun_fn_shout(const char *k_b4, bool k_b5);
static const char *kofun_fn_classify(int64_t k_b6);
static void kofun_fn_note(bool k_b7);

static const char *kofun_fn_shout(const char *k_b4, bool k_b5) {
    bool k_n2 = k_b5;
    if (k_n2) {
        const char * k_n5 = k_b4;
        const char *k_n6 = "!";
        const char *k_n4 = kofun_rt_text_concat(k_n5, k_n6);
        return k_n4;
    }
    const char * k_n8 = k_b4;
    return k_n8;
}

static const char *kofun_fn_classify(int64_t k_b6) {
    int64_t k_n12 = k_b6;
    int64_t k_n13 = INT64_C(0);
    bool k_n11 = k_n12 < k_n13;
    if (k_n11) {
        const char *k_n15 = "negative";
        return k_n15;
    } else {
        int64_t k_n18 = k_b6;
        int64_t k_n19 = INT64_C(0);
        bool k_n17 = k_n18 == k_n19;
        if (k_n17) {
            const char *k_n21 = "zero";
            return k_n21;
        } else {
            const char *k_n23 = "positive";
            return k_n23;
        }
    }
    const char *k_n25 = "unreachable";
    return k_n25;
}

static void kofun_fn_note(bool k_b7) {
    bool k_n28 = k_b7;
    if (k_n28) {
        return;
    }
    return;
}

int main(int argc, char **argv) {
    kofun_runtime_argc = argc > 0 ? argc - 1 : 0;
    kofun_runtime_argv = argc > 0 ? argv + 1 : argv;
    (void)kofun_failed;
    (void)kofun_error;
    (void)kofun_add;
    (void)kofun_sub;
    (void)kofun_mul;
    (void)kofun_neg;
    (void)kofun_floor_div;
    (void)kofun_floor_mod;
    (void)kofun_fn_shout;
    (void)kofun_fn_classify;
    (void)kofun_fn_note;
    const char *k_n35 = " ";
    bool k_n34 = kofun_rt_is_space(k_n35);
    kofun_fn_note(k_n34);
    if (kofun_failed) return 1;
    const char *k_n39 = "  kofun  ";
    const char * k_n38 = kofun_rt_trim(k_n39);
    bool k_n40 = true;
    const char * k_n37 = kofun_fn_shout(k_n38, k_n40);
    if (kofun_failed) return 1;
    const char * k_b8 = k_n37;
    const char * k_n43 = k_b8;
    int64_t k_n44 = INT64_C(0);
    const char * k_n47 = k_b8;
    int64_t k_n46 = kofun_rt_text_len(k_n47);
    int64_t k_n48 = INT64_C(1);
    int64_t k_n45 = kofun_sub(k_n46, k_n48);
    if (kofun_failed) return 1;
    const char * k_n42 = kofun_rt_text_slice(k_n43, k_n44, k_n45);
    const char * k_b9 = k_n42;
    const char *k_n51 = "a|b\nc";
    const char *k_n52 = "|";
    const char *k_n53 = "-";
    const char * k_n50 = kofun_rt_replace(k_n51, k_n52, k_n53);
    const char * k_b10 = k_n50;
    const char * k_n58 = k_b8;
    const char *k_n59 = "kofun";
    bool k_n57 = kofun_rt_text_contains(k_n58, k_n59);
    bool k_n56 = k_n57;
    if (k_n56) {
        const char * k_n61 = k_b8;
        const char *k_n62 = "ko";
        bool k_n60 = kofun_rt_starts_with(k_n61, k_n62);
        k_n56 = k_n60;
    }
    bool k_n55 = k_n56;
    if (!k_n55) {
        const char *k_n65 = "x";
        bool k_n64 = kofun_rt_is_digit(k_n65);
        bool k_n63 = !k_n64;
        k_n55 = k_n63;
    }
    if (k_n55) {
        const char * k_n70 = k_b8;
        const char *k_n71 = "fun";
        int64_t k_n69 = kofun_rt_find(k_n70, k_n71);
        int64_t k_n72 = INT64_C(2);
        int64_t k_n68 = kofun_sub(k_n69, k_n72);
        if (kofun_failed) return 1;
        const char * k_n67 = kofun_fn_classify(k_n68);
        if (kofun_failed) return 1;
        const char * k_b11 = k_n67;
        const char * k_n75 = k_b10;
        const char * k_n74 = kofun_rt_validate_unicode_source(k_n75);
        const char * k_b12 = k_n74;
        const char * k_n79 = k_b12;
        const char *k_n80 = "";
        bool k_n78 = kofun_rt_text_equal(k_n79, k_n80);
        bool k_n77 = k_n78;
        if (k_n77) {
            const char *k_n82 = "k";
            bool k_n81 = kofun_rt_is_xid_continue(k_n82);
            k_n77 = k_n81;
        }
        if (k_n77) {
            const char * k_n88 = k_b11;
            const char * k_n89 = k_b9;
            const char *k_n87 = kofun_rt_text_concat(k_n88, k_n89);
            int64_t k_n86 = kofun_rt_text_len(k_n87);
            const char * k_n91 = k_b8;
            int64_t k_n90 = kofun_rt_text_len(k_n91);
            int64_t k_n85 = kofun_sub(k_n86, k_n90);
            if (kofun_failed) return 1;
            int64_t k_n92 = INT64_C(4);
            int64_t k_n84 = kofun_sub(k_n85, k_n92);
            if (kofun_failed) return 1;
            return (int)k_n84;
        }
    }
    int64_t k_n94 = INT64_C(9);
    return (int)k_n94;
}

