/* Generated by Kofun bootstrap compiler. */
/* Source: bootstrap/stage1/compiler.kofun */
#include <stdbool.h>
#include <ctype.h>
#include <inttypes.h>
#include <math.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../../unicode/kofun_unicode.c"

typedef struct {
    int64_t len;
    const char **items;
} kofun_text_list;

int kofun_runtime_argc = 0;
char **kofun_runtime_argv = NULL;

void kofun_rt_panic(const char *message) {
    fprintf(stderr, "Kofun runtime error: %s\n", message);
    exit(1);
}

void kofun_rt_fail(void) {
    exit(1);
}

void *kofun_rt_alloc(size_t size) {
    void *value = malloc(size == 0 ? 1 : size);
    if (value == NULL) {
        kofun_rt_panic("out of memory");
    }
    return value;
}

char *kofun_rt_copy_n(const char *value, size_t length) {
    char *result = (char *)kofun_rt_alloc(length + 1);
    if (length > 0) {
        memcpy(result, value, length);
    }
    result[length] = '\0';
    return result;
}

char *kofun_rt_text_concat(const char *left, const char *right) {
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    char *result = (char *)kofun_rt_alloc(left_len + right_len + 1);
    memcpy(result, left, left_len);
    memcpy(result + left_len, right, right_len + 1);
    return result;
}

bool kofun_rt_text_equal(const char *left, const char *right) {
    return strcmp(left, right) == 0;
}

int64_t kofun_rt_text_len(const char *value) {
    return (int64_t)strlen(value);
}

int64_t kofun_rt_text_list_len(kofun_text_list values) {
    return values.len;
}

kofun_text_list kofun_rt_args(void) {
    kofun_text_list result;
    result.len = (int64_t)kofun_runtime_argc;
    result.items = (const char **)kofun_runtime_argv;
    return result;
}

kofun_text_list kofun_rt_chars(const char *value) {
    size_t length = strlen(value);
    const char **items = (const char **)kofun_rt_alloc(sizeof(char *) * (length == 0 ? 1 : length));
    for (size_t index = 0; index < length; ++index) {
        items[index] = kofun_rt_copy_n(value + index, 1);
    }
    kofun_text_list result;
    result.len = (int64_t)length;
    result.items = items;
    return result;
}

const char *kofun_rt_text_list_get(kofun_text_list values, int64_t index) {
    if (index < 0 || index >= values.len) {
        kofun_rt_panic("List[Text] index out of bounds");
    }
    return values.items[index];
}

const char *kofun_rt_text_index(const char *value, int64_t index) {
    int64_t length = (int64_t)strlen(value);
    if (index < 0 || index >= length) {
        kofun_rt_panic("Text index out of bounds");
    }
    return kofun_rt_copy_n(value + index, 1);
}

bool kofun_rt_text_contains(const char *value, const char *needle) {
    return strstr(value, needle) != NULL;
}

int64_t kofun_rt_find(const char *value, const char *needle) {
    const char *found = strstr(value, needle);
    return found == NULL ? INT64_C(-1) : (int64_t)(found - value);
}

char *kofun_rt_text_slice(const char *value, int64_t start, int64_t end) {
    int64_t length = (int64_t)strlen(value);
    if (start < 0) start = 0;
    if (end < start) end = start;
    if (start > length) start = length;
    if (end > length) end = length;
    return kofun_rt_copy_n(value + start, (size_t)(end - start));
}

char *kofun_rt_trim(const char *value) {
    const unsigned char *start = (const unsigned char *)value;
    while (*start != '\0' && isspace(*start)) {
        ++start;
    }
    const unsigned char *end = (const unsigned char *)value + strlen(value);
    while (end > start && isspace(end[-1])) {
        --end;
    }
    return kofun_rt_copy_n((const char *)start, (size_t)(end - start));
}

char *kofun_rt_replace(const char *value, const char *old, const char *replacement) {
    size_t old_len = strlen(old);
    if (old_len == 0) {
        return kofun_rt_copy_n(value, strlen(value));
    }
    size_t replacement_len = strlen(replacement);
    size_t count = 0;
    const char *cursor = value;
    while ((cursor = strstr(cursor, old)) != NULL) {
        ++count;
        cursor += old_len;
    }
    size_t value_len = strlen(value);
    size_t result_len;
    if (replacement_len >= old_len) {
        result_len = value_len + count * (replacement_len - old_len);
    } else {
        result_len = value_len - count * (old_len - replacement_len);
    }
    char *result = (char *)kofun_rt_alloc(result_len + 1);
    char *out = result;
    cursor = value;
    const char *match;
    while ((match = strstr(cursor, old)) != NULL) {
        size_t prefix = (size_t)(match - cursor);
        memcpy(out, cursor, prefix);
        out += prefix;
        memcpy(out, replacement, replacement_len);
        out += replacement_len;
        cursor = match + old_len;
    }
    strcpy(out, cursor);
    return result;
}

bool kofun_rt_starts_with(const char *value, const char *prefix) {
    size_t prefix_len = strlen(prefix);
    return strncmp(value, prefix, prefix_len) == 0;
}

bool kofun_rt_ends_with(const char *value, const char *suffix) {
    size_t value_len = strlen(value);
    size_t suffix_len = strlen(suffix);
    return suffix_len <= value_len && strcmp(value + value_len - suffix_len, suffix) == 0;
}

bool kofun_rt_is_digit(const char *value) {
    return value[0] != '\0' && value[1] == '\0' && isdigit((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_space(const char *value) {
    return value[0] != '\0' && value[1] == '\0' && isspace((unsigned char)value[0]) != 0;
}

int64_t kofun_rt_parse_int(const char *value) {
    char *end = NULL;
    long long result = strtoll(value, &end, 10);
    if (end == value || *end != '\0') {
        kofun_rt_panic("invalid integer text");
    }
    return (int64_t)result;
}

char *kofun_rt_int_to_text(int64_t value) {
    char buffer[64];
    int written = snprintf(buffer, sizeof(buffer), "%" PRId64, value);
    if (written < 0) {
        kofun_rt_panic("integer formatting failed");
    }
    return kofun_rt_copy_n(buffer, (size_t)written);
}

char *kofun_rt_read_text(const char *path) {
    FILE *file = fopen(path, "rb");
    if (file == NULL) {
        kofun_rt_panic("cannot open input file");
    }
    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        kofun_rt_panic("cannot seek input file");
    }
    long size = ftell(file);
    if (size < 0) {
        fclose(file);
        kofun_rt_panic("cannot measure input file");
    }
    rewind(file);
    char *result = (char *)kofun_rt_alloc((size_t)size + 1);
    size_t read = fread(result, 1, (size_t)size, file);
    if (read != (size_t)size && ferror(file)) {
        fclose(file);
        kofun_rt_panic("cannot read input file");
    }
    result[read] = '\0';
    fclose(file);
    return result;
}

void kofun_rt_write_text(const char *path, const char *value) {
    FILE *file = fopen(path, "wb");
    if (file == NULL) {
        kofun_rt_panic("cannot open output file");
    }
    size_t length = strlen(value);
    if (fwrite(value, 1, length, file) != length) {
        fclose(file);
        kofun_rt_panic("cannot write output file");
    }
    if (fclose(file) != 0) {
        kofun_rt_panic("cannot close output file");
    }
}

static bool kofun_fn_identifier_char(const char * fr_char);
static bool kofun_fn_valid_name(const char * name);
static int64_t kofun_fn_digit_value(const char * symbol);
static bool kofun_fn_all_digits(const char * value);
static bool kofun_fn_within_bound(const char * digits, const char * bound);
static bool kofun_fn_preceded_by_operand(const char * expression, int64_t index);
static int64_t kofun_fn_split_binary(const char * expression, const char * operators);
static int64_t kofun_fn_split_operators(const char * expression, const char * operators);
static bool kofun_fn_wraps_whole(const char * expression);
static int64_t kofun_fn_postfix_index(const char * expression);
static const char * kofun_fn_call_argument(const char * expression, const char * callee);
static int64_t kofun_fn_last_newline(const char * value);
static const char * kofun_fn_lowered_type(const char * lowered);
static const char * kofun_fn_lowered_value(const char * lowered);
static const char * kofun_fn_lowered_statements(const char * lowered);
static const char * kofun_fn_lowered_operand(const char * lowered);
static const char * kofun_fn_lower_step(const char * path, const char * indent, const char * callee, const char * left, const char * right);
static const char * kofun_fn_lower_comparison(const char * path, const char * indent, const char * operator_text, const char * left, const char * right);
static const char * kofun_fn_lower_logical(const char * path, const char * indent, const char * operator_text, const char * left, const char * right);
static const char * kofun_fn_bound_type(const char * bound, const char * name);
static const char * kofun_fn_lower_atom(const char * atom, const char * bound);
static const char * kofun_fn_lower_negation(const char * operand, const char * bound, const char * path, const char * indent);
static const char * kofun_fn_lower_expression(const char * expression, const char * bound, const char * path, const char * indent);
static const char * kofun_fn_print_expression(const char * line);
static const char * kofun_fn_binding_name(const char * line);
static const char * kofun_fn_binding_expression(const char * line);
static const char * kofun_fn_binding_annotation(const char * line);
static const char * kofun_fn_indentation(int64_t units);
static const char * kofun_fn_statement_indent(int64_t depth);
static const char * kofun_fn_nested_indent(int64_t depth);
static const char * kofun_fn_scope_enter(const char * bound);
static const char * kofun_fn_scope_leave(const char * bound);
static const char * kofun_fn_block_kind(const char * blocks);
static const char * kofun_fn_block_pop(const char * blocks);
static const char * kofun_fn_header_condition(const char * line, const char * keyword);
static const char * kofun_fn_range_header(const char * line);
static const char * kofun_fn_range_name(const char * line);
static const char * kofun_fn_range_bounds(const char * line);
static const char * kofun_fn_range_start(const char * line);
static const char * kofun_fn_range_end(const char * line);
static bool kofun_fn_valid_source(const char * source);
static const char * kofun_fn_emit_statements(const char * source);
static const char * kofun_fn_emit_c(const char * source);
static bool kofun_fn_compile_file(const char * input_path, const char * output_path);
static void kofun_fn_main(void);

static bool kofun_fn_identifier_char(const char * fr_char) {
    unsigned char first = (unsigned char)fr_char[0];
    return first >= UINT8_C(0x80) ||
        kofun_rt_is_digit(fr_char) ||
        kofun_rt_text_contains(
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_",
            fr_char
        );
}

static bool kofun_fn_valid_name(const char * name) {
    kofun_text_list symbols = kofun_rt_chars(name);
    if (((((kofun_rt_text_list_len(symbols)) == (INT64_C(0)))) || (kofun_rt_is_digit(kofun_rt_text_list_get(symbols, INT64_C(0)))))) {
        return false;
    }
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if ((!kofun_fn_identifier_char(kofun_rt_text_list_get(symbols, index)))) {
            return false;
        }
    }
    return true;
}

static int64_t kofun_fn_digit_value(const char * symbol) {
    return kofun_rt_find("0123456789", symbol);
}

static bool kofun_fn_all_digits(const char * value) {
    kofun_text_list symbols = kofun_rt_chars(value);
    if (((kofun_rt_text_list_len(symbols)) == (INT64_C(0)))) {
        return false;
    }
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if ((!kofun_rt_is_digit(kofun_rt_text_list_get(symbols, index)))) {
            return false;
        }
    }
    return true;
}

static bool kofun_fn_within_bound(const char * digits, const char * bound) {
    kofun_text_list symbols = kofun_rt_chars(digits);
    kofun_text_list limit = kofun_rt_chars(bound);
    int64_t start = INT64_C(0);
    while ((((start) + (INT64_C(1))) < (kofun_rt_text_list_len(symbols))) &&
           kofun_rt_text_equal(kofun_rt_text_list_get(symbols, start), "0")) {
        start = ((start) + (INT64_C(1)));
    }
    int64_t significant = ((kofun_rt_text_list_len(symbols)) - (start));
    if (((significant) != (kofun_rt_text_list_len(limit)))) {
        return ((significant) < (kofun_rt_text_list_len(limit)));
    }
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(limit); ++index) {
        int64_t left = kofun_fn_digit_value(
            kofun_rt_text_list_get(symbols, ((start) + (index))));
        int64_t right = kofun_fn_digit_value(kofun_rt_text_list_get(limit, index));
        if (((left) != (right))) {
            return ((left) < (right));
        }
    }
    return true;
}

static bool kofun_fn_preceded_by_operand(const char * expression, int64_t index) {
    kofun_text_list symbols = kofun_rt_chars(expression);
    int64_t cursor = ((index) - (INT64_C(1)));
    while (((cursor) >= (INT64_C(0)))) {
        const char * symbol = kofun_rt_text_list_get(symbols, cursor);
        if ((!kofun_rt_is_space(symbol))) {
            return ((((kofun_rt_text_equal(symbol, ")")) ||
                     (kofun_rt_text_equal(symbol, "]"))) ||
                    (kofun_rt_text_equal(symbol, "\""))) ||
                   (kofun_fn_identifier_char(symbol)));
        }
        cursor = ((cursor) - (INT64_C(1)));
    }
    return false;
}

static int64_t kofun_fn_split_binary(const char * expression, const char * operators) {
    kofun_text_list symbols = kofun_rt_chars(expression);
    int64_t depth = INT64_C(0);
    int64_t found = INT64_C(-1);
    bool quoted = false;
    bool escaped = false;
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        const char * symbol = kofun_rt_text_list_get(symbols, index);
        if (quoted) {
            if (escaped) {
                escaped = false;
            } else if (kofun_rt_text_equal(symbol, "\\")) {
                escaped = true;
            } else if (kofun_rt_text_equal(symbol, "\"")) {
                quoted = false;
            }
        } else if (kofun_rt_text_equal(symbol, "\"")) {
            quoted = true;
        } else if ((kofun_rt_text_equal(symbol, "(")) ||
                   (kofun_rt_text_equal(symbol, "["))) {
            depth = ((depth) + (INT64_C(1)));
        } else if ((kofun_rt_text_equal(symbol, ")")) ||
                   (kofun_rt_text_equal(symbol, "]"))) {
            depth = ((depth) - (INT64_C(1)));
        } else if ((((depth) == (INT64_C(0)))) && (kofun_rt_text_contains(operators, symbol))) {
            if (kofun_fn_preceded_by_operand(expression, index)) {
                found = index;
            }
        }
    }
    return found;
}

static int64_t kofun_fn_split_operators(const char * expression, const char * operators) {
    kofun_text_list symbols = kofun_rt_chars(expression);
    int64_t depth = INT64_C(0);
    int64_t found = INT64_C(-1);
    bool quoted = false;
    bool escaped = false;
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        const char * symbol = kofun_rt_text_list_get(symbols, index);
        if (quoted) {
            if (escaped) {
                escaped = false;
            } else if (kofun_rt_text_equal(symbol, "\\")) {
                escaped = true;
            } else if (kofun_rt_text_equal(symbol, "\"")) {
                quoted = false;
            }
        } else if (kofun_rt_text_equal(symbol, "\"")) {
            quoted = true;
        } else if ((kofun_rt_text_equal(symbol, "(")) ||
                   (kofun_rt_text_equal(symbol, "["))) {
            depth = ((depth) + (INT64_C(1)));
        } else if ((kofun_rt_text_equal(symbol, ")")) ||
                   (kofun_rt_text_equal(symbol, "]"))) {
            depth = ((depth) - (INT64_C(1)));
        } else if ((((depth) == (INT64_C(0)))) &&
                   kofun_fn_preceded_by_operand(expression, index)) {
            const char * candidate = symbol;
            if ((((index) + (INT64_C(2))) <= (kofun_rt_text_list_len(symbols)))) {
                const char * pair = kofun_rt_text_slice(
                    expression, index, ((index) + (INT64_C(2))));
                if (((kofun_rt_find(
                        operators,
                        kofun_rt_text_concat(
                            kofun_rt_text_concat(",", pair), ","))) >=
                     (INT64_C(0)))) {
                    candidate = pair;
                }
            }
            if (((kofun_rt_find(
                    operators,
                    kofun_rt_text_concat(
                        kofun_rt_text_concat(",", candidate), ","))) >=
                 (INT64_C(0)))) {
                found = index;
            }
        }
    }
    return found;
}

static bool kofun_fn_wraps_whole(const char * expression) {
    kofun_text_list symbols = kofun_rt_chars(expression);
    if ((((kofun_rt_text_list_len(symbols)) < (INT64_C(2))) ||
         ((!kofun_rt_text_equal(kofun_rt_text_list_get(symbols, INT64_C(0)), "("))))) {
        return false;
    }
    int64_t depth = INT64_C(0);
    bool quoted = false;
    bool escaped = false;
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        const char * symbol = kofun_rt_text_list_get(symbols, index);
        if (quoted) {
            if (escaped) {
                escaped = false;
            } else if (kofun_rt_text_equal(symbol, "\\")) {
                escaped = true;
            } else if (kofun_rt_text_equal(symbol, "\"")) {
                quoted = false;
            }
        } else if (kofun_rt_text_equal(symbol, "\"")) {
            quoted = true;
        } else if (kofun_rt_text_equal(symbol, "(")) {
            depth = ((depth) + (INT64_C(1)));
        } else if (kofun_rt_text_equal(symbol, ")")) {
            depth = ((depth) - (INT64_C(1)));
            if (((depth) == (INT64_C(0)))) {
                return ((index) == ((kofun_rt_text_list_len(symbols)) - (INT64_C(1))));
            }
        }
    }
    return false;
}

static int64_t kofun_fn_postfix_index(const char * expression) {
    kofun_text_list symbols = kofun_rt_chars(expression);
    if (((kofun_rt_text_list_len(symbols)) < (INT64_C(3))) ||
        (!kofun_rt_text_equal(
            kofun_rt_text_list_get(
                symbols,
                ((kofun_rt_text_list_len(symbols)) - (INT64_C(1)))),
            "]"))) {
        return INT64_C(-1);
    }
    int64_t parens = INT64_C(0);
    int64_t brackets = INT64_C(0);
    int64_t found = INT64_C(-1);
    bool quoted = false;
    bool escaped = false;
    for (int64_t index = INT64_C(0);
         index < kofun_rt_text_list_len(symbols);
         ++index) {
        const char * symbol = kofun_rt_text_list_get(symbols, index);
        if (quoted) {
            if (escaped) {
                escaped = false;
            } else if (kofun_rt_text_equal(symbol, "\\")) {
                escaped = true;
            } else if (kofun_rt_text_equal(symbol, "\"")) {
                quoted = false;
            }
        } else if (kofun_rt_text_equal(symbol, "\"")) {
            quoted = true;
        } else if (kofun_rt_text_equal(symbol, "(")) {
            parens = ((parens) + (INT64_C(1)));
        } else if (kofun_rt_text_equal(symbol, ")")) {
            parens = ((parens) - (INT64_C(1)));
        } else if (kofun_rt_text_equal(symbol, "[")) {
            if (((parens) == (INT64_C(0))) &&
                ((brackets) == (INT64_C(0)))) {
                found = index;
            }
            brackets = ((brackets) + (INT64_C(1)));
        } else if (kofun_rt_text_equal(symbol, "]")) {
            brackets = ((brackets) - (INT64_C(1)));
            if (((brackets) < (INT64_C(0)))) {
                return INT64_C(-1);
            }
        }
    }
    if (((parens) != (INT64_C(0))) ||
        ((brackets) != (INT64_C(0)))) {
        return INT64_C(-1);
    }
    return found;
}

static const char * kofun_fn_call_argument(
        const char * expression,
        const char * callee) {
    if ((!kofun_rt_starts_with(
            expression, kofun_rt_text_concat(callee, "(")))) {
        return "";
    }
    const char * parenthesized = kofun_rt_text_slice(
        expression, kofun_rt_text_len(callee), kofun_rt_text_len(expression));
    if ((!kofun_fn_wraps_whole(parenthesized))) {
        return "";
    }
    return kofun_rt_trim(kofun_rt_text_slice(
        parenthesized, INT64_C(1),
        ((kofun_rt_text_len(parenthesized)) - (INT64_C(1)))));
}

static int64_t kofun_fn_last_newline(const char * value) {
    kofun_text_list symbols = kofun_rt_chars(value);
    int64_t found = INT64_C(-1);
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if (kofun_rt_text_equal(kofun_rt_text_list_get(symbols, index), "\n")) {
            found = index;
        }
    }
    return found;
}

static const char * kofun_fn_lowered_type(const char * lowered) {
    if (kofun_rt_starts_with(lowered, "Int|")) {
        return "Int";
    }
    if (kofun_rt_starts_with(lowered, "Bool|")) {
        return "Bool";
    }
    if (kofun_rt_starts_with(lowered, "Text|")) {
        return "Text";
    }
    if (kofun_rt_starts_with(lowered, "List[Text]|")) {
        return "List[Text]";
    }
    return "";
}

static const char * kofun_fn_lowered_value(const char * lowered) {
    const char * kind = kofun_fn_lowered_type(lowered);
    if (((kofun_rt_text_len(kind)) == (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_text_slice(
        lowered,
        ((kofun_rt_text_len(kind)) + (INT64_C(1))),
        kofun_rt_text_len(lowered));
}

static const char * kofun_fn_lowered_statements(const char * lowered) {
    const char * value = kofun_fn_lowered_value(lowered);
    int64_t cut = kofun_fn_last_newline(value);
    if (((cut) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_text_slice(value, INT64_C(0), ((cut) + (INT64_C(1))));
}

static const char * kofun_fn_lowered_operand(const char * lowered) {
    const char * value = kofun_fn_lowered_value(lowered);
    int64_t cut = kofun_fn_last_newline(value);
    return kofun_rt_text_slice(
        value, ((cut) + (INT64_C(1))), kofun_rt_text_len(value));
}

static const char * kofun_fn_lower_step(const char * path, const char * indent, const char * callee, const char * left, const char * right) {
    if (((!kofun_rt_text_equal(kofun_fn_lowered_type(left), "Int"))) ||
        ((!kofun_rt_text_equal(kofun_fn_lowered_type(right), "Int")))) {
        return "";
    }
    const char * temporary = kofun_rt_text_concat("kt_", path);
    const char * emitted = "Int|";
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(left));
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(right));
    emitted = kofun_rt_text_concat(emitted, indent);
    emitted = kofun_rt_text_concat(emitted, "int64_t ");
    emitted = kofun_rt_text_concat(emitted, temporary);
    emitted = kofun_rt_text_concat(emitted, " = ");
    emitted = kofun_rt_text_concat(emitted, callee);
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(left));
    emitted = kofun_rt_text_concat(emitted, ", ");
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(right));
    emitted = kofun_rt_text_concat(emitted, ");\n");
    return kofun_rt_text_concat(emitted, temporary);
}

static const char * kofun_fn_lower_comparison(
        const char * path,
        const char * indent,
        const char * operator_text,
        const char * left,
        const char * right) {
    const char * left_type = kofun_fn_lowered_type(left);
    const char * right_type = kofun_fn_lowered_type(right);
    if ((kofun_rt_text_equal(operator_text, "==")) ||
        (kofun_rt_text_equal(operator_text, "!="))) {
        if ((((kofun_rt_text_len(left_type)) == (INT64_C(0)))) ||
            ((!kofun_rt_text_equal(left_type, right_type)))) {
            return "";
        }
        if (kofun_rt_text_equal(left_type, "List[Text]")) {
            return "";
        }
    } else if (((!kofun_rt_text_equal(left_type, "Int"))) ||
               ((!kofun_rt_text_equal(right_type, "Int")))) {
        return "";
    }
    const char * temporary = kofun_rt_text_concat("kt_", path);
    if (kofun_rt_text_equal(left_type, "Text")) {
        const char * negated = "";
        if (kofun_rt_text_equal(operator_text, "!=")) {
            negated = "!";
        }
        const char * emitted = "Bool|";
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_statements(left));
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_statements(right));
        emitted = kofun_rt_text_concat(emitted, indent);
        emitted = kofun_rt_text_concat(emitted, "bool ");
        emitted = kofun_rt_text_concat(emitted, temporary);
        emitted = kofun_rt_text_concat(emitted, " = ");
        emitted = kofun_rt_text_concat(emitted, negated);
        emitted = kofun_rt_text_concat(emitted, "kofun_rt_text_equal(");
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_operand(left));
        emitted = kofun_rt_text_concat(emitted, ", ");
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_operand(right));
        emitted = kofun_rt_text_concat(emitted, ");\n");
        return kofun_rt_text_concat(emitted, temporary);
    }
    const char * emitted = "Bool|";
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(left));
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(right));
    emitted = kofun_rt_text_concat(emitted, indent);
    emitted = kofun_rt_text_concat(emitted, "bool ");
    emitted = kofun_rt_text_concat(emitted, temporary);
    emitted = kofun_rt_text_concat(emitted, " = ");
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(left));
    emitted = kofun_rt_text_concat(emitted, " ");
    emitted = kofun_rt_text_concat(emitted, operator_text);
    emitted = kofun_rt_text_concat(emitted, " ");
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(right));
    emitted = kofun_rt_text_concat(emitted, ";\n");
    return kofun_rt_text_concat(emitted, temporary);
}

static const char * kofun_fn_lower_logical(
        const char * path,
        const char * indent,
        const char * operator_text,
        const char * left,
        const char * right) {
    if (((!kofun_rt_text_equal(kofun_fn_lowered_type(left), "Bool"))) ||
        ((!kofun_rt_text_equal(kofun_fn_lowered_type(right), "Bool")))) {
        return "";
    }
    const char * temporary = kofun_rt_text_concat("kt_", path);
    const char * condition = temporary;
    if (kofun_rt_text_equal(operator_text, "||")) {
        condition = kofun_rt_text_concat("!", temporary);
    }
    const char * emitted = "Bool|";
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(left));
    emitted = kofun_rt_text_concat(emitted, indent);
    emitted = kofun_rt_text_concat(emitted, "bool ");
    emitted = kofun_rt_text_concat(emitted, temporary);
    emitted = kofun_rt_text_concat(emitted, " = ");
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(left));
    emitted = kofun_rt_text_concat(emitted, ";\n");
    emitted = kofun_rt_text_concat(emitted, indent);
    emitted = kofun_rt_text_concat(emitted, "if (!failed && ");
    emitted = kofun_rt_text_concat(emitted, condition);
    emitted = kofun_rt_text_concat(emitted, ") {\n");
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(right));
    emitted = kofun_rt_text_concat(emitted, indent);
    emitted = kofun_rt_text_concat(emitted, "    ");
    emitted = kofun_rt_text_concat(emitted, temporary);
    emitted = kofun_rt_text_concat(emitted, " = ");
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(right));
    emitted = kofun_rt_text_concat(emitted, ";\n");
    emitted = kofun_rt_text_concat(emitted, indent);
    emitted = kofun_rt_text_concat(emitted, "}\n");
    return kofun_rt_text_concat(emitted, temporary);
}

static const char * kofun_fn_bound_type(const char * bound, const char * name) {
    const char * int_key = kofun_rt_text_concat(
        kofun_rt_text_concat(
            kofun_rt_text_concat("|", name), ":Int"), "|");
    if (((kofun_rt_find(bound, int_key)) >= (INT64_C(0)))) {
        return "Int";
    }
    const char * bool_key = kofun_rt_text_concat(
        kofun_rt_text_concat(
            kofun_rt_text_concat("|", name), ":Bool"), "|");
    if (((kofun_rt_find(bound, bool_key)) >= (INT64_C(0)))) {
        return "Bool";
    }
    const char * text_key = kofun_rt_text_concat(
        kofun_rt_text_concat(
            kofun_rt_text_concat("|", name), ":Text"), "|");
    if (((kofun_rt_find(bound, text_key)) >= (INT64_C(0)))) {
        return "Text";
    }
    const char * list_key = kofun_rt_text_concat(
        kofun_rt_text_concat(
            kofun_rt_text_concat("|", name), ":List[Text]"), "|");
    if (((kofun_rt_find(bound, list_key)) >= (INT64_C(0)))) {
        return "List[Text]";
    }
    return "";
}

static const char * kofun_fn_lower_atom(const char * atom, const char * bound) {
    kofun_text_list symbols = kofun_rt_chars(atom);
    if ((((kofun_rt_text_list_len(symbols)) >= (INT64_C(2))) &&
         kofun_rt_text_equal(
             kofun_rt_text_list_get(symbols, INT64_C(0)), "\"")) &&
        kofun_rt_text_equal(
            kofun_rt_text_list_get(
                symbols,
                ((kofun_rt_text_list_len(symbols)) - (INT64_C(1)))),
            "\"")) {
        bool escaped = false;
        for (int64_t index = INT64_C(1);
             index < ((kofun_rt_text_list_len(symbols)) - (INT64_C(1)));
             ++index) {
            const char * symbol = kofun_rt_text_list_get(symbols, index);
            if (escaped) {
                if (((!kofun_rt_text_equal(symbol, "n"))) &&
                    ((!kofun_rt_text_equal(symbol, "\""))) &&
                    ((!kofun_rt_text_equal(symbol, "\\")))) {
                    return "";
                }
                escaped = false;
            } else if (kofun_rt_text_equal(symbol, "\\")) {
                escaped = true;
            } else if (kofun_rt_text_equal(symbol, "\"")) {
                return "";
            }
        }
        if (escaped) {
            return "";
        }
        return kofun_rt_text_concat("Text|", atom);
    }
    if (kofun_fn_all_digits(atom)) {
        if ((!kofun_fn_within_bound(atom, "9223372036854775807"))) {
            return "";
        }
        return kofun_rt_text_concat("Int|", atom);
    }
    if ((kofun_rt_text_equal(atom, "true")) ||
        (kofun_rt_text_equal(atom, "false"))) {
        return kofun_rt_text_concat("Bool|", atom);
    }
    if ((!kofun_fn_valid_name(atom))) {
        return "";
    }
    const char * kind = kofun_fn_bound_type(bound, atom);
    if (((kofun_rt_text_len(kind)) == (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_text_concat(
        kofun_rt_text_concat(kind, "|"),
        kofun_rt_text_concat("kf_", atom));
}

static const char * kofun_fn_lower_negation(const char * operand, const char * bound, const char * path, const char * indent) {
    const char * trimmed = kofun_rt_trim(operand);
    if (kofun_fn_all_digits(trimmed)) {
        if (kofun_fn_within_bound(trimmed, "9223372036854775807")) {
            return kofun_rt_text_concat("Int|-", trimmed);
        }
        if (kofun_fn_within_bound(trimmed, "9223372036854775808")) {
            return "Int|INT64_MIN";
        }
        return "";
    }
    const char * inner = kofun_fn_lower_expression(
        trimmed, bound, kofun_rt_text_concat(path, "u"), indent);
    if ((!kofun_rt_text_equal(kofun_fn_lowered_type(inner), "Int"))) {
        return "";
    }
    const char * temporary = kofun_rt_text_concat("kt_", path);
    const char * emitted = "Int|";
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(inner));
    emitted = kofun_rt_text_concat(emitted, indent);
    emitted = kofun_rt_text_concat(emitted, "int64_t ");
    emitted = kofun_rt_text_concat(emitted, temporary);
    emitted = kofun_rt_text_concat(emitted, " = checked_neg(");
    emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(inner));
    emitted = kofun_rt_text_concat(emitted, ");\n");
    return kofun_rt_text_concat(emitted, temporary);
}

static const char * kofun_fn_lower_expression(const char * expression, const char * bound, const char * path, const char * indent) {
    const char * trimmed = kofun_rt_trim(expression);
    if (((kofun_rt_text_len(trimmed)) == (INT64_C(0)))) {
        return "";
    }

    int64_t logical_or = kofun_fn_split_operators(trimmed, ",||,");
    if (((logical_or) >= (INT64_C(0)))) {
        const char * left = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(0), logical_or), bound,
            kofun_rt_text_concat(path, "l"), indent);
        const char * right = kofun_fn_lower_expression(
            kofun_rt_text_slice(
                trimmed, ((logical_or) + (INT64_C(2))),
                kofun_rt_text_len(trimmed)), bound,
            kofun_rt_text_concat(path, "r"), indent);
        return kofun_fn_lower_logical(path, indent, "||", left, right);
    }

    int64_t logical_and = kofun_fn_split_operators(trimmed, ",&&,");
    if (((logical_and) >= (INT64_C(0)))) {
        const char * left = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(0), logical_and), bound,
            kofun_rt_text_concat(path, "l"), indent);
        const char * right = kofun_fn_lower_expression(
            kofun_rt_text_slice(
                trimmed, ((logical_and) + (INT64_C(2))),
                kofun_rt_text_len(trimmed)), bound,
            kofun_rt_text_concat(path, "r"), indent);
        return kofun_fn_lower_logical(path, indent, "&&", left, right);
    }

    int64_t equality = kofun_fn_split_operators(trimmed, ",==,!=,");
    if (((equality) >= (INT64_C(0)))) {
        const char * operator_text = kofun_rt_text_slice(
            trimmed, equality, ((equality) + (INT64_C(2))));
        const char * left = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(0), equality), bound,
            kofun_rt_text_concat(path, "l"), indent);
        const char * right = kofun_fn_lower_expression(
            kofun_rt_text_slice(
                trimmed, ((equality) + (INT64_C(2))),
                kofun_rt_text_len(trimmed)), bound,
            kofun_rt_text_concat(path, "r"), indent);
        return kofun_fn_lower_comparison(
            path, indent, operator_text, left, right);
    }

    int64_t ordering = kofun_fn_split_operators(trimmed, ",<=,>=,<,>,");
    if (((ordering) >= (INT64_C(0)))) {
        int64_t skip = INT64_C(1);
        if (((((ordering) + (INT64_C(2))) <= (kofun_rt_text_len(trimmed)))) &&
            kofun_rt_text_equal(
                kofun_rt_text_slice(
                    trimmed, ((ordering) + (INT64_C(1))),
                    ((ordering) + (INT64_C(2)))),
                "=")) {
            skip = INT64_C(2);
        }
        const char * operator_text = kofun_rt_text_slice(
            trimmed, ordering, ((ordering) + (skip)));
        const char * left = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(0), ordering), bound,
            kofun_rt_text_concat(path, "l"), indent);
        const char * right = kofun_fn_lower_expression(
            kofun_rt_text_slice(
                trimmed, ((ordering) + (skip)),
                kofun_rt_text_len(trimmed)), bound,
            kofun_rt_text_concat(path, "r"), indent);
        return kofun_fn_lower_comparison(
            path, indent, operator_text, left, right);
    }

    int64_t additive = kofun_fn_split_binary(trimmed, "+-");
    if (((additive) >= (INT64_C(0)))) {
        const char * left = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(0), additive), bound,
            kofun_rt_text_concat(path, "l"), indent);
        const char * right = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, ((additive) + (INT64_C(1))),
                                kofun_rt_text_len(trimmed)), bound,
            kofun_rt_text_concat(path, "r"), indent);
        if (kofun_rt_text_equal(
                kofun_rt_text_slice(trimmed, additive, ((additive) + (INT64_C(1)))), "+")) {
            if ((kofun_rt_text_equal(kofun_fn_lowered_type(left), "Text")) &&
                (kofun_rt_text_equal(kofun_fn_lowered_type(right), "Text"))) {
                const char * temporary = kofun_rt_text_concat("kt_", path);
                const char * emitted = "Text|";
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_statements(left));
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_statements(right));
                emitted = kofun_rt_text_concat(emitted, indent);
                emitted = kofun_rt_text_concat(emitted, "const char * ");
                emitted = kofun_rt_text_concat(emitted, temporary);
                emitted = kofun_rt_text_concat(
                    emitted, " = kofun_rt_text_concat(");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_operand(left));
                emitted = kofun_rt_text_concat(emitted, ", ");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_operand(right));
                emitted = kofun_rt_text_concat(emitted, ");\n");
                return kofun_rt_text_concat(emitted, temporary);
            }
            return kofun_fn_lower_step(path, indent, "checked_add(", left, right);
        }
        return kofun_fn_lower_step(path, indent, "checked_sub(", left, right);
    }

    int64_t multiplicative = kofun_fn_split_binary(trimmed, "*%/");
    if (((multiplicative) >= (INT64_C(0)))) {
        const char * operator_text = kofun_rt_text_slice(
            trimmed, multiplicative, ((multiplicative) + (INT64_C(1))));
        const char * callee = "checked_mul(";
        int64_t skip = INT64_C(1);
        if (kofun_rt_text_equal(operator_text, "%")) {
            callee = "floor_mod(";
        } else if (kofun_rt_text_equal(operator_text, "/")) {
            if ((((multiplicative) + (INT64_C(2))) > (kofun_rt_text_len(trimmed)))) {
                return "";
            }
            if ((!kofun_rt_text_equal(
                    kofun_rt_text_slice(trimmed, ((multiplicative) + (INT64_C(1))),
                                        ((multiplicative) + (INT64_C(2)))), "/"))) {
                return "";
            }
            callee = "floor_div(";
            skip = INT64_C(2);
        }
        const char * left = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(0), multiplicative), bound,
            kofun_rt_text_concat(path, "l"), indent);
        const char * right = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, ((multiplicative) + (skip)),
                                kofun_rt_text_len(trimmed)), bound,
            kofun_rt_text_concat(path, "r"), indent);
        return kofun_fn_lower_step(path, indent, callee, left, right);
    }

    int64_t index_open = kofun_fn_postfix_index(trimmed);
    if (((index_open) >= (INT64_C(0)))) {
        const char * base = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(0), index_open), bound,
            kofun_rt_text_concat(path, "b"), indent);
        const char * index = kofun_fn_lower_expression(
            kofun_rt_text_slice(
                trimmed, ((index_open) + (INT64_C(1))),
                ((kofun_rt_text_len(trimmed)) - (INT64_C(1)))),
            bound, kofun_rt_text_concat(path, "i"), indent);
        const char * base_type = kofun_fn_lowered_type(base);
        if ((!kofun_rt_text_equal(
                kofun_fn_lowered_type(index), "Int")) ||
            ((!kofun_rt_text_equal(base_type, "Text")) &&
             (!kofun_rt_text_equal(base_type, "List[Text]")))) {
            return "";
        }
        const char * callee = "kofun_rt_text_index(";
        if (kofun_rt_text_equal(base_type, "List[Text]")) {
            callee = "kofun_rt_text_list_get(";
        }
        const char * temporary = kofun_rt_text_concat("kt_", path);
        const char * emitted = "Text|";
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_statements(base));
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_statements(index));
        emitted = kofun_rt_text_concat(emitted, indent);
        emitted = kofun_rt_text_concat(emitted, "const char * ");
        emitted = kofun_rt_text_concat(emitted, temporary);
        emitted = kofun_rt_text_concat(emitted, " = ");
        emitted = kofun_rt_text_concat(emitted, callee);
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_operand(base));
        emitted = kofun_rt_text_concat(emitted, ", ");
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_operand(index));
        emitted = kofun_rt_text_concat(emitted, ");\n");
        return kofun_rt_text_concat(emitted, temporary);
    }

    if (kofun_rt_starts_with(trimmed, "chars(")) {
        const char * value = kofun_fn_lower_expression(
            kofun_fn_call_argument(trimmed, "chars"), bound,
            kofun_rt_text_concat(path, "c"), indent);
        if ((!kofun_rt_text_equal(
                kofun_fn_lowered_type(value), "Text"))) {
            return "";
        }
        const char * temporary = kofun_rt_text_concat("kt_", path);
        const char * emitted = "List[Text]|";
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_statements(value));
        emitted = kofun_rt_text_concat(emitted, indent);
        emitted = kofun_rt_text_concat(emitted, "KofunTextList ");
        emitted = kofun_rt_text_concat(emitted, temporary);
        emitted = kofun_rt_text_concat(emitted, " = kofun_rt_chars(");
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_operand(value));
        emitted = kofun_rt_text_concat(emitted, ");\n");
        return kofun_rt_text_concat(emitted, temporary);
    }

    if (kofun_rt_starts_with(trimmed, "len(")) {
        const char * value = kofun_fn_lower_expression(
            kofun_fn_call_argument(trimmed, "len"), bound,
            kofun_rt_text_concat(path, "n"), indent);
        if ((!kofun_rt_text_equal(
                kofun_fn_lowered_type(value), "List[Text]"))) {
            return "";
        }
        const char * temporary = kofun_rt_text_concat("kt_", path);
        const char * emitted = "Int|";
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_statements(value));
        emitted = kofun_rt_text_concat(emitted, indent);
        emitted = kofun_rt_text_concat(emitted, "int64_t ");
        emitted = kofun_rt_text_concat(emitted, temporary);
        emitted = kofun_rt_text_concat(
            emitted, " = kofun_rt_text_list_len(");
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_operand(value));
        emitted = kofun_rt_text_concat(emitted, ");\n");
        return kofun_rt_text_concat(emitted, temporary);
    }

    if (kofun_rt_starts_with(trimmed, "+")) {
        const char * inner = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(1), kofun_rt_text_len(trimmed)), bound, path, indent);
        if ((!kofun_rt_text_equal(kofun_fn_lowered_type(inner), "Int"))) {
            return "";
        }
        return inner;
    }
    if (kofun_rt_starts_with(trimmed, "-")) {
        return kofun_fn_lower_negation(
            kofun_rt_text_slice(trimmed, INT64_C(1), kofun_rt_text_len(trimmed)), bound, path, indent);
    }
    if (kofun_rt_starts_with(trimmed, "!")) {
        const char * inner = kofun_fn_lower_expression(
            kofun_rt_text_slice(
                trimmed, INT64_C(1), kofun_rt_text_len(trimmed)),
            bound, kofun_rt_text_concat(path, "u"), indent);
        if ((!kofun_rt_text_equal(kofun_fn_lowered_type(inner), "Bool"))) {
            return "";
        }
        const char * temporary = kofun_rt_text_concat("kt_", path);
        const char * emitted = "Bool|";
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_statements(inner));
        emitted = kofun_rt_text_concat(emitted, indent);
        emitted = kofun_rt_text_concat(emitted, "bool ");
        emitted = kofun_rt_text_concat(emitted, temporary);
        emitted = kofun_rt_text_concat(emitted, " = !");
        emitted = kofun_rt_text_concat(
            emitted, kofun_fn_lowered_operand(inner));
        emitted = kofun_rt_text_concat(emitted, ";\n");
        return kofun_rt_text_concat(emitted, temporary);
    }
    if (kofun_fn_wraps_whole(trimmed)) {
        return kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(1),
                                ((kofun_rt_text_len(trimmed)) - (INT64_C(1)))), bound, path, indent);
    }
    return kofun_fn_lower_atom(trimmed, bound);
}

static const char * kofun_fn_print_expression(const char * line) {
    const char * marker = "print(";
    int64_t start = kofun_rt_find(line, marker);
    if (((start) < (INT64_C(0)))) {
        return "";
    }
    int64_t expression_start = ((start) + (kofun_rt_text_len(marker)));
    kofun_text_list symbols = kofun_rt_chars(line);
    int64_t depth = INT64_C(1);
    int64_t index = expression_start;
    bool quoted = false;
    bool escaped = false;
    while (((index) < (kofun_rt_text_list_len(symbols)))) {
        const char * symbol = kofun_rt_text_list_get(symbols, index);
        if (quoted) {
            if (escaped) {
                escaped = false;
            } else if (kofun_rt_text_equal(symbol, "\\")) {
                escaped = true;
            } else if (kofun_rt_text_equal(symbol, "\"")) {
                quoted = false;
            }
        } else if (kofun_rt_text_equal(symbol, "\"")) {
            quoted = true;
        } else if (kofun_rt_text_equal(symbol, "(")) {
            depth = ((depth) + (INT64_C(1)));
        } else if (kofun_rt_text_equal(symbol, ")")) {
            depth = ((depth) - (INT64_C(1)));
            if (((depth) == (INT64_C(0)))) {
                return kofun_rt_trim(kofun_rt_text_slice(line, expression_start, index));
            }
        }
        index = ((index) + (INT64_C(1)));
    }
    return "";
}

static const char * kofun_fn_binding_name(const char * line) {
    int64_t equals = kofun_rt_find(line, "=");
    if (((equals) < (INT64_C(0)))) {
        return "";
    }
    const char * name = kofun_rt_trim(kofun_rt_text_slice(line, INT64_C(4), equals));
    int64_t colon = kofun_rt_find(name, ":");
    if (((colon) >= (INT64_C(0)))) {
        return kofun_rt_trim(kofun_rt_text_slice(name, INT64_C(0), colon));
    }
    return name;
}

static const char * kofun_fn_binding_expression(const char * line) {
    int64_t equals = kofun_rt_find(line, "=");
    if (((equals) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_trim(kofun_rt_text_slice(line, ((equals) + (INT64_C(1))), kofun_rt_text_len(line)));
}

static const char * kofun_fn_binding_annotation(const char * line) {
    int64_t equals = kofun_rt_find(line, "=");
    if (((equals) < (INT64_C(0)))) {
        return "";
    }
    const char * declaration = kofun_rt_trim(
        kofun_rt_text_slice(line, INT64_C(4), equals));
    int64_t colon = kofun_rt_find(declaration, ":");
    if (((colon) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_trim(kofun_rt_text_slice(
        declaration, ((colon) + (INT64_C(1))),
        kofun_rt_text_len(declaration)));
}

static const char * kofun_fn_indentation(int64_t units) {
    const char * spaces = "";
    int64_t step = INT64_C(0);
    while (((step) < (units))) {
        spaces = kofun_rt_text_concat(spaces, "    ");
        step = ((step) + (INT64_C(1)));
    }
    return spaces;
}

static const char * kofun_fn_statement_indent(int64_t depth) {
    return kofun_fn_indentation(
        ((((INT64_C(2)) * (depth))) - (INT64_C(1))));
}

static const char * kofun_fn_nested_indent(int64_t depth) {
    return kofun_fn_indentation(((INT64_C(2)) * (depth)));
}

static const char * kofun_fn_scope_enter(const char * bound) {
    return kofun_rt_text_concat(bound, "{|");
}

static const char * kofun_fn_scope_leave(const char * bound) {
    kofun_text_list symbols = kofun_rt_chars(bound);
    int64_t found = INT64_C(-1);
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if (kofun_rt_text_equal(kofun_rt_text_list_get(symbols, index), "{")) {
            found = index;
        }
    }
    if (((found) < (INT64_C(0)))) {
        return bound;
    }
    return kofun_rt_text_slice(bound, INT64_C(0), found);
}

static const char * kofun_fn_block_kind(const char * blocks) {
    if (((kofun_rt_text_len(blocks)) == (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_text_slice(
        blocks, ((kofun_rt_text_len(blocks)) - (INT64_C(1))),
        kofun_rt_text_len(blocks));
}

static const char * kofun_fn_block_pop(const char * blocks) {
    if (((kofun_rt_text_len(blocks)) == (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_text_slice(
        blocks, INT64_C(0), ((kofun_rt_text_len(blocks)) - (INT64_C(1))));
}

static const char * kofun_fn_header_condition(const char * line, const char * keyword) {
    if ((!kofun_rt_starts_with(line, keyword))) {
        return "";
    }
    if (((kofun_rt_text_len(line)) <
         ((kofun_rt_text_len(keyword)) + (INT64_C(2))))) {
        return "";
    }
    if ((!kofun_rt_text_equal(
            kofun_rt_text_slice(
                line, ((kofun_rt_text_len(line)) - (INT64_C(2))),
                kofun_rt_text_len(line)),
            " {"))) {
        return "";
    }
    return kofun_rt_trim(kofun_rt_text_slice(
        line, kofun_rt_text_len(keyword),
        ((kofun_rt_text_len(line)) - (INT64_C(2)))));
}

static const char * kofun_fn_range_header(const char * line) {
    if ((!kofun_rt_starts_with(line, "for "))) {
        return "";
    }
    if ((!kofun_rt_text_equal(
            kofun_rt_text_slice(
                line, ((kofun_rt_text_len(line)) - (INT64_C(2))),
                kofun_rt_text_len(line)),
            " {"))) {
        return "";
    }
    return kofun_rt_trim(kofun_rt_text_slice(
        line, INT64_C(4), ((kofun_rt_text_len(line)) - (INT64_C(2)))));
}

static const char * kofun_fn_range_name(const char * line) {
    const char * header = kofun_fn_range_header(line);
    int64_t split = kofun_rt_find(header, " in ");
    if (((split) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_trim(kofun_rt_text_slice(header, INT64_C(0), split));
}

static const char * kofun_fn_range_bounds(const char * line) {
    const char * header = kofun_fn_range_header(line);
    int64_t split = kofun_rt_find(header, " in ");
    if (((split) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_text_slice(
        header, ((split) + (INT64_C(4))), kofun_rt_text_len(header));
}

static const char * kofun_fn_range_start(const char * line) {
    const char * bounds = kofun_fn_range_bounds(line);
    int64_t split = kofun_rt_find(bounds, " .. ");
    if (((split) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_trim(kofun_rt_text_slice(bounds, INT64_C(0), split));
}

static const char * kofun_fn_range_end(const char * line) {
    const char * bounds = kofun_fn_range_bounds(line);
    int64_t split = kofun_rt_find(bounds, " .. ");
    if (((split) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_trim(kofun_rt_text_slice(
        bounds, ((split) + (INT64_C(4))), kofun_rt_text_len(bounds)));
}

static bool kofun_fn_valid_source(const char * source) {
    kofun_text_list symbols = kofun_rt_chars(source);
    int64_t line_start = INT64_C(0);
    int64_t prints = INT64_C(0);
    int64_t main_headers = INT64_C(0);
    const char * blocks = "";
    const char * bound = "|";
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if (kofun_rt_text_equal(kofun_rt_text_list_get(symbols, index), "\n")) {
            const char * line = kofun_rt_trim(kofun_rt_text_slice(source, line_start, index));
            if (((kofun_rt_text_len(line) == INT64_C(0)) || kofun_rt_starts_with(line, "#"))) {
            } else if (kofun_rt_text_equal(line, "fn main() {")) {
                if ((((main_headers) != (INT64_C(0))) ||
                     ((kofun_rt_text_len(blocks)) > (INT64_C(0))))) {
                    return false;
                }
                main_headers = ((main_headers) + (INT64_C(1)));
                blocks = "f";
                bound = kofun_fn_scope_enter(bound);
            } else if (kofun_rt_text_equal(line, "}")) {
                if (((kofun_rt_text_len(blocks)) == (INT64_C(0)))) {
                    return false;
                }
                blocks = kofun_fn_block_pop(blocks);
                bound = kofun_fn_scope_leave(bound);
            } else if (kofun_rt_text_equal(line, "} else {")) {
                if ((!kofun_rt_text_equal(kofun_fn_block_kind(blocks), "i"))) {
                    return false;
                }
                blocks = kofun_rt_text_concat(
                    kofun_fn_block_pop(blocks), "e");
                bound = kofun_fn_scope_enter(kofun_fn_scope_leave(bound));
            } else if (kofun_rt_starts_with(line, "} else if ")) {
                if ((!kofun_rt_text_equal(kofun_fn_block_kind(blocks), "i"))) {
                    return false;
                }
                bound = kofun_fn_scope_leave(bound);
                const char * condition = kofun_fn_lower_expression(
                    kofun_fn_header_condition(line, "} else if "), bound, "x",
                    kofun_fn_statement_indent(kofun_rt_text_len(blocks)));
                if ((!kofun_rt_text_equal(
                        kofun_fn_lowered_type(condition), "Bool"))) {
                    return false;
                }
                bound = kofun_fn_scope_enter(bound);
            } else if (kofun_rt_starts_with(line, "if ")) {
                if (((kofun_rt_text_len(blocks)) == (INT64_C(0)))) {
                    return false;
                }
                const char * condition = kofun_fn_lower_expression(
                    kofun_fn_header_condition(line, "if "), bound, "x",
                    kofun_fn_statement_indent(
                        ((kofun_rt_text_len(blocks)) + (INT64_C(1)))));
                if ((!kofun_rt_text_equal(
                        kofun_fn_lowered_type(condition), "Bool"))) {
                    return false;
                }
                blocks = kofun_rt_text_concat(blocks, "i");
                bound = kofun_fn_scope_enter(bound);
            } else if (kofun_rt_starts_with(line, "while ")) {
                if (((kofun_rt_text_len(blocks)) == (INT64_C(0)))) {
                    return false;
                }
                const char * condition = kofun_fn_lower_expression(
                    kofun_fn_header_condition(line, "while "), bound, "x",
                    kofun_fn_statement_indent(
                        ((kofun_rt_text_len(blocks)) + (INT64_C(1)))));
                if ((!kofun_rt_text_equal(
                        kofun_fn_lowered_type(condition), "Bool"))) {
                    return false;
                }
                blocks = kofun_rt_text_concat(blocks, "w");
                bound = kofun_fn_scope_enter(bound);
            } else if (kofun_rt_starts_with(line, "for ")) {
                if (((kofun_rt_text_len(blocks)) == (INT64_C(0)))) {
                    return false;
                }
                const char * name = kofun_fn_range_name(line);
                if (((!kofun_fn_valid_name(name)) ||
                     kofun_rt_text_equal(name, "true")) ||
                    kofun_rt_text_equal(name, "false")) {
                    return false;
                }
                if (((kofun_rt_text_len(kofun_fn_bound_type(bound, name))) >
                     (INT64_C(0)))) {
                    return false;
                }
                const char * from = kofun_fn_lower_expression(
                    kofun_fn_range_start(line), bound, "xl",
                    kofun_fn_nested_indent(kofun_rt_text_len(blocks)));
                const char * to = kofun_fn_lower_expression(
                    kofun_fn_range_end(line), bound, "xr",
                    kofun_fn_nested_indent(kofun_rt_text_len(blocks)));
                if (((!kofun_rt_text_equal(
                          kofun_fn_lowered_type(from), "Int")) ||
                     (!kofun_rt_text_equal(
                          kofun_fn_lowered_type(to), "Int")))) {
                    return false;
                }
                blocks = kofun_rt_text_concat(blocks, "r");
                bound = kofun_rt_text_concat(
                    kofun_rt_text_concat(
                        kofun_rt_text_concat(
                            kofun_fn_scope_enter(bound), name), ":Int"),
                    "|");
            } else if (kofun_rt_starts_with(line, "let ")) {
                if (((kofun_rt_text_len(blocks)) == (INT64_C(0)))) {
                    return false;
                }
                const char * name = kofun_fn_binding_name(line);
                if (((!kofun_fn_valid_name(name)) ||
                     kofun_rt_text_equal(name, "true")) ||
                    kofun_rt_text_equal(name, "false")) {
                    return false;
                }
                if (((kofun_rt_text_len(kofun_fn_bound_type(bound, name))) >
                     (INT64_C(0)))) {
                    return false;
                }
                const char * value = kofun_fn_lower_expression(
                    kofun_fn_binding_expression(line), bound, "x",
                    kofun_fn_nested_indent(kofun_rt_text_len(blocks)));
                const char * kind = kofun_fn_lowered_type(value);
                if (((kofun_rt_text_len(kind)) == (INT64_C(0)))) {
                    return false;
                }
                const char * declaration = kofun_rt_trim(
                    kofun_rt_text_slice(
                        line, INT64_C(4), kofun_rt_find(line, "=")));
                const char * annotation = kofun_fn_binding_annotation(line);
                if (((kofun_rt_find(declaration, ":")) >= (INT64_C(0))) &&
                    ((!kofun_rt_text_equal(annotation, kind)))) {
                    return false;
                }
                bound = kofun_rt_text_concat(
                    kofun_rt_text_concat(
                        kofun_rt_text_concat(
                            kofun_rt_text_concat(bound, name), ":"),
                        kind),
                    "|");
            } else if (kofun_rt_starts_with(line, "print(")) {
                if (((kofun_rt_text_len(blocks)) == (INT64_C(0)))) {
                    return false;
                }
                const char * expression = kofun_fn_print_expression(line);
                const char * kind = kofun_fn_lowered_type(
                    kofun_fn_lower_expression(
                        expression, bound, "x",
                        kofun_fn_nested_indent(kofun_rt_text_len(blocks))));
                if (((!kofun_rt_text_equal(kind, "Int"))) &&
                    ((!kofun_rt_text_equal(kind, "Text")))) {
                    return false;
                }
                prints = ((prints) + (INT64_C(1)));
            } else {
                return false;
            }
            line_start = ((index) + (INT64_C(1)));
        }
    }
    return (((((main_headers) == (INT64_C(1))) && ((kofun_rt_text_len(blocks)) == (INT64_C(0))))) && ((prints) > (INT64_C(0))));
}

static const char * kofun_fn_emit_statements(const char * source) {
    kofun_text_list symbols = kofun_rt_chars(source);
    int64_t line_start = INT64_C(0);
    const char * emitted = "";
    const char * bound = "|";
    const char * blocks = "";
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if (kofun_rt_text_equal(kofun_rt_text_list_get(symbols, index), "\n")) {
            const char * line = kofun_rt_trim(kofun_rt_text_slice(source, line_start, index));
            if (kofun_rt_text_equal(line, "fn main() {")) {
                blocks = "f";
                bound = kofun_fn_scope_enter(bound);
            } else if (kofun_rt_text_equal(line, "}")) {
                const char * kind = kofun_fn_block_kind(blocks);
                int64_t depth = kofun_rt_text_len(blocks);
                blocks = kofun_fn_block_pop(blocks);
                bound = kofun_fn_scope_leave(bound);
                if (((kofun_rt_text_len(blocks)) > (INT64_C(0)))) {
                    if ((kofun_rt_text_equal(kind, "w") ||
                         kofun_rt_text_equal(kind, "r"))) {
                        emitted = kofun_rt_text_concat(
                            emitted,
                            kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                        emitted = kofun_rt_text_concat(emitted, "}\n");
                        emitted = kofun_rt_text_concat(
                            emitted,
                            kofun_fn_statement_indent(
                                ((depth) - (INT64_C(1)))));
                        emitted = kofun_rt_text_concat(emitted, "}\n");
                    } else {
                        emitted = kofun_rt_text_concat(
                            emitted,
                            kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                        emitted = kofun_rt_text_concat(emitted, "}\n");
                        emitted = kofun_rt_text_concat(
                            emitted,
                            kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                        emitted = kofun_rt_text_concat(
                            emitted, "(void)kt_taken;\n");
                        emitted = kofun_rt_text_concat(
                            emitted,
                            kofun_fn_statement_indent(
                                ((depth) - (INT64_C(1)))));
                        emitted = kofun_rt_text_concat(emitted, "}\n");
                    }
                }
            } else if (kofun_rt_text_equal(line, "} else {")) {
                int64_t depth = kofun_rt_text_len(blocks);
                blocks = kofun_rt_text_concat(
                    kofun_fn_block_pop(blocks), "e");
                bound = kofun_fn_scope_enter(kofun_fn_scope_leave(bound));
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                emitted = kofun_rt_text_concat(emitted, "}\n");
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                emitted = kofun_rt_text_concat(
                    emitted, "if (!kt_taken) {\n");
            } else if (kofun_rt_starts_with(line, "} else if ")) {
                int64_t depth = kofun_rt_text_len(blocks);
                bound = kofun_fn_scope_leave(bound);
                const char * condition = kofun_fn_lower_expression(
                    kofun_fn_header_condition(line, "} else if "), bound, "x",
                    kofun_fn_statement_indent(depth));
                bound = kofun_fn_scope_enter(bound);
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                emitted = kofun_rt_text_concat(emitted, "}\n");
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                emitted = kofun_rt_text_concat(
                    emitted, "if (!kt_taken) {\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_statements(condition));
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "kt_cond = ");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_operand(condition));
                emitted = kofun_rt_text_concat(emitted, ";\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(
                    emitted, "if (failed) return 1;\n");
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                emitted = kofun_rt_text_concat(emitted, "} else {\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "kt_cond = false;\n");
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                emitted = kofun_rt_text_concat(emitted, "}\n");
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_nested_indent(((depth) - (INT64_C(1)))));
                emitted = kofun_rt_text_concat(emitted, "if (kt_cond) {\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "kt_taken = true;\n");
            } else if (kofun_rt_starts_with(line, "if ")) {
                int64_t depth = kofun_rt_text_len(blocks);
                const char * condition = kofun_fn_lower_expression(
                    kofun_fn_header_condition(line, "if "), bound, "x",
                    kofun_fn_statement_indent(((depth) + (INT64_C(1)))));
                blocks = kofun_rt_text_concat(blocks, "i");
                bound = kofun_fn_scope_enter(bound);
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "{\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(
                    emitted, "bool kt_taken = false;\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "bool kt_cond;\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "{\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_statements(condition));
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_statement_indent(((depth) + (INT64_C(1)))));
                emitted = kofun_rt_text_concat(emitted, "kt_cond = ");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_operand(condition));
                emitted = kofun_rt_text_concat(emitted, ";\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "}\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(
                    emitted, "if (failed) return 1;\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "if (kt_cond) {\n");
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_statement_indent(((depth) + (INT64_C(1)))));
                emitted = kofun_rt_text_concat(emitted, "kt_taken = true;\n");
            } else if (kofun_rt_starts_with(line, "while ")) {
                int64_t depth = kofun_rt_text_len(blocks);
                const char * condition = kofun_fn_lower_expression(
                    kofun_fn_header_condition(line, "while "), bound, "x",
                    kofun_fn_statement_indent(((depth) + (INT64_C(1)))));
                blocks = kofun_rt_text_concat(blocks, "w");
                bound = kofun_fn_scope_enter(bound);
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "{\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "bool kt_cond;\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "while (true) {\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_statements(condition));
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_statement_indent(((depth) + (INT64_C(1)))));
                emitted = kofun_rt_text_concat(emitted, "kt_cond = ");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_operand(condition));
                emitted = kofun_rt_text_concat(emitted, ";\n");
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_statement_indent(((depth) + (INT64_C(1)))));
                emitted = kofun_rt_text_concat(
                    emitted, "if (failed) return 1;\n");
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_statement_indent(((depth) + (INT64_C(1)))));
                emitted = kofun_rt_text_concat(
                    emitted, "if (!kt_cond) break;\n");
            } else if (kofun_rt_starts_with(line, "for ")) {
                int64_t depth = kofun_rt_text_len(blocks);
                const char * name = kofun_fn_range_name(line);
                const char * from = kofun_fn_lower_expression(
                    kofun_fn_range_start(line), bound, "xl",
                    kofun_fn_nested_indent(depth));
                const char * to = kofun_fn_lower_expression(
                    kofun_fn_range_end(line), bound, "xr",
                    kofun_fn_nested_indent(depth));
                blocks = kofun_rt_text_concat(blocks, "r");
                bound = kofun_rt_text_concat(
                    kofun_rt_text_concat(
                        kofun_rt_text_concat(
                            kofun_fn_scope_enter(bound), name), ":Int"),
                    "|");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "{\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_statements(from));
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "int64_t kt_from = ");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_operand(from));
                emitted = kofun_rt_text_concat(emitted, ";\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_statements(to));
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "int64_t kt_to = ");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_lowered_operand(to));
                emitted = kofun_rt_text_concat(emitted, ";\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(
                    emitted, "if (failed) return 1;\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "for (int64_t kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, " = kt_from; kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, " < kt_to; ++kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, ") {\n");
                emitted = kofun_rt_text_concat(
                    emitted,
                    kofun_fn_statement_indent(((depth) + (INT64_C(1)))));
                emitted = kofun_rt_text_concat(emitted, "(void)kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, ";\n");
            } else if (kofun_rt_starts_with(line, "let ")) {
                int64_t depth = kofun_rt_text_len(blocks);
                const char * name = kofun_fn_binding_name(line);
                const char * value = kofun_fn_lower_expression(
                    kofun_fn_binding_expression(line), bound, "x",
                    kofun_fn_nested_indent(depth));
                const char * kind = kofun_fn_lowered_type(value);
                const char * c_type = "int64_t";
                if (kofun_rt_text_equal(kind, "Bool")) {
                    c_type = "bool";
                } else if (kofun_rt_text_equal(kind, "Text")) {
                    c_type = "const char *";
                } else if (kofun_rt_text_equal(kind, "List[Text]")) {
                    c_type = "KofunTextList";
                }
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, c_type);
                emitted = kofun_rt_text_concat(emitted, " kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, ";\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "{\n");
                emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(value));
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_nested_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, " = ");
                emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(value));
                emitted = kofun_rt_text_concat(emitted, ";\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "}\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(
                    emitted, "if (failed) return 1;\n");
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "(void)kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, ";\n");
                bound = kofun_rt_text_concat(
                    kofun_rt_text_concat(
                        kofun_rt_text_concat(
                            kofun_rt_text_concat(bound, name), ":"),
                        kind),
                    "|");
            } else if (kofun_rt_starts_with(line, "print(")) {
                int64_t depth = kofun_rt_text_len(blocks);
                const char * value = kofun_fn_lower_expression(
                    kofun_fn_print_expression(line), bound, "x",
                    kofun_fn_nested_indent(depth));
                const char * kind = kofun_fn_lowered_type(value);
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "{\n");
                emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(value));
                if (kofun_rt_text_equal(kind, "Text")) {
                    emitted = kofun_rt_text_concat(
                        emitted, kofun_fn_nested_indent(depth));
                    emitted = kofun_rt_text_concat(
                        emitted, "const char * value = ");
                    emitted = kofun_rt_text_concat(
                        emitted, kofun_fn_lowered_operand(value));
                    emitted = kofun_rt_text_concat(emitted, ";\n");
                    emitted = kofun_rt_text_concat(
                        emitted, kofun_fn_nested_indent(depth));
                    emitted = kofun_rt_text_concat(
                        emitted, "if (failed) return 1;\n");
                    emitted = kofun_rt_text_concat(
                        emitted, kofun_fn_nested_indent(depth));
                    emitted = kofun_rt_text_concat(
                        emitted, "fputs(value, stdout);\n");
                    emitted = kofun_rt_text_concat(
                        emitted, kofun_fn_nested_indent(depth));
                    emitted = kofun_rt_text_concat(
                        emitted, "fputc('\\n', stdout);\n");
                } else {
                    emitted = kofun_rt_text_concat(
                        emitted, kofun_fn_nested_indent(depth));
                    emitted = kofun_rt_text_concat(
                        emitted, "int64_t value = ");
                    emitted = kofun_rt_text_concat(
                        emitted, kofun_fn_lowered_operand(value));
                    emitted = kofun_rt_text_concat(emitted, ";\n");
                    emitted = kofun_rt_text_concat(
                        emitted, kofun_fn_nested_indent(depth));
                    emitted = kofun_rt_text_concat(
                        emitted, "if (failed) return 1;\n");
                    emitted = kofun_rt_text_concat(
                        emitted, kofun_fn_nested_indent(depth));
                    emitted = kofun_rt_text_concat(
                        emitted, "printf(\"%\" PRId64 \"\\n\", value);\n");
                }
                emitted = kofun_rt_text_concat(
                    emitted, kofun_fn_statement_indent(depth));
                emitted = kofun_rt_text_concat(emitted, "}\n");
            }
            line_start = ((index) + (INT64_C(1)));
        }
    }
    return emitted;
}

static const char * kofun_fn_emit_c(const char * source) {
    const char * statements = kofun_fn_emit_statements(source);
    bool uses_text_index =
        ((kofun_rt_find(statements, "kofun_rt_text_index")) >=
         (INT64_C(0)));
    bool uses_list =
        ((kofun_rt_find(statements, "KofunTextList")) >= (INT64_C(0)));
    bool uses_text =
        (((kofun_rt_find(statements, "const char *")) >= (INT64_C(0))) ||
         ((kofun_rt_find(statements, "kofun_rt_text_")) >= (INT64_C(0))) ||
         uses_list);
    static const char text_headers[] =
        "#include <stdlib.h>\n"
        "#include <string.h>\n";
    static const char text_runtime[] =
        "typedef struct KofunTextAllocation {\n"
        "    struct KofunTextAllocation *next;\n"
        "    char bytes[];\n"
        "} KofunTextAllocation;\n\n"
        "static KofunTextAllocation *kofun_rt_text_allocations;\n\n"
        "static void kofun_rt_text_cleanup(void) {\n"
        "    while (kofun_rt_text_allocations != NULL) {\n"
        "        KofunTextAllocation *allocation = kofun_rt_text_allocations;\n"
        "        kofun_rt_text_allocations = allocation->next;\n"
        "        free(allocation);\n"
        "    }\n"
        "}\n\n"
        "static const char *kofun_rt_text_concat(const char *left, const char *right) {\n"
        "    size_t left_size = strlen(left);\n"
        "    size_t right_size = strlen(right);\n"
        "    if (right_size == SIZE_MAX || left_size > SIZE_MAX - right_size - 1) {\n"
        "        runtime_error(\"error[R010]: Text concatenation is too large\");\n"
        "        return \"\";\n"
        "    }\n"
        "    size_t payload_size = left_size + right_size + 1;\n"
        "    if (payload_size > SIZE_MAX - sizeof(KofunTextAllocation)) {\n"
        "        runtime_error(\"error[R010]: Text concatenation is too large\");\n"
        "        return \"\";\n"
        "    }\n"
        "    KofunTextAllocation *allocation =\n"
        "        malloc(sizeof(KofunTextAllocation) + payload_size);\n"
        "    if (allocation == NULL) {\n"
        "        runtime_error(\"error[R010]: Text allocation failed\");\n"
        "        return \"\";\n"
        "    }\n"
        "    memcpy(allocation->bytes, left, left_size);\n"
        "    memcpy(allocation->bytes + left_size, right, right_size);\n"
        "    allocation->bytes[left_size + right_size] = '\\0';\n"
        "    allocation->next = kofun_rt_text_allocations;\n"
        "    kofun_rt_text_allocations = allocation;\n"
        "    return allocation->bytes;\n"
        "}\n\n"
        "static bool kofun_rt_text_equal(const char *left, const char *right) {\n"
        "    return strcmp(left, right) == 0;\n"
        "}\n\n";
    static const char text_main[] =
        "    if (atexit(kofun_rt_text_cleanup) != 0) {\n"
        "        runtime_error(\"error[R010]: Text cleanup registration failed\");\n"
        "        return 1;\n"
        "    }\n"
        "    (void)kofun_rt_text_concat;\n"
        "    (void)kofun_rt_text_equal;\n";
    static const char text_index_runtime[] =
        "static const char *kofun_rt_text_index(const char *value, int64_t index) {\n"
        "    size_t length = strlen(value);\n"
        "    if (index < 0 || (uint64_t)index >= (uint64_t)length) {\n"
        "        runtime_error(\"error[R010]: Text index out of bounds\");\n"
        "        return \"\";\n"
        "    }\n"
        "    char character[2] = { value[index], '\\0' };\n"
        "    return kofun_rt_text_concat(\"\", character);\n"
        "}\n\n";
    static const char text_index_main[] =
        "    (void)kofun_rt_text_index;\n";
    static const char list_runtime[] =
        "typedef struct {\n"
        "    int64_t len;\n"
        "    const char **items;\n"
        "} KofunTextList;\n\n"
        "typedef struct KofunTextListAllocation {\n"
        "    struct KofunTextListAllocation *next;\n"
        "    const char *items[];\n"
        "} KofunTextListAllocation;\n\n"
        "static KofunTextListAllocation *kofun_rt_text_list_allocations;\n\n"
        "static void kofun_rt_text_list_cleanup(void) {\n"
        "    while (kofun_rt_text_list_allocations != NULL) {\n"
        "        KofunTextListAllocation *allocation =\n"
        "            kofun_rt_text_list_allocations;\n"
        "        kofun_rt_text_list_allocations = allocation->next;\n"
        "        free(allocation);\n"
        "    }\n"
        "}\n\n"
        "static KofunTextList kofun_rt_empty_text_list(void) {\n"
        "    KofunTextList result = { 0, NULL };\n"
        "    return result;\n"
        "}\n\n"
        "static KofunTextList kofun_rt_chars(const char *value) {\n"
        "    size_t length = strlen(value);\n"
        "    if ((uint64_t)length > (uint64_t)INT64_MAX ||\n"
        "        length > (SIZE_MAX - sizeof(KofunTextListAllocation)) /\n"
        "            sizeof(const char *)) {\n"
        "        runtime_error(\"error[R010]: List[Text] allocation is too large\");\n"
        "        return kofun_rt_empty_text_list();\n"
        "    }\n"
        "    KofunTextListAllocation *allocation = malloc(\n"
        "        sizeof(KofunTextListAllocation) + length * sizeof(const char *));\n"
        "    if (allocation == NULL) {\n"
        "        runtime_error(\"error[R010]: List[Text] allocation failed\");\n"
        "        return kofun_rt_empty_text_list();\n"
        "    }\n"
        "    allocation->next = kofun_rt_text_list_allocations;\n"
        "    kofun_rt_text_list_allocations = allocation;\n"
        "    for (size_t index = 0; index < length; ++index) {\n"
        "        char character[2] = { value[index], '\\0' };\n"
        "        allocation->items[index] =\n"
        "            kofun_rt_text_concat(\"\", character);\n"
        "        if (failed) return kofun_rt_empty_text_list();\n"
        "    }\n"
        "    KofunTextList result = {\n"
        "        (int64_t)length,\n"
        "        allocation->items,\n"
        "    };\n"
        "    return result;\n"
        "}\n\n"
        "static int64_t kofun_rt_text_list_len(KofunTextList values) {\n"
        "    return values.len;\n"
        "}\n\n"
        "static const char *kofun_rt_text_list_get(\n"
        "    KofunTextList values,\n"
        "    int64_t index\n"
        ") {\n"
        "    if (index < 0 || index >= values.len) {\n"
        "        runtime_error(\"error[R010]: List[Text] index out of bounds\");\n"
        "        return \"\";\n"
        "    }\n"
        "    return values.items[index];\n"
        "}\n\n";
    static const char list_main[] =
        "    if (atexit(kofun_rt_text_list_cleanup) != 0) {\n"
        "        runtime_error(\"error[R010]: List[Text] cleanup registration failed\");\n"
        "        return 1;\n"
        "    }\n"
        "    (void)kofun_rt_chars;\n"
        "    (void)kofun_rt_text_list_len;\n"
        "    (void)kofun_rt_text_list_get;\n";
    static const char *const preamble[] = {
        "/* Generated by the Kofun-written Stage 1 seed compiler. */\n",
        "#include <inttypes.h>\n",
        "#include <stdbool.h>\n",
        "#include <stdint.h>\n",
        "#include <stdio.h>\n",
        "static bool failed;\n\n",
        "static void runtime_error(const char *message) {\n",
        "    if (!failed) {\n",
        "        fputs(message, stderr);\n",
        "        fputc('\\n', stderr);\n",
        "    }\n",
        "    failed = true;\n",
        "}\n\n",
        "static int64_t checked_add(int64_t left, int64_t right) {\n",
        "    int64_t result;\n",
        "    if (__builtin_add_overflow(left, right, &result)) {\n",
        "        runtime_error(\"error[R010]: integer overflow in operator `+`\");\n",
        "        return 0;\n",
        "    }\n",
        "    return result;\n",
        "}\n\n",
        "static int64_t checked_sub(int64_t left, int64_t right) {\n",
        "    int64_t result;\n",
        "    if (__builtin_sub_overflow(left, right, &result)) {\n",
        "        runtime_error(\"error[R010]: integer overflow in operator `-`\");\n",
        "        return 0;\n",
        "    }\n",
        "    return result;\n",
        "}\n\n",
        "static int64_t checked_mul(int64_t left, int64_t right) {\n",
        "    int64_t result;\n",
        "    if (__builtin_mul_overflow(left, right, &result)) {\n",
        "        runtime_error(\"error[R010]: integer overflow in operator `*`\");\n",
        "        return 0;\n",
        "    }\n",
        "    return result;\n",
        "}\n\n",
        "static int64_t checked_neg(int64_t value) {\n",
        "    if (value == INT64_MIN) {\n",
        "        runtime_error(\"error[R010]: integer overflow in unary operator `-`\");\n",
        "        return 0;\n",
        "    }\n",
        "    return -value;\n",
        "}\n\n",
        "static int64_t floor_div(int64_t left, int64_t right) {\n",
        "    if (right == 0) {\n",
        "        runtime_error(\"error[R010]: operator `//` failed: division by zero\");\n",
        "        return 0;\n",
        "    }\n",
        "    if (left == INT64_MIN && right == -1) {\n",
        "        runtime_error(\"error[R010]: integer overflow in operator `//`\");\n",
        "        return 0;\n",
        "    }\n",
        "    int64_t quotient = left / right;\n",
        "    int64_t remainder = left % right;\n",
        "    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;\n",
        "    return quotient;\n",
        "}\n\n",
        "static int64_t floor_mod(int64_t left, int64_t right) {\n",
        "    if (right == 0) {\n",
        "        runtime_error(\"error[R010]: operator `%` failed: division by zero\");\n",
        "        return 0;\n",
        "    }\n",
        "    if (left == INT64_MIN && right == -1) return 0;\n",
        "    int64_t remainder = left % right;\n",
        "    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;\n",
        "    return remainder;\n",
        "}\n\n",
    };
    const char * emitted = "";
    for (size_t index = 0; index < sizeof(preamble) / sizeof(preamble[0]); ++index) {
        emitted = kofun_rt_text_concat(emitted, preamble[index]);
        if (index == 4) {
            if (uses_text) {
                emitted = kofun_rt_text_concat(emitted, text_headers);
            }
            emitted = kofun_rt_text_concat(emitted, "\n");
        }
    }
    if (uses_text) {
        emitted = kofun_rt_text_concat(emitted, text_runtime);
    }
    if (uses_text_index) {
        emitted = kofun_rt_text_concat(emitted, text_index_runtime);
    }
    if (uses_list) {
        emitted = kofun_rt_text_concat(emitted, list_runtime);
    }
    emitted = kofun_rt_text_concat(
        emitted,
        "int main(void) {\n"
        "    (void)checked_add;\n"
        "    (void)checked_sub;\n"
        "    (void)checked_mul;\n"
        "    (void)checked_neg;\n"
        "    (void)floor_div;\n"
        "    (void)floor_mod;\n");
    if (uses_text) {
        emitted = kofun_rt_text_concat(emitted, text_main);
    }
    if (uses_text_index) {
        emitted = kofun_rt_text_concat(emitted, text_index_main);
    }
    if (uses_list) {
        emitted = kofun_rt_text_concat(emitted, list_main);
    }
    emitted = kofun_rt_text_concat(emitted, statements);
    return kofun_rt_text_concat(emitted, "    return 0;\n}\n");
}

static bool kofun_fn_compile_file(const char * input_path, const char * output_path) {
    const char * input = kofun_rt_read_text(input_path);
    KofunUnicodeError unicode_error;
    if (!kofun_unicode_validate_source(
            (const uint8_t *)input,
            strlen(input),
            &unicode_error)) {
        char message[1024];
        kofun_unicode_format_error(
            &unicode_error,
            getenv("KOFUN_DIAGNOSTIC_LOCALE"),
            message,
            sizeof(message)
        );
        fprintf(stderr, "%s\n", message);
        return false;
    }
    const char * source = kofun_rt_text_concat(input, "\n");
    if ((!kofun_fn_valid_source(source))) {
        printf("%s\n", "compile error: unsupported Kofun integer Core source");
        return false;
    }
    const char * emitted = kofun_fn_emit_c(source);
    (void)(kofun_rt_write_text(output_path, emitted));
    printf("%s\n", output_path);
    return true;
}

static void kofun_fn_main(void) {
    kofun_text_list arguments = kofun_rt_args();
    if (((kofun_rt_text_list_len(arguments)) != (INT64_C(2)))) {
        printf("%s\n", "usage: kofun-stage1 INPUT.kofun OUTPUT.c");
        return;
    }
    if ((!(kofun_fn_compile_file(kofun_rt_text_list_get(arguments, INT64_C(0)), kofun_rt_text_list_get(arguments, INT64_C(1)))))) {
        kofun_rt_fail();
    }
    return;
}

int main(int argc, char **argv) {
    kofun_runtime_argc = argc > 0 ? argc - 1 : 0;
    kofun_runtime_argv = argc > 0 ? argv + 1 : argv;
    kofun_fn_main();
    return 0;
}
