/* Generated by Kofun bootstrap compiler. */
/* Source: bootstrap/stage1/compiler.kofun */
#include <stdbool.h>
#include <ctype.h>
#include <inttypes.h>
#include <math.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../../unicode/kofun_unicode.c"

typedef struct {
    int64_t len;
    const char **items;
} kofun_text_list;

int kofun_runtime_argc = 0;
char **kofun_runtime_argv = NULL;

void kofun_rt_panic(const char *message) {
    fprintf(stderr, "Kofun runtime error: %s\n", message);
    exit(1);
}

void kofun_rt_fail(void) {
    exit(1);
}

void *kofun_rt_alloc(size_t size) {
    void *value = malloc(size == 0 ? 1 : size);
    if (value == NULL) {
        kofun_rt_panic("out of memory");
    }
    return value;
}

char *kofun_rt_copy_n(const char *value, size_t length) {
    char *result = (char *)kofun_rt_alloc(length + 1);
    if (length > 0) {
        memcpy(result, value, length);
    }
    result[length] = '\0';
    return result;
}

char *kofun_rt_text_concat(const char *left, const char *right) {
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    char *result = (char *)kofun_rt_alloc(left_len + right_len + 1);
    memcpy(result, left, left_len);
    memcpy(result + left_len, right, right_len + 1);
    return result;
}

bool kofun_rt_text_equal(const char *left, const char *right) {
    return strcmp(left, right) == 0;
}

int64_t kofun_rt_text_len(const char *value) {
    return (int64_t)strlen(value);
}

int64_t kofun_rt_text_list_len(kofun_text_list values) {
    return values.len;
}

kofun_text_list kofun_rt_args(void) {
    kofun_text_list result;
    result.len = (int64_t)kofun_runtime_argc;
    result.items = (const char **)kofun_runtime_argv;
    return result;
}

kofun_text_list kofun_rt_chars(const char *value) {
    size_t length = strlen(value);
    const char **items = (const char **)kofun_rt_alloc(sizeof(char *) * (length == 0 ? 1 : length));
    for (size_t index = 0; index < length; ++index) {
        items[index] = kofun_rt_copy_n(value + index, 1);
    }
    kofun_text_list result;
    result.len = (int64_t)length;
    result.items = items;
    return result;
}

const char *kofun_rt_text_list_get(kofun_text_list values, int64_t index) {
    if (index < 0 || index >= values.len) {
        kofun_rt_panic("List[Text] index out of bounds");
    }
    return values.items[index];
}

const char *kofun_rt_text_index(const char *value, int64_t index) {
    int64_t length = (int64_t)strlen(value);
    if (index < 0 || index >= length) {
        kofun_rt_panic("Text index out of bounds");
    }
    return kofun_rt_copy_n(value + index, 1);
}

bool kofun_rt_text_contains(const char *value, const char *needle) {
    return strstr(value, needle) != NULL;
}

int64_t kofun_rt_find(const char *value, const char *needle) {
    const char *found = strstr(value, needle);
    return found == NULL ? INT64_C(-1) : (int64_t)(found - value);
}

char *kofun_rt_text_slice(const char *value, int64_t start, int64_t end) {
    int64_t length = (int64_t)strlen(value);
    if (start < 0) start = 0;
    if (end < start) end = start;
    if (start > length) start = length;
    if (end > length) end = length;
    return kofun_rt_copy_n(value + start, (size_t)(end - start));
}

char *kofun_rt_trim(const char *value) {
    const unsigned char *start = (const unsigned char *)value;
    while (*start != '\0' && isspace(*start)) {
        ++start;
    }
    const unsigned char *end = (const unsigned char *)value + strlen(value);
    while (end > start && isspace(end[-1])) {
        --end;
    }
    return kofun_rt_copy_n((const char *)start, (size_t)(end - start));
}

char *kofun_rt_replace(const char *value, const char *old, const char *replacement) {
    size_t old_len = strlen(old);
    if (old_len == 0) {
        return kofun_rt_copy_n(value, strlen(value));
    }
    size_t replacement_len = strlen(replacement);
    size_t count = 0;
    const char *cursor = value;
    while ((cursor = strstr(cursor, old)) != NULL) {
        ++count;
        cursor += old_len;
    }
    size_t value_len = strlen(value);
    size_t result_len;
    if (replacement_len >= old_len) {
        result_len = value_len + count * (replacement_len - old_len);
    } else {
        result_len = value_len - count * (old_len - replacement_len);
    }
    char *result = (char *)kofun_rt_alloc(result_len + 1);
    char *out = result;
    cursor = value;
    const char *match;
    while ((match = strstr(cursor, old)) != NULL) {
        size_t prefix = (size_t)(match - cursor);
        memcpy(out, cursor, prefix);
        out += prefix;
        memcpy(out, replacement, replacement_len);
        out += replacement_len;
        cursor = match + old_len;
    }
    strcpy(out, cursor);
    return result;
}

bool kofun_rt_starts_with(const char *value, const char *prefix) {
    size_t prefix_len = strlen(prefix);
    return strncmp(value, prefix, prefix_len) == 0;
}

bool kofun_rt_ends_with(const char *value, const char *suffix) {
    size_t value_len = strlen(value);
    size_t suffix_len = strlen(suffix);
    return suffix_len <= value_len && strcmp(value + value_len - suffix_len, suffix) == 0;
}

bool kofun_rt_is_digit(const char *value) {
    return value[0] != '\0' && value[1] == '\0' && isdigit((unsigned char)value[0]) != 0;
}

bool kofun_rt_is_space(const char *value) {
    return value[0] != '\0' && value[1] == '\0' && isspace((unsigned char)value[0]) != 0;
}

int64_t kofun_rt_parse_int(const char *value) {
    char *end = NULL;
    long long result = strtoll(value, &end, 10);
    if (end == value || *end != '\0') {
        kofun_rt_panic("invalid integer text");
    }
    return (int64_t)result;
}

char *kofun_rt_int_to_text(int64_t value) {
    char buffer[64];
    int written = snprintf(buffer, sizeof(buffer), "%" PRId64, value);
    if (written < 0) {
        kofun_rt_panic("integer formatting failed");
    }
    return kofun_rt_copy_n(buffer, (size_t)written);
}

char *kofun_rt_read_text(const char *path) {
    FILE *file = fopen(path, "rb");
    if (file == NULL) {
        kofun_rt_panic("cannot open input file");
    }
    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        kofun_rt_panic("cannot seek input file");
    }
    long size = ftell(file);
    if (size < 0) {
        fclose(file);
        kofun_rt_panic("cannot measure input file");
    }
    rewind(file);
    char *result = (char *)kofun_rt_alloc((size_t)size + 1);
    size_t read = fread(result, 1, (size_t)size, file);
    if (read != (size_t)size && ferror(file)) {
        fclose(file);
        kofun_rt_panic("cannot read input file");
    }
    result[read] = '\0';
    fclose(file);
    return result;
}

void kofun_rt_write_text(const char *path, const char *value) {
    FILE *file = fopen(path, "wb");
    if (file == NULL) {
        kofun_rt_panic("cannot open output file");
    }
    size_t length = strlen(value);
    if (fwrite(value, 1, length, file) != length) {
        fclose(file);
        kofun_rt_panic("cannot write output file");
    }
    if (fclose(file) != 0) {
        kofun_rt_panic("cannot close output file");
    }
}

static bool kofun_fn_identifier_char(const char * fr_char);
static bool kofun_fn_valid_name(const char * name);
static int64_t kofun_fn_digit_value(const char * symbol);
static bool kofun_fn_all_digits(const char * value);
static bool kofun_fn_within_bound(const char * digits, const char * bound);
static bool kofun_fn_preceded_by_operand(const char * expression, int64_t index);
static int64_t kofun_fn_split_binary(const char * expression, const char * operators);
static bool kofun_fn_wraps_whole(const char * expression);
static int64_t kofun_fn_last_newline(const char * value);
static const char * kofun_fn_lowered_statements(const char * lowered);
static const char * kofun_fn_lowered_operand(const char * lowered);
static const char * kofun_fn_lower_step(const char * path, const char * callee, const char * left, const char * right);
static const char * kofun_fn_lower_atom(const char * atom, const char * bound);
static const char * kofun_fn_lower_negation(const char * operand, const char * bound, const char * path);
static const char * kofun_fn_lower_expression(const char * expression, const char * bound, const char * path);
static const char * kofun_fn_print_expression(const char * line);
static const char * kofun_fn_binding_name(const char * line);
static const char * kofun_fn_binding_expression(const char * line);
static bool kofun_fn_valid_source(const char * source);
static const char * kofun_fn_emit_statements(const char * source);
static const char * kofun_fn_emit_c(const char * source);
static bool kofun_fn_compile_file(const char * input_path, const char * output_path);
static void kofun_fn_main(void);

static bool kofun_fn_identifier_char(const char * fr_char) {
    unsigned char first = (unsigned char)fr_char[0];
    return first >= UINT8_C(0x80) ||
        kofun_rt_is_digit(fr_char) ||
        kofun_rt_text_contains(
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_",
            fr_char
        );
}

static bool kofun_fn_valid_name(const char * name) {
    kofun_text_list symbols = kofun_rt_chars(name);
    if (((((kofun_rt_text_list_len(symbols)) == (INT64_C(0)))) || (kofun_rt_is_digit(kofun_rt_text_list_get(symbols, INT64_C(0)))))) {
        return false;
    }
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if ((!kofun_fn_identifier_char(kofun_rt_text_list_get(symbols, index)))) {
            return false;
        }
    }
    return true;
}

static int64_t kofun_fn_digit_value(const char * symbol) {
    return kofun_rt_find("0123456789", symbol);
}

static bool kofun_fn_all_digits(const char * value) {
    kofun_text_list symbols = kofun_rt_chars(value);
    if (((kofun_rt_text_list_len(symbols)) == (INT64_C(0)))) {
        return false;
    }
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if ((!kofun_rt_is_digit(kofun_rt_text_list_get(symbols, index)))) {
            return false;
        }
    }
    return true;
}

static bool kofun_fn_within_bound(const char * digits, const char * bound) {
    kofun_text_list symbols = kofun_rt_chars(digits);
    kofun_text_list limit = kofun_rt_chars(bound);
    int64_t start = INT64_C(0);
    while ((((start) + (INT64_C(1))) < (kofun_rt_text_list_len(symbols))) &&
           kofun_rt_text_equal(kofun_rt_text_list_get(symbols, start), "0")) {
        start = ((start) + (INT64_C(1)));
    }
    int64_t significant = ((kofun_rt_text_list_len(symbols)) - (start));
    if (((significant) != (kofun_rt_text_list_len(limit)))) {
        return ((significant) < (kofun_rt_text_list_len(limit)));
    }
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(limit); ++index) {
        int64_t left = kofun_fn_digit_value(
            kofun_rt_text_list_get(symbols, ((start) + (index))));
        int64_t right = kofun_fn_digit_value(kofun_rt_text_list_get(limit, index));
        if (((left) != (right))) {
            return ((left) < (right));
        }
    }
    return true;
}

static bool kofun_fn_preceded_by_operand(const char * expression, int64_t index) {
    kofun_text_list symbols = kofun_rt_chars(expression);
    int64_t cursor = ((index) - (INT64_C(1)));
    while (((cursor) >= (INT64_C(0)))) {
        const char * symbol = kofun_rt_text_list_get(symbols, cursor);
        if ((!kofun_rt_is_space(symbol))) {
            return ((kofun_rt_text_equal(symbol, ")")) ||
                    (kofun_fn_identifier_char(symbol)));
        }
        cursor = ((cursor) - (INT64_C(1)));
    }
    return false;
}

static int64_t kofun_fn_split_binary(const char * expression, const char * operators) {
    kofun_text_list symbols = kofun_rt_chars(expression);
    int64_t depth = INT64_C(0);
    int64_t found = INT64_C(-1);
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        const char * symbol = kofun_rt_text_list_get(symbols, index);
        if (kofun_rt_text_equal(symbol, "(")) {
            depth = ((depth) + (INT64_C(1)));
        } else if (kofun_rt_text_equal(symbol, ")")) {
            depth = ((depth) - (INT64_C(1)));
        } else if ((((depth) == (INT64_C(0)))) && (kofun_rt_text_contains(operators, symbol))) {
            if (kofun_fn_preceded_by_operand(expression, index)) {
                found = index;
            }
        }
    }
    return found;
}

static bool kofun_fn_wraps_whole(const char * expression) {
    kofun_text_list symbols = kofun_rt_chars(expression);
    if ((((kofun_rt_text_list_len(symbols)) < (INT64_C(2))) ||
         ((!kofun_rt_text_equal(kofun_rt_text_list_get(symbols, INT64_C(0)), "("))))) {
        return false;
    }
    int64_t depth = INT64_C(0);
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        const char * symbol = kofun_rt_text_list_get(symbols, index);
        if (kofun_rt_text_equal(symbol, "(")) {
            depth = ((depth) + (INT64_C(1)));
        } else if (kofun_rt_text_equal(symbol, ")")) {
            depth = ((depth) - (INT64_C(1)));
            if (((depth) == (INT64_C(0)))) {
                return ((index) == ((kofun_rt_text_list_len(symbols)) - (INT64_C(1))));
            }
        }
    }
    return false;
}

static int64_t kofun_fn_last_newline(const char * value) {
    kofun_text_list symbols = kofun_rt_chars(value);
    int64_t found = INT64_C(-1);
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if (kofun_rt_text_equal(kofun_rt_text_list_get(symbols, index), "\n")) {
            found = index;
        }
    }
    return found;
}

static const char * kofun_fn_lowered_statements(const char * lowered) {
    int64_t cut = kofun_fn_last_newline(lowered);
    if (((cut) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_text_slice(lowered, INT64_C(0), ((cut) + (INT64_C(1))));
}

static const char * kofun_fn_lowered_operand(const char * lowered) {
    int64_t cut = kofun_fn_last_newline(lowered);
    return kofun_rt_text_slice(lowered, ((cut) + (INT64_C(1))), kofun_rt_text_len(lowered));
}

static const char * kofun_fn_lower_step(const char * path, const char * callee, const char * left, const char * right) {
    const char * temporary = kofun_rt_text_concat("kt_", path);
    return kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_fn_lowered_statements(left), kofun_fn_lowered_statements(right)), "        int64_t "), temporary), " = "), callee), kofun_fn_lowered_operand(left)), ", "), kofun_rt_text_concat(kofun_fn_lowered_operand(right), ");\n")), temporary);
}

static const char * kofun_fn_lower_atom(const char * atom, const char * bound) {
    if (kofun_fn_all_digits(atom)) {
        if ((!kofun_fn_within_bound(atom, "9223372036854775807"))) {
            return "";
        }
        return atom;
    }
    if ((!kofun_fn_valid_name(atom))) {
        return "";
    }
    if (((kofun_rt_find(bound, kofun_rt_text_concat(kofun_rt_text_concat("|", atom), "|"))) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_text_concat("kf_", atom);
}

static const char * kofun_fn_lower_negation(const char * operand, const char * bound, const char * path) {
    const char * trimmed = kofun_rt_trim(operand);
    if (kofun_fn_all_digits(trimmed)) {
        if (kofun_fn_within_bound(trimmed, "9223372036854775807")) {
            return kofun_rt_text_concat("-", trimmed);
        }
        if (kofun_fn_within_bound(trimmed, "9223372036854775808")) {
            return "INT64_MIN";
        }
        return "";
    }
    const char * inner = kofun_fn_lower_expression(
        trimmed, bound, kofun_rt_text_concat(path, "u"));
    if (((kofun_rt_text_len(inner)) == (INT64_C(0)))) {
        return "";
    }
    const char * temporary = kofun_rt_text_concat("kt_", path);
    return kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_rt_text_concat(kofun_fn_lowered_statements(inner), "        int64_t "), temporary), " = checked_neg("), kofun_rt_text_concat(kofun_fn_lowered_operand(inner), ");\n")), temporary);
}

static const char * kofun_fn_lower_expression(const char * expression, const char * bound, const char * path) {
    const char * trimmed = kofun_rt_trim(expression);
    if (((kofun_rt_text_len(trimmed)) == (INT64_C(0)))) {
        return "";
    }

    int64_t additive = kofun_fn_split_binary(trimmed, "+-");
    if (((additive) >= (INT64_C(0)))) {
        const char * left = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(0), additive), bound,
            kofun_rt_text_concat(path, "l"));
        const char * right = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, ((additive) + (INT64_C(1))),
                                kofun_rt_text_len(trimmed)), bound,
            kofun_rt_text_concat(path, "r"));
        if ((((kofun_rt_text_len(left)) == (INT64_C(0))) ||
             ((kofun_rt_text_len(right)) == (INT64_C(0))))) {
            return "";
        }
        if (kofun_rt_text_equal(
                kofun_rt_text_slice(trimmed, additive, ((additive) + (INT64_C(1)))), "+")) {
            return kofun_fn_lower_step(path, "checked_add(", left, right);
        }
        return kofun_fn_lower_step(path, "checked_sub(", left, right);
    }

    int64_t multiplicative = kofun_fn_split_binary(trimmed, "*%/");
    if (((multiplicative) >= (INT64_C(0)))) {
        const char * operator_text = kofun_rt_text_slice(
            trimmed, multiplicative, ((multiplicative) + (INT64_C(1))));
        const char * callee = "checked_mul(";
        int64_t skip = INT64_C(1);
        if (kofun_rt_text_equal(operator_text, "%")) {
            callee = "floor_mod(";
        } else if (kofun_rt_text_equal(operator_text, "/")) {
            if ((((multiplicative) + (INT64_C(2))) > (kofun_rt_text_len(trimmed)))) {
                return "";
            }
            if ((!kofun_rt_text_equal(
                    kofun_rt_text_slice(trimmed, ((multiplicative) + (INT64_C(1))),
                                        ((multiplicative) + (INT64_C(2)))), "/"))) {
                return "";
            }
            callee = "floor_div(";
            skip = INT64_C(2);
        }
        const char * left = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(0), multiplicative), bound,
            kofun_rt_text_concat(path, "l"));
        const char * right = kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, ((multiplicative) + (skip)),
                                kofun_rt_text_len(trimmed)), bound,
            kofun_rt_text_concat(path, "r"));
        if ((((kofun_rt_text_len(left)) == (INT64_C(0))) ||
             ((kofun_rt_text_len(right)) == (INT64_C(0))))) {
            return "";
        }
        return kofun_fn_lower_step(path, callee, left, right);
    }

    if (kofun_rt_starts_with(trimmed, "+")) {
        return kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(1), kofun_rt_text_len(trimmed)), bound, path);
    }
    if (kofun_rt_starts_with(trimmed, "-")) {
        return kofun_fn_lower_negation(
            kofun_rt_text_slice(trimmed, INT64_C(1), kofun_rt_text_len(trimmed)), bound, path);
    }
    if (kofun_fn_wraps_whole(trimmed)) {
        return kofun_fn_lower_expression(
            kofun_rt_text_slice(trimmed, INT64_C(1),
                                ((kofun_rt_text_len(trimmed)) - (INT64_C(1)))), bound, path);
    }
    return kofun_fn_lower_atom(trimmed, bound);
}

static const char * kofun_fn_print_expression(const char * line) {
    const char * marker = "print(";
    int64_t start = kofun_rt_find(line, marker);
    if (((start) < (INT64_C(0)))) {
        return "";
    }
    int64_t expression_start = ((start) + (kofun_rt_text_len(marker)));
    kofun_text_list symbols = kofun_rt_chars(line);
    int64_t depth = INT64_C(1);
    int64_t index = expression_start;
    while (((index) < (kofun_rt_text_list_len(symbols)))) {
        const char * symbol = kofun_rt_text_list_get(symbols, index);
        if (kofun_rt_text_equal(symbol, "(")) {
            depth = ((depth) + (INT64_C(1)));
        } else if (kofun_rt_text_equal(symbol, ")")) {
            depth = ((depth) - (INT64_C(1)));
            if (((depth) == (INT64_C(0)))) {
                return kofun_rt_trim(kofun_rt_text_slice(line, expression_start, index));
            }
        }
        index = ((index) + (INT64_C(1)));
    }
    return "";
}

static const char * kofun_fn_binding_name(const char * line) {
    int64_t equals = kofun_rt_find(line, "=");
    if (((equals) < (INT64_C(0)))) {
        return "";
    }
    const char * name = kofun_rt_trim(kofun_rt_text_slice(line, INT64_C(4), equals));
    int64_t colon = kofun_rt_find(name, ":");
    if (((colon) >= (INT64_C(0)))) {
        return kofun_rt_trim(kofun_rt_text_slice(name, INT64_C(0), colon));
    }
    return name;
}

static const char * kofun_fn_binding_expression(const char * line) {
    int64_t equals = kofun_rt_find(line, "=");
    if (((equals) < (INT64_C(0)))) {
        return "";
    }
    return kofun_rt_trim(kofun_rt_text_slice(line, ((equals) + (INT64_C(1))), kofun_rt_text_len(line)));
}

static bool kofun_fn_valid_source(const char * source) {
    kofun_text_list symbols = kofun_rt_chars(source);
    int64_t line_start = INT64_C(0);
    int64_t prints = INT64_C(0);
    int64_t main_headers = INT64_C(0);
    int64_t body_depth = INT64_C(0);
    const char * bound = "|";
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if (kofun_rt_text_equal(kofun_rt_text_list_get(symbols, index), "\n")) {
            const char * line = kofun_rt_trim(kofun_rt_text_slice(source, line_start, index));
            if (((kofun_rt_text_len(line) == INT64_C(0)) || kofun_rt_starts_with(line, "#"))) {
            } else if (kofun_rt_text_equal(line, "fn main() {")) {
                if ((((main_headers) != (INT64_C(0))) || ((body_depth) != (INT64_C(0))))) {
                    return false;
                }
                main_headers = ((main_headers) + (INT64_C(1)));
                body_depth = INT64_C(1);
            } else if (kofun_rt_text_equal(line, "}")) {
                if (((body_depth) != (INT64_C(1)))) {
                    return false;
                }
                body_depth = INT64_C(0);
            } else if (kofun_rt_starts_with(line, "let ")) {
                if (((body_depth) != (INT64_C(1)))) {
                    return false;
                }
                const char * name = kofun_fn_binding_name(line);
                if ((!kofun_fn_valid_name(name))) {
                    return false;
                }
                if (((kofun_rt_find(bound, kofun_rt_text_concat(kofun_rt_text_concat("|", name), "|"))) >= (INT64_C(0)))) {
                    return false;
                }
                if (((kofun_rt_text_len(kofun_fn_lower_expression(kofun_fn_binding_expression(line), bound, "x"))) == (INT64_C(0)))) {
                    return false;
                }
                bound = kofun_rt_text_concat(kofun_rt_text_concat(bound, name), "|");
            } else if (kofun_rt_starts_with(line, "print(")) {
                if (((body_depth) != (INT64_C(1)))) {
                    return false;
                }
                const char * expression = kofun_fn_print_expression(line);
                if (((kofun_rt_text_len(kofun_fn_lower_expression(expression, bound, "x"))) == (INT64_C(0)))) {
                    return false;
                }
                prints = ((prints) + (INT64_C(1)));
            } else {
                return false;
            }
            line_start = ((index) + (INT64_C(1)));
        }
    }
    return (((((main_headers) == (INT64_C(1))) && ((body_depth) == (INT64_C(0))))) && ((prints) > (INT64_C(0))));
}

static const char * kofun_fn_emit_statements(const char * source) {
    kofun_text_list symbols = kofun_rt_chars(source);
    int64_t line_start = INT64_C(0);
    const char * emitted = "";
    const char * bound = "|";
    for (int64_t index = INT64_C(0); index < kofun_rt_text_list_len(symbols); ++index) {
        if (kofun_rt_text_equal(kofun_rt_text_list_get(symbols, index), "\n")) {
            const char * line = kofun_rt_trim(kofun_rt_text_slice(source, line_start, index));
            if (kofun_rt_starts_with(line, "let ")) {
                const char * name = kofun_fn_binding_name(line);
                const char * value = kofun_fn_lower_expression(kofun_fn_binding_expression(line), bound, "x");
                emitted = kofun_rt_text_concat(emitted, "    int64_t kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, ";\n    {\n");
                emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(value));
                emitted = kofun_rt_text_concat(emitted, "        kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, " = ");
                emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(value));
                emitted = kofun_rt_text_concat(emitted, ";\n    }\n    if (failed) return 1;\n    (void)kf_");
                emitted = kofun_rt_text_concat(emitted, name);
                emitted = kofun_rt_text_concat(emitted, ";\n");
                bound = kofun_rt_text_concat(kofun_rt_text_concat(bound, name), "|");
            } else if (kofun_rt_starts_with(line, "print(")) {
                const char * value = kofun_fn_lower_expression(kofun_fn_print_expression(line), bound, "x");
                emitted = kofun_rt_text_concat(emitted, "    {\n");
                emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_statements(value));
                emitted = kofun_rt_text_concat(emitted, "        int64_t value = ");
                emitted = kofun_rt_text_concat(emitted, kofun_fn_lowered_operand(value));
                emitted = kofun_rt_text_concat(emitted, ";\n        if (failed) return 1;\n");
                emitted = kofun_rt_text_concat(emitted, "        printf(\"%\" PRId64 \"\\n\", value);\n    }\n");
            }
            line_start = ((index) + (INT64_C(1)));
        }
    }
    return emitted;
}

static const char * kofun_fn_emit_c(const char * source) {
    static const char *const preamble[] = {
        "/* Generated by the Kofun-written Stage 1 seed compiler. */\n",
        "#include <inttypes.h>\n",
        "#include <stdbool.h>\n",
        "#include <stdint.h>\n",
        "#include <stdio.h>\n\n",
        "static bool failed;\n\n",
        "static void runtime_error(const char *message) {\n",
        "    if (!failed) {\n",
        "        fputs(message, stderr);\n",
        "        fputc('\\n', stderr);\n",
        "    }\n",
        "    failed = true;\n",
        "}\n\n",
        "static int64_t checked_add(int64_t left, int64_t right) {\n",
        "    int64_t result;\n",
        "    if (__builtin_add_overflow(left, right, &result)) {\n",
        "        runtime_error(\"error[R010]: integer overflow in operator `+`\");\n",
        "        return 0;\n",
        "    }\n",
        "    return result;\n",
        "}\n\n",
        "static int64_t checked_sub(int64_t left, int64_t right) {\n",
        "    int64_t result;\n",
        "    if (__builtin_sub_overflow(left, right, &result)) {\n",
        "        runtime_error(\"error[R010]: integer overflow in operator `-`\");\n",
        "        return 0;\n",
        "    }\n",
        "    return result;\n",
        "}\n\n",
        "static int64_t checked_mul(int64_t left, int64_t right) {\n",
        "    int64_t result;\n",
        "    if (__builtin_mul_overflow(left, right, &result)) {\n",
        "        runtime_error(\"error[R010]: integer overflow in operator `*`\");\n",
        "        return 0;\n",
        "    }\n",
        "    return result;\n",
        "}\n\n",
        "static int64_t checked_neg(int64_t value) {\n",
        "    if (value == INT64_MIN) {\n",
        "        runtime_error(\"error[R010]: integer overflow in unary operator `-`\");\n",
        "        return 0;\n",
        "    }\n",
        "    return -value;\n",
        "}\n\n",
        "static int64_t floor_div(int64_t left, int64_t right) {\n",
        "    if (right == 0) {\n",
        "        runtime_error(\"error[R010]: operator `//` failed: division by zero\");\n",
        "        return 0;\n",
        "    }\n",
        "    if (left == INT64_MIN && right == -1) {\n",
        "        runtime_error(\"error[R010]: integer overflow in operator `//`\");\n",
        "        return 0;\n",
        "    }\n",
        "    int64_t quotient = left / right;\n",
        "    int64_t remainder = left % right;\n",
        "    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;\n",
        "    return quotient;\n",
        "}\n\n",
        "static int64_t floor_mod(int64_t left, int64_t right) {\n",
        "    if (right == 0) {\n",
        "        runtime_error(\"error[R010]: operator `%` failed: division by zero\");\n",
        "        return 0;\n",
        "    }\n",
        "    if (left == INT64_MIN && right == -1) return 0;\n",
        "    int64_t remainder = left % right;\n",
        "    if (remainder != 0 && ((remainder < 0) != (right < 0))) remainder += right;\n",
        "    return remainder;\n",
        "}\n\n",
        "int main(void) {\n",
        "    (void)checked_add;\n",
        "    (void)checked_sub;\n",
        "    (void)checked_mul;\n",
        "    (void)checked_neg;\n",
        "    (void)floor_div;\n",
        "    (void)floor_mod;\n",
    };
    const char * emitted = "";
    for (size_t index = 0; index < sizeof(preamble) / sizeof(preamble[0]); ++index) {
        emitted = kofun_rt_text_concat(emitted, preamble[index]);
    }
    emitted = kofun_rt_text_concat(emitted, kofun_fn_emit_statements(source));
    return kofun_rt_text_concat(emitted, "    return 0;\n}\n");
}

static bool kofun_fn_compile_file(const char * input_path, const char * output_path) {
    const char * input = kofun_rt_read_text(input_path);
    KofunUnicodeError unicode_error;
    if (!kofun_unicode_validate_source(
            (const uint8_t *)input,
            strlen(input),
            &unicode_error)) {
        char message[1024];
        kofun_unicode_format_error(
            &unicode_error,
            getenv("KOFUN_DIAGNOSTIC_LOCALE"),
            message,
            sizeof(message)
        );
        fprintf(stderr, "%s\n", message);
        return false;
    }
    const char * source = kofun_rt_text_concat(input, "\n");
    if ((!kofun_fn_valid_source(source))) {
        printf("%s\n", "compile error: unsupported Kofun integer Core source");
        return false;
    }
    const char * emitted = kofun_fn_emit_c(source);
    (void)(kofun_rt_write_text(output_path, emitted));
    printf("%s\n", output_path);
    return true;
}

static void kofun_fn_main(void) {
    kofun_text_list arguments = kofun_rt_args();
    if (((kofun_rt_text_list_len(arguments)) != (INT64_C(2)))) {
        printf("%s\n", "usage: kofun-stage1 INPUT.kofun OUTPUT.c");
        return;
    }
    if ((!(kofun_fn_compile_file(kofun_rt_text_list_get(arguments, INT64_C(0)), kofun_rt_text_list_get(arguments, INT64_C(1)))))) {
        kofun_rt_fail();
    }
    return;
}

int main(int argc, char **argv) {
    kofun_runtime_argc = argc > 0 ? argc - 1 : 0;
    kofun_runtime_argv = argc > 0 ? argv + 1 : argv;
    kofun_fn_main();
    return 0;
}
